version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    open-pull-requests-limit: 10
    groups:
      kotlin-and-compose:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.compose*"
      androidx:
        patterns:
          - "androidx.*"
          - "com.android.*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Budapest
    open-pull-requests-limit: 10
