[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "21"
sample-android-minSdk = "23"
android-targetSdk = "36"
androidx-activity = "1.13.0"
androidx-appcompat = "1.8.0"
buildconfig = "6.0.10"
composeMultiplatform = "1.11.1"
composeMaterial3 = "1.11.0-alpha07"
composeMaterialIconsExtended = "1.7.3"
koin = "4.2.2"
koin-compiler = "1.1.0"
kotlin = "2.3.21"
kotlinx-coroutines = "1.11.0"
navigation3 = "1.1.1"
navigation3-runtime = "1.1.6"
skiko = "0.9.22.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeMaterialIconsExtended" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3-runtime" }
skiko-awt = { module = "org.jetbrains.skiko:skiko-awt", version.ref = "skiko" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
buildconfig-gradlePlugin = { module = "com.github.gmazzo.buildconfig:plugin", version.ref = "buildconfig" }
composeCompiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
composeMultiplatform-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "composeMultiplatform" }
kotlinMultiplatform-gradlePlugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
koinCompiler-gradlePlugin = { module = "io.insert-koin:koin-compiler-gradle-plugin", version.ref = "koin-compiler" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
koinCompiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-compiler" }
symbolsKotlinMultiplatformLibrary = { id = "io.github.hlcaptain.symbols.kotlin-multiplatform-library" }
symbolsComposeMultiplatformLibrary = { id = "io.github.hlcaptain.symbols.compose-multiplatform-library" }
symbolsKmpPublishing = { id = "io.github.hlcaptain.symbols.kmp-publishing" }
symbolsMaterialFontLibrary = { id = "io.github.hlcaptain.symbols.material-font-library" }
symbolsMaterialVectorLibrary = { id = "io.github.hlcaptain.symbols.material-vector-library" }
symbolsPublishedAndroidLibrary = { id = "io.github.hlcaptain.symbols.published-android-library" }
symbolsSampleFeature = { id = "io.github.hlcaptain.symbols.sample-feature" }
