[versions]
pluginPublish = "2.1.1"
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "21"
sample-android-minSdk = "23"
android-targetSdk = "36"
androidx-activity = "1.13.0"
androidx-appcompat = "1.8.0"
buildconfig = "6.0.10"
composeMultiplatform = "1.12.0"
composeMaterial3 = "1.13.0-alpha01"
composeMaterialIconsExtended = "1.7.3"
koin = "4.2.2"
koin-compiler = "1.1.0"
kotlin = "2.4.20"
kotlinx-coroutines = "1.11.0"
navigation3 = "1.1.1"
navigation3-runtime = "1.1.6"
androidx-compose = "1.11.4"
androidx-test = "1.7.0"
androidx-benchmark = "1.4.1"
androidx-uiautomator = "2.3.0"
androidx-profileinstaller = "1.4.1"
composePreviewScanner = "0.9.1"
junit = "4.13.2"
robolectric = "4.16.1"
roborazzi = "1.72.0"
skiko = "0.9.22.2"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "composeMaterialIconsExtended" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMaterial3" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }
navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3-runtime" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-compose" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-uiautomator" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
composePreviewScanner-android = { module = "io.github.sergio-sastre.ComposablePreviewScanner:android", version.ref = "composePreviewScanner" }
junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
roborazzi = { module = "io.github.takahirom.roborazzi:roborazzi", version.ref = "roborazzi" }
roborazzi-compose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
roborazzi-composePreviewScannerSupport = { module = "io.github.takahirom.roborazzi:roborazzi-compose-preview-scanner-support", version.ref = "roborazzi" }
skiko-awt = { module = "org.jetbrains.skiko:skiko-awt", version.ref = "skiko" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
android-gradleApi = { module = "com.android.tools.build:gradle-api", version.ref = "agp" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
buildconfig-gradlePlugin = { module = "com.github.gmazzo.buildconfig:plugin", version.ref = "buildconfig" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
composeCompiler-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
composeMultiplatform-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "composeMultiplatform" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinMultiplatform-gradlePlugin = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }
koinCompiler-gradlePlugin = { module = "io.insert-koin:koin-compiler-gradle-plugin", version.ref = "koin-compiler" }
symbols-gradlePlugin = { module = "io.github.hlcaptain:symbol-gradle-plugin" }

[plugins]
gradlePluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidTest = { id = "com.android.test", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
koinCompiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-compiler" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
symbolFonts = { id = "io.github.hlcaptain.symbol-fonts" }
symbolsKotlinMultiplatformLibrary = { id = "io.github.hlcaptain.symbols.kotlin-multiplatform-library" }
symbolsComposeMultiplatformLibrary = { id = "io.github.hlcaptain.symbols.compose-multiplatform-library" }
symbolsKmpPublishing = { id = "io.github.hlcaptain.symbols.kmp-publishing" }
symbolsMaterialFontLibrary = { id = "io.github.hlcaptain.symbols.material-font-library" }
symbolsMaterialVectorSources = { id = "io.github.hlcaptain.symbols.material-vector-sources" }
symbolsMaterialVectorLibrary = { id = "io.github.hlcaptain.symbols.material-vector-library" }
symbolsPublishedAndroidLibrary = { id = "io.github.hlcaptain.symbols.published-android-library" }
symbolsSampleFeature = { id = "io.github.hlcaptain.symbols.sample-feature" }
