// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.LightOff as OutlinedLightOff
import io.github.hlcaptain.symbols.material.rounded.vectors.LightOff as RoundedLightOff
import io.github.hlcaptain.symbols.material.sharp.vectors.LightOff as SharpLightOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Lightbulb as OutlinedLightbulb
import io.github.hlcaptain.symbols.material.rounded.vectors.Lightbulb as RoundedLightbulb
import io.github.hlcaptain.symbols.material.sharp.vectors.Lightbulb as SharpLightbulb
import io.github.hlcaptain.symbols.material.outlined.vectors.Lightbulb2 as OutlinedLightbulb2
import io.github.hlcaptain.symbols.material.rounded.vectors.Lightbulb2 as RoundedLightbulb2
import io.github.hlcaptain.symbols.material.sharp.vectors.Lightbulb2 as SharpLightbulb2
import io.github.hlcaptain.symbols.material.outlined.vectors.LightbulbCircle as OutlinedLightbulbCircle
import io.github.hlcaptain.symbols.material.rounded.vectors.LightbulbCircle as RoundedLightbulbCircle
import io.github.hlcaptain.symbols.material.sharp.vectors.LightbulbCircle as SharpLightbulbCircle
import io.github.hlcaptain.symbols.material.outlined.vectors.LightbulbOutline as OutlinedLightbulbOutline
import io.github.hlcaptain.symbols.material.rounded.vectors.LightbulbOutline as RoundedLightbulbOutline
import io.github.hlcaptain.symbols.material.sharp.vectors.LightbulbOutline as SharpLightbulbOutline
import io.github.hlcaptain.symbols.material.outlined.vectors.LightningStand as OutlinedLightningStand
import io.github.hlcaptain.symbols.material.rounded.vectors.LightningStand as RoundedLightningStand
import io.github.hlcaptain.symbols.material.sharp.vectors.LightningStand as SharpLightningStand
import io.github.hlcaptain.symbols.material.outlined.vectors.LineAxis as OutlinedLineAxis
import io.github.hlcaptain.symbols.material.rounded.vectors.LineAxis as RoundedLineAxis
import io.github.hlcaptain.symbols.material.sharp.vectors.LineAxis as SharpLineAxis
import io.github.hlcaptain.symbols.material.outlined.vectors.LineCurve as OutlinedLineCurve
import io.github.hlcaptain.symbols.material.rounded.vectors.LineCurve as RoundedLineCurve
import io.github.hlcaptain.symbols.material.sharp.vectors.LineCurve as SharpLineCurve
import io.github.hlcaptain.symbols.material.outlined.vectors.LineEnd as OutlinedLineEnd
import io.github.hlcaptain.symbols.material.rounded.vectors.LineEnd as RoundedLineEnd
import io.github.hlcaptain.symbols.material.sharp.vectors.LineEnd as SharpLineEnd
import io.github.hlcaptain.symbols.material.outlined.vectors.LineEndArrow as OutlinedLineEndArrow
import io.github.hlcaptain.symbols.material.rounded.vectors.LineEndArrow as RoundedLineEndArrow
import io.github.hlcaptain.symbols.material.sharp.vectors.LineEndArrow as SharpLineEndArrow
import io.github.hlcaptain.symbols.material.outlined.vectors.LineEndArrowNotch as OutlinedLineEndArrowNotch
import io.github.hlcaptain.symbols.material.rounded.vectors.LineEndArrowNotch as RoundedLineEndArrowNotch
import io.github.hlcaptain.symbols.material.sharp.vectors.LineEndArrowNotch as SharpLineEndArrowNotch
import io.github.hlcaptain.symbols.material.outlined.vectors.LineEndCircle as OutlinedLineEndCircle
import io.github.hlcaptain.symbols.material.rounded.vectors.LineEndCircle as RoundedLineEndCircle
import io.github.hlcaptain.symbols.material.sharp.vectors.LineEndCircle as SharpLineEndCircle
import io.github.hlcaptain.symbols.material.outlined.vectors.LineEndDiamond as OutlinedLineEndDiamond
import io.github.hlcaptain.symbols.material.rounded.vectors.LineEndDiamond as RoundedLineEndDiamond
import io.github.hlcaptain.symbols.material.sharp.vectors.LineEndDiamond as SharpLineEndDiamond
import io.github.hlcaptain.symbols.material.outlined.vectors.LineEndSquare as OutlinedLineEndSquare
import io.github.hlcaptain.symbols.material.rounded.vectors.LineEndSquare as RoundedLineEndSquare
import io.github.hlcaptain.symbols.material.sharp.vectors.LineEndSquare as SharpLineEndSquare
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStart as OutlinedLineStart
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStart as RoundedLineStart
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStart as SharpLineStart
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStartArrow as OutlinedLineStartArrow
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStartArrow as RoundedLineStartArrow
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStartArrow as SharpLineStartArrow
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStartArrowNotch as OutlinedLineStartArrowNotch
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStartArrowNotch as RoundedLineStartArrowNotch
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStartArrowNotch as SharpLineStartArrowNotch
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStartCircle as OutlinedLineStartCircle
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStartCircle as RoundedLineStartCircle
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStartCircle as SharpLineStartCircle
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStartDiamond as OutlinedLineStartDiamond
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStartDiamond as RoundedLineStartDiamond
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStartDiamond as SharpLineStartDiamond
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStartSquare as OutlinedLineStartSquare
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStartSquare as RoundedLineStartSquare
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStartSquare as SharpLineStartSquare
import io.github.hlcaptain.symbols.material.outlined.vectors.LineStyle as OutlinedLineStyle
import io.github.hlcaptain.symbols.material.rounded.vectors.LineStyle as RoundedLineStyle
import io.github.hlcaptain.symbols.material.sharp.vectors.LineStyle as SharpLineStyle
import io.github.hlcaptain.symbols.material.outlined.vectors.LineWeight as OutlinedLineWeight
import io.github.hlcaptain.symbols.material.rounded.vectors.LineWeight as RoundedLineWeight
import io.github.hlcaptain.symbols.material.sharp.vectors.LineWeight as SharpLineWeight
import io.github.hlcaptain.symbols.material.outlined.vectors.LinearScale as OutlinedLinearScale
import io.github.hlcaptain.symbols.material.rounded.vectors.LinearScale as RoundedLinearScale
import io.github.hlcaptain.symbols.material.sharp.vectors.LinearScale as SharpLinearScale
import io.github.hlcaptain.symbols.material.outlined.vectors.Link as OutlinedLink
import io.github.hlcaptain.symbols.material.rounded.vectors.Link as RoundedLink
import io.github.hlcaptain.symbols.material.sharp.vectors.Link as SharpLink
import io.github.hlcaptain.symbols.material.outlined.vectors.LinkOff as OutlinedLinkOff
import io.github.hlcaptain.symbols.material.rounded.vectors.LinkOff as RoundedLinkOff
import io.github.hlcaptain.symbols.material.sharp.vectors.LinkOff as SharpLinkOff
import io.github.hlcaptain.symbols.material.outlined.vectors.LinkedCamera as OutlinedLinkedCamera
import io.github.hlcaptain.symbols.material.rounded.vectors.LinkedCamera as RoundedLinkedCamera
import io.github.hlcaptain.symbols.material.sharp.vectors.LinkedCamera as SharpLinkedCamera
import io.github.hlcaptain.symbols.material.outlined.vectors.LinkedServices as OutlinedLinkedServices
import io.github.hlcaptain.symbols.material.rounded.vectors.LinkedServices as RoundedLinkedServices
import io.github.hlcaptain.symbols.material.sharp.vectors.LinkedServices as SharpLinkedServices
import io.github.hlcaptain.symbols.material.outlined.vectors.Liquor as OutlinedLiquor
import io.github.hlcaptain.symbols.material.rounded.vectors.Liquor as RoundedLiquor
import io.github.hlcaptain.symbols.material.sharp.vectors.Liquor as SharpLiquor
import io.github.hlcaptain.symbols.material.outlined.vectors.List as OutlinedList
import io.github.hlcaptain.symbols.material.rounded.vectors.List as RoundedList
import io.github.hlcaptain.symbols.material.sharp.vectors.List as SharpList
import io.github.hlcaptain.symbols.material.outlined.vectors.ListAlt as OutlinedListAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ListAlt as RoundedListAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ListAlt as SharpListAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ListAltAdd as OutlinedListAltAdd
import io.github.hlcaptain.symbols.material.rounded.vectors.ListAltAdd as RoundedListAltAdd
import io.github.hlcaptain.symbols.material.sharp.vectors.ListAltAdd as SharpListAltAdd
import io.github.hlcaptain.symbols.material.outlined.vectors.ListAltCheck as OutlinedListAltCheck
import io.github.hlcaptain.symbols.material.rounded.vectors.ListAltCheck as RoundedListAltCheck
import io.github.hlcaptain.symbols.material.sharp.vectors.ListAltCheck as SharpListAltCheck
import io.github.hlcaptain.symbols.material.outlined.vectors.Lists as OutlinedLists
import io.github.hlcaptain.symbols.material.rounded.vectors.Lists as RoundedLists
import io.github.hlcaptain.symbols.material.sharp.vectors.Lists as SharpLists
import io.github.hlcaptain.symbols.material.outlined.vectors.LiveHelp as OutlinedLiveHelp
import io.github.hlcaptain.symbols.material.rounded.vectors.LiveHelp as RoundedLiveHelp
import io.github.hlcaptain.symbols.material.sharp.vectors.LiveHelp as SharpLiveHelp
import io.github.hlcaptain.symbols.material.outlined.vectors.LiveTv as OutlinedLiveTv
import io.github.hlcaptain.symbols.material.rounded.vectors.LiveTv as RoundedLiveTv
import io.github.hlcaptain.symbols.material.sharp.vectors.LiveTv as SharpLiveTv
import io.github.hlcaptain.symbols.material.outlined.vectors.Living as OutlinedLiving
import io.github.hlcaptain.symbols.material.rounded.vectors.Living as RoundedLiving
import io.github.hlcaptain.symbols.material.sharp.vectors.Living as SharpLiving
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalActivity as OutlinedLocalActivity
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalActivity as RoundedLocalActivity
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalActivity as SharpLocalActivity
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalAirport as OutlinedLocalAirport
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalAirport as RoundedLocalAirport
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalAirport as SharpLocalAirport
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalAtm as OutlinedLocalAtm
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalAtm as RoundedLocalAtm
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalAtm as SharpLocalAtm
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalBar as OutlinedLocalBar
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalBar as RoundedLocalBar
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalBar as SharpLocalBar
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalCafe as OutlinedLocalCafe
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalCafe as RoundedLocalCafe
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalCafe as SharpLocalCafe
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalCarWash as OutlinedLocalCarWash
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalCarWash as RoundedLocalCarWash
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalCarWash as SharpLocalCarWash
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalConvenienceStore as OutlinedLocalConvenienceStore
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalConvenienceStore as RoundedLocalConvenienceStore
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalConvenienceStore as SharpLocalConvenienceStore
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalDining as OutlinedLocalDining
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalDining as RoundedLocalDining
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalDining as SharpLocalDining
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalDrink as OutlinedLocalDrink
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalDrink as RoundedLocalDrink
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalDrink as SharpLocalDrink
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalFireDepartment as OutlinedLocalFireDepartment
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalFireDepartment as RoundedLocalFireDepartment
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalFireDepartment as SharpLocalFireDepartment
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalFlorist as OutlinedLocalFlorist
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalFlorist as RoundedLocalFlorist
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalFlorist as SharpLocalFlorist
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalGasStation as OutlinedLocalGasStation
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalGasStation as RoundedLocalGasStation
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalGasStation as SharpLocalGasStation
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalGroceryStore as OutlinedLocalGroceryStore
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalGroceryStore as RoundedLocalGroceryStore
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalGroceryStore as SharpLocalGroceryStore
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalHospital as OutlinedLocalHospital
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalHospital as RoundedLocalHospital
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalHospital as SharpLocalHospital
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalHotel as OutlinedLocalHotel
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalHotel as RoundedLocalHotel
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalHotel as SharpLocalHotel
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalLaundryService as OutlinedLocalLaundryService
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalLaundryService as RoundedLocalLaundryService
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalLaundryService as SharpLocalLaundryService
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalLibrary as OutlinedLocalLibrary
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalLibrary as RoundedLocalLibrary
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalLibrary as SharpLocalLibrary
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalMall as OutlinedLocalMall
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalMall as RoundedLocalMall
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalMall as SharpLocalMall
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalMovies as OutlinedLocalMovies
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalMovies as RoundedLocalMovies
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalMovies as SharpLocalMovies
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalOffer as OutlinedLocalOffer
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalOffer as RoundedLocalOffer
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalOffer as SharpLocalOffer
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalParking as OutlinedLocalParking
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalParking as RoundedLocalParking
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalParking as SharpLocalParking
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPharmacy as OutlinedLocalPharmacy
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPharmacy as RoundedLocalPharmacy
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPharmacy as SharpLocalPharmacy
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPhone as OutlinedLocalPhone
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPhone as RoundedLocalPhone
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPhone as SharpLocalPhone
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPizza as OutlinedLocalPizza
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPizza as RoundedLocalPizza
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPizza as SharpLocalPizza
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPlay as OutlinedLocalPlay
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPlay as RoundedLocalPlay
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPlay as SharpLocalPlay
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPolice as OutlinedLocalPolice
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPolice as RoundedLocalPolice
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPolice as SharpLocalPolice
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPostOffice as OutlinedLocalPostOffice
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPostOffice as RoundedLocalPostOffice
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPostOffice as SharpLocalPostOffice
import io.github.hlcaptain.symbols.material.outlined.vectors.LocalPrintshop as OutlinedLocalPrintshop
import io.github.hlcaptain.symbols.material.rounded.vectors.LocalPrintshop as RoundedLocalPrintshop
import io.github.hlcaptain.symbols.material.sharp.vectors.LocalPrintshop as SharpLocalPrintshop

public val Icons.Themed.LightOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLightOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLightOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLightOff
    }

public val Icons.Themed.Lightbulb: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLightbulb
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLightbulb
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLightbulb
    }

public val Icons.Themed.Lightbulb2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLightbulb2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLightbulb2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLightbulb2
    }

public val Icons.Themed.LightbulbCircle: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLightbulbCircle
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLightbulbCircle
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLightbulbCircle
    }

public val Icons.Themed.LightbulbOutline: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLightbulbOutline
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLightbulbOutline
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLightbulbOutline
    }

public val Icons.Themed.LightningStand: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLightningStand
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLightningStand
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLightningStand
    }

public val Icons.Themed.LineAxis: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineAxis
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineAxis
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineAxis
    }

public val Icons.Themed.LineCurve: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineCurve
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineCurve
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineCurve
    }

public val Icons.Themed.LineEnd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineEnd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineEnd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineEnd
    }

public val Icons.Themed.LineEndArrow: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineEndArrow
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineEndArrow
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineEndArrow
    }

public val Icons.Themed.LineEndArrowNotch: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineEndArrowNotch
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineEndArrowNotch
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineEndArrowNotch
    }

public val Icons.Themed.LineEndCircle: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineEndCircle
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineEndCircle
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineEndCircle
    }

public val Icons.Themed.LineEndDiamond: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineEndDiamond
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineEndDiamond
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineEndDiamond
    }

public val Icons.Themed.LineEndSquare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineEndSquare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineEndSquare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineEndSquare
    }

public val Icons.Themed.LineStart: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStart
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStart
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStart
    }

public val Icons.Themed.LineStartArrow: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStartArrow
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStartArrow
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStartArrow
    }

public val Icons.Themed.LineStartArrowNotch: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStartArrowNotch
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStartArrowNotch
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStartArrowNotch
    }

public val Icons.Themed.LineStartCircle: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStartCircle
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStartCircle
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStartCircle
    }

public val Icons.Themed.LineStartDiamond: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStartDiamond
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStartDiamond
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStartDiamond
    }

public val Icons.Themed.LineStartSquare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStartSquare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStartSquare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStartSquare
    }

public val Icons.Themed.LineStyle: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineStyle
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineStyle
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineStyle
    }

public val Icons.Themed.LineWeight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLineWeight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLineWeight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLineWeight
    }

public val Icons.Themed.LinearScale: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLinearScale
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLinearScale
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLinearScale
    }

public val Icons.Themed.Link: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLink
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLink
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLink
    }

public val Icons.Themed.LinkOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLinkOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLinkOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLinkOff
    }

public val Icons.Themed.LinkedCamera: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLinkedCamera
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLinkedCamera
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLinkedCamera
    }

public val Icons.Themed.LinkedServices: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLinkedServices
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLinkedServices
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLinkedServices
    }

public val Icons.Themed.Liquor: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLiquor
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLiquor
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLiquor
    }

public val Icons.Themed.List: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedList
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedList
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpList
    }

public val Icons.Themed.ListAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedListAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedListAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpListAlt
    }

public val Icons.Themed.ListAltAdd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedListAltAdd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedListAltAdd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpListAltAdd
    }

public val Icons.Themed.ListAltCheck: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedListAltCheck
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedListAltCheck
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpListAltCheck
    }

public val Icons.Themed.Lists: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLists
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLists
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLists
    }

public val Icons.Themed.LiveHelp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLiveHelp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLiveHelp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLiveHelp
    }

public val Icons.Themed.LiveTv: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLiveTv
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLiveTv
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLiveTv
    }

public val Icons.Themed.Living: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLiving
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLiving
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLiving
    }

public val Icons.Themed.LocalActivity: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalActivity
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalActivity
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalActivity
    }

public val Icons.Themed.LocalAirport: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalAirport
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalAirport
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalAirport
    }

public val Icons.Themed.LocalAtm: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalAtm
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalAtm
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalAtm
    }

public val Icons.Themed.LocalBar: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalBar
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalBar
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalBar
    }

public val Icons.Themed.LocalCafe: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalCafe
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalCafe
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalCafe
    }

public val Icons.Themed.LocalCarWash: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalCarWash
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalCarWash
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalCarWash
    }

public val Icons.Themed.LocalConvenienceStore: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalConvenienceStore
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalConvenienceStore
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalConvenienceStore
    }

public val Icons.Themed.LocalDining: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalDining
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalDining
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalDining
    }

public val Icons.Themed.LocalDrink: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalDrink
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalDrink
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalDrink
    }

public val Icons.Themed.LocalFireDepartment: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalFireDepartment
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalFireDepartment
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalFireDepartment
    }

public val Icons.Themed.LocalFlorist: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalFlorist
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalFlorist
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalFlorist
    }

public val Icons.Themed.LocalGasStation: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalGasStation
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalGasStation
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalGasStation
    }

public val Icons.Themed.LocalGroceryStore: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalGroceryStore
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalGroceryStore
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalGroceryStore
    }

public val Icons.Themed.LocalHospital: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalHospital
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalHospital
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalHospital
    }

public val Icons.Themed.LocalHotel: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalHotel
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalHotel
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalHotel
    }

public val Icons.Themed.LocalLaundryService: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalLaundryService
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalLaundryService
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalLaundryService
    }

public val Icons.Themed.LocalLibrary: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalLibrary
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalLibrary
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalLibrary
    }

public val Icons.Themed.LocalMall: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalMall
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalMall
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalMall
    }

public val Icons.Themed.LocalMovies: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalMovies
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalMovies
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalMovies
    }

public val Icons.Themed.LocalOffer: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalOffer
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalOffer
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalOffer
    }

public val Icons.Themed.LocalParking: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalParking
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalParking
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalParking
    }

public val Icons.Themed.LocalPharmacy: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPharmacy
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPharmacy
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPharmacy
    }

public val Icons.Themed.LocalPhone: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPhone
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPhone
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPhone
    }

public val Icons.Themed.LocalPizza: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPizza
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPizza
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPizza
    }

public val Icons.Themed.LocalPlay: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPlay
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPlay
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPlay
    }

public val Icons.Themed.LocalPolice: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPolice
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPolice
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPolice
    }

public val Icons.Themed.LocalPostOffice: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPostOffice
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPostOffice
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPostOffice
    }

public val Icons.Themed.LocalPrintshop: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedLocalPrintshop
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedLocalPrintshop
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpLocalPrintshop
    }
