// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.MicExternalOff as OutlinedMicExternalOff
import io.github.hlcaptain.symbols.material.rounded.vectors.MicExternalOff as RoundedMicExternalOff
import io.github.hlcaptain.symbols.material.sharp.vectors.MicExternalOff as SharpMicExternalOff
import io.github.hlcaptain.symbols.material.outlined.vectors.MicExternalOn as OutlinedMicExternalOn
import io.github.hlcaptain.symbols.material.rounded.vectors.MicExternalOn as RoundedMicExternalOn
import io.github.hlcaptain.symbols.material.sharp.vectors.MicExternalOn as SharpMicExternalOn
import io.github.hlcaptain.symbols.material.outlined.vectors.MicNone as OutlinedMicNone
import io.github.hlcaptain.symbols.material.rounded.vectors.MicNone as RoundedMicNone
import io.github.hlcaptain.symbols.material.sharp.vectors.MicNone as SharpMicNone
import io.github.hlcaptain.symbols.material.outlined.vectors.MicOff as OutlinedMicOff
import io.github.hlcaptain.symbols.material.rounded.vectors.MicOff as RoundedMicOff
import io.github.hlcaptain.symbols.material.sharp.vectors.MicOff as SharpMicOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Microbiology as OutlinedMicrobiology
import io.github.hlcaptain.symbols.material.rounded.vectors.Microbiology as RoundedMicrobiology
import io.github.hlcaptain.symbols.material.sharp.vectors.Microbiology as SharpMicrobiology
import io.github.hlcaptain.symbols.material.outlined.vectors.Microwave as OutlinedMicrowave
import io.github.hlcaptain.symbols.material.rounded.vectors.Microwave as RoundedMicrowave
import io.github.hlcaptain.symbols.material.sharp.vectors.Microwave as SharpMicrowave
import io.github.hlcaptain.symbols.material.outlined.vectors.MicrowaveGen as OutlinedMicrowaveGen
import io.github.hlcaptain.symbols.material.rounded.vectors.MicrowaveGen as RoundedMicrowaveGen
import io.github.hlcaptain.symbols.material.sharp.vectors.MicrowaveGen as SharpMicrowaveGen
import io.github.hlcaptain.symbols.material.outlined.vectors.MilitaryTech as OutlinedMilitaryTech
import io.github.hlcaptain.symbols.material.rounded.vectors.MilitaryTech as RoundedMilitaryTech
import io.github.hlcaptain.symbols.material.sharp.vectors.MilitaryTech as SharpMilitaryTech
import io.github.hlcaptain.symbols.material.outlined.vectors.Mimo as OutlinedMimo
import io.github.hlcaptain.symbols.material.rounded.vectors.Mimo as RoundedMimo
import io.github.hlcaptain.symbols.material.sharp.vectors.Mimo as SharpMimo
import io.github.hlcaptain.symbols.material.outlined.vectors.MimoDisconnect as OutlinedMimoDisconnect
import io.github.hlcaptain.symbols.material.rounded.vectors.MimoDisconnect as RoundedMimoDisconnect
import io.github.hlcaptain.symbols.material.sharp.vectors.MimoDisconnect as SharpMimoDisconnect
import io.github.hlcaptain.symbols.material.outlined.vectors.Mindfulness as OutlinedMindfulness
import io.github.hlcaptain.symbols.material.rounded.vectors.Mindfulness as RoundedMindfulness
import io.github.hlcaptain.symbols.material.sharp.vectors.Mindfulness as SharpMindfulness
import io.github.hlcaptain.symbols.material.outlined.vectors.Minimize as OutlinedMinimize
import io.github.hlcaptain.symbols.material.rounded.vectors.Minimize as RoundedMinimize
import io.github.hlcaptain.symbols.material.sharp.vectors.Minimize as SharpMinimize
import io.github.hlcaptain.symbols.material.outlined.vectors.MinorCrash as OutlinedMinorCrash
import io.github.hlcaptain.symbols.material.rounded.vectors.MinorCrash as RoundedMinorCrash
import io.github.hlcaptain.symbols.material.sharp.vectors.MinorCrash as SharpMinorCrash
import io.github.hlcaptain.symbols.material.outlined.vectors.Mintmark as OutlinedMintmark
import io.github.hlcaptain.symbols.material.rounded.vectors.Mintmark as RoundedMintmark
import io.github.hlcaptain.symbols.material.sharp.vectors.Mintmark as SharpMintmark
import io.github.hlcaptain.symbols.material.outlined.vectors.MissedVideoCall as OutlinedMissedVideoCall
import io.github.hlcaptain.symbols.material.rounded.vectors.MissedVideoCall as RoundedMissedVideoCall
import io.github.hlcaptain.symbols.material.sharp.vectors.MissedVideoCall as SharpMissedVideoCall
import io.github.hlcaptain.symbols.material.outlined.vectors.MissedVideoCallFilled as OutlinedMissedVideoCallFilled
import io.github.hlcaptain.symbols.material.rounded.vectors.MissedVideoCallFilled as RoundedMissedVideoCallFilled
import io.github.hlcaptain.symbols.material.sharp.vectors.MissedVideoCallFilled as SharpMissedVideoCallFilled
import io.github.hlcaptain.symbols.material.outlined.vectors.MissingController as OutlinedMissingController
import io.github.hlcaptain.symbols.material.rounded.vectors.MissingController as RoundedMissingController
import io.github.hlcaptain.symbols.material.sharp.vectors.MissingController as SharpMissingController
import io.github.hlcaptain.symbols.material.outlined.vectors.Mist as OutlinedMist
import io.github.hlcaptain.symbols.material.rounded.vectors.Mist as RoundedMist
import io.github.hlcaptain.symbols.material.sharp.vectors.Mist as SharpMist
import io.github.hlcaptain.symbols.material.outlined.vectors.Mitre as OutlinedMitre
import io.github.hlcaptain.symbols.material.rounded.vectors.Mitre as RoundedMitre
import io.github.hlcaptain.symbols.material.sharp.vectors.Mitre as SharpMitre
import io.github.hlcaptain.symbols.material.outlined.vectors.MixtureMed as OutlinedMixtureMed
import io.github.hlcaptain.symbols.material.rounded.vectors.MixtureMed as RoundedMixtureMed
import io.github.hlcaptain.symbols.material.sharp.vectors.MixtureMed as SharpMixtureMed
import io.github.hlcaptain.symbols.material.outlined.vectors.Mms as OutlinedMms
import io.github.hlcaptain.symbols.material.rounded.vectors.Mms as RoundedMms
import io.github.hlcaptain.symbols.material.sharp.vectors.Mms as SharpMms
import io.github.hlcaptain.symbols.material.outlined.vectors.Mobile as OutlinedMobile
import io.github.hlcaptain.symbols.material.rounded.vectors.Mobile as RoundedMobile
import io.github.hlcaptain.symbols.material.sharp.vectors.Mobile as SharpMobile
import io.github.hlcaptain.symbols.material.outlined.vectors.Mobile2 as OutlinedMobile2
import io.github.hlcaptain.symbols.material.rounded.vectors.Mobile2 as RoundedMobile2
import io.github.hlcaptain.symbols.material.sharp.vectors.Mobile2 as SharpMobile2
import io.github.hlcaptain.symbols.material.outlined.vectors.Mobile3 as OutlinedMobile3
import io.github.hlcaptain.symbols.material.rounded.vectors.Mobile3 as RoundedMobile3
import io.github.hlcaptain.symbols.material.sharp.vectors.Mobile3 as SharpMobile3
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileAlert as OutlinedMobileAlert
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileAlert as RoundedMobileAlert
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileAlert as SharpMobileAlert
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileArrowDown as OutlinedMobileArrowDown
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileArrowDown as RoundedMobileArrowDown
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileArrowDown as SharpMobileArrowDown
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileArrowRight as OutlinedMobileArrowRight
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileArrowRight as RoundedMobileArrowRight
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileArrowRight as SharpMobileArrowRight
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileArrowUpRight as OutlinedMobileArrowUpRight
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileArrowUpRight as RoundedMobileArrowUpRight
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileArrowUpRight as SharpMobileArrowUpRight
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileBlock as OutlinedMobileBlock
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileBlock as RoundedMobileBlock
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileBlock as SharpMobileBlock
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCamera as OutlinedMobileCamera
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCamera as RoundedMobileCamera
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCamera as SharpMobileCamera
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCameraFront as OutlinedMobileCameraFront
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCameraFront as RoundedMobileCameraFront
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCameraFront as SharpMobileCameraFront
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCameraRear as OutlinedMobileCameraRear
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCameraRear as RoundedMobileCameraRear
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCameraRear as SharpMobileCameraRear
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCancel as OutlinedMobileCancel
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCancel as RoundedMobileCancel
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCancel as SharpMobileCancel
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCast as OutlinedMobileCast
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCast as RoundedMobileCast
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCast as SharpMobileCast
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCharge as OutlinedMobileCharge
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCharge as RoundedMobileCharge
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCharge as SharpMobileCharge
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileChat as OutlinedMobileChat
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileChat as RoundedMobileChat
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileChat as SharpMobileChat
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCheck as OutlinedMobileCheck
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCheck as RoundedMobileCheck
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCheck as SharpMobileCheck
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileCode as OutlinedMobileCode
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileCode as RoundedMobileCode
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileCode as SharpMobileCode
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileDots as OutlinedMobileDots
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileDots as RoundedMobileDots
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileDots as SharpMobileDots
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileFriendly as OutlinedMobileFriendly
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileFriendly as RoundedMobileFriendly
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileFriendly as SharpMobileFriendly
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileGear as OutlinedMobileGear
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileGear as RoundedMobileGear
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileGear as SharpMobileGear
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileHand as OutlinedMobileHand
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileHand as RoundedMobileHand
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileHand as SharpMobileHand
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileHandLeft as OutlinedMobileHandLeft
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileHandLeft as RoundedMobileHandLeft
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileHandLeft as SharpMobileHandLeft
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileHandLeftOff as OutlinedMobileHandLeftOff
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileHandLeftOff as RoundedMobileHandLeftOff
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileHandLeftOff as SharpMobileHandLeftOff
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileHandOff as OutlinedMobileHandOff
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileHandOff as RoundedMobileHandOff
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileHandOff as SharpMobileHandOff
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileInfo as OutlinedMobileInfo
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileInfo as RoundedMobileInfo
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileInfo as SharpMobileInfo
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileLandscape as OutlinedMobileLandscape
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileLandscape as RoundedMobileLandscape
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileLandscape as SharpMobileLandscape
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileLayout as OutlinedMobileLayout
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileLayout as RoundedMobileLayout
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileLayout as SharpMobileLayout
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileLockLandscape as OutlinedMobileLockLandscape
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileLockLandscape as RoundedMobileLockLandscape
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileLockLandscape as SharpMobileLockLandscape
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileLockPortrait as OutlinedMobileLockPortrait
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileLockPortrait as RoundedMobileLockPortrait
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileLockPortrait as SharpMobileLockPortrait
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileLoupe as OutlinedMobileLoupe
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileLoupe as RoundedMobileLoupe
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileLoupe as SharpMobileLoupe
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileMenu as OutlinedMobileMenu
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileMenu as RoundedMobileMenu
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileMenu as SharpMobileMenu
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileOff as OutlinedMobileOff
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileOff as RoundedMobileOff
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileOff as SharpMobileOff
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileQuestion as OutlinedMobileQuestion
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileQuestion as RoundedMobileQuestion
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileQuestion as SharpMobileQuestion
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileRotate as OutlinedMobileRotate
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileRotate as RoundedMobileRotate
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileRotate as SharpMobileRotate
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileRotateLock as OutlinedMobileRotateLock
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileRotateLock as RoundedMobileRotateLock
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileRotateLock as SharpMobileRotateLock
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileScreenShare as OutlinedMobileScreenShare
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileScreenShare as RoundedMobileScreenShare
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileScreenShare as SharpMobileScreenShare
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileScreensaver as OutlinedMobileScreensaver
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileScreensaver as RoundedMobileScreensaver
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileScreensaver as SharpMobileScreensaver
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileSensorHi as OutlinedMobileSensorHi
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileSensorHi as RoundedMobileSensorHi
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileSensorHi as SharpMobileSensorHi
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileSensorLo as OutlinedMobileSensorLo
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileSensorLo as RoundedMobileSensorLo
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileSensorLo as SharpMobileSensorLo
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileShare as OutlinedMobileShare
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileShare as RoundedMobileShare
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileShare as SharpMobileShare
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileShareStack as OutlinedMobileShareStack
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileShareStack as RoundedMobileShareStack
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileShareStack as SharpMobileShareStack
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileSound as OutlinedMobileSound
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileSound as RoundedMobileSound
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileSound as SharpMobileSound
import io.github.hlcaptain.symbols.material.outlined.vectors.MobileSound2 as OutlinedMobileSound2
import io.github.hlcaptain.symbols.material.rounded.vectors.MobileSound2 as RoundedMobileSound2
import io.github.hlcaptain.symbols.material.sharp.vectors.MobileSound2 as SharpMobileSound2

public val Icons.Themed.MicExternalOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicExternalOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicExternalOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicExternalOff
    }

public val Icons.Themed.MicExternalOn: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicExternalOn
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicExternalOn
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicExternalOn
    }

public val Icons.Themed.MicNone: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicNone
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicNone
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicNone
    }

public val Icons.Themed.MicOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicOff
    }

public val Icons.Themed.Microbiology: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicrobiology
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicrobiology
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicrobiology
    }

public val Icons.Themed.Microwave: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicrowave
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicrowave
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicrowave
    }

public val Icons.Themed.MicrowaveGen: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMicrowaveGen
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMicrowaveGen
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMicrowaveGen
    }

public val Icons.Themed.MilitaryTech: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMilitaryTech
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMilitaryTech
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMilitaryTech
    }

public val Icons.Themed.Mimo: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMimo
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMimo
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMimo
    }

public val Icons.Themed.MimoDisconnect: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMimoDisconnect
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMimoDisconnect
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMimoDisconnect
    }

public val Icons.Themed.Mindfulness: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMindfulness
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMindfulness
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMindfulness
    }

public val Icons.Themed.Minimize: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMinimize
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMinimize
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMinimize
    }

public val Icons.Themed.MinorCrash: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMinorCrash
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMinorCrash
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMinorCrash
    }

public val Icons.Themed.Mintmark: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMintmark
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMintmark
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMintmark
    }

public val Icons.Themed.MissedVideoCall: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMissedVideoCall
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMissedVideoCall
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMissedVideoCall
    }

public val Icons.Themed.MissedVideoCallFilled: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMissedVideoCallFilled
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMissedVideoCallFilled
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMissedVideoCallFilled
    }

public val Icons.Themed.MissingController: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMissingController
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMissingController
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMissingController
    }

public val Icons.Themed.Mist: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMist
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMist
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMist
    }

public val Icons.Themed.Mitre: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMitre
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMitre
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMitre
    }

public val Icons.Themed.MixtureMed: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMixtureMed
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMixtureMed
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMixtureMed
    }

public val Icons.Themed.Mms: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMms
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMms
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMms
    }

public val Icons.Themed.Mobile: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobile
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobile
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobile
    }

public val Icons.Themed.Mobile2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobile2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobile2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobile2
    }

public val Icons.Themed.Mobile3: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobile3
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobile3
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobile3
    }

public val Icons.Themed.MobileAlert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileAlert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileAlert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileAlert
    }

public val Icons.Themed.MobileArrowDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileArrowDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileArrowDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileArrowDown
    }

public val Icons.Themed.MobileArrowRight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileArrowRight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileArrowRight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileArrowRight
    }

public val Icons.Themed.MobileArrowUpRight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileArrowUpRight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileArrowUpRight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileArrowUpRight
    }

public val Icons.Themed.MobileBlock: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileBlock
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileBlock
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileBlock
    }

public val Icons.Themed.MobileCamera: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCamera
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCamera
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCamera
    }

public val Icons.Themed.MobileCameraFront: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCameraFront
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCameraFront
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCameraFront
    }

public val Icons.Themed.MobileCameraRear: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCameraRear
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCameraRear
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCameraRear
    }

public val Icons.Themed.MobileCancel: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCancel
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCancel
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCancel
    }

public val Icons.Themed.MobileCast: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCast
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCast
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCast
    }

public val Icons.Themed.MobileCharge: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCharge
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCharge
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCharge
    }

public val Icons.Themed.MobileChat: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileChat
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileChat
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileChat
    }

public val Icons.Themed.MobileCheck: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCheck
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCheck
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCheck
    }

public val Icons.Themed.MobileCode: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileCode
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileCode
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileCode
    }

public val Icons.Themed.MobileDots: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileDots
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileDots
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileDots
    }

public val Icons.Themed.MobileFriendly: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileFriendly
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileFriendly
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileFriendly
    }

public val Icons.Themed.MobileGear: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileGear
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileGear
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileGear
    }

public val Icons.Themed.MobileHand: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileHand
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileHand
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileHand
    }

public val Icons.Themed.MobileHandLeft: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileHandLeft
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileHandLeft
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileHandLeft
    }

public val Icons.Themed.MobileHandLeftOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileHandLeftOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileHandLeftOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileHandLeftOff
    }

public val Icons.Themed.MobileHandOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileHandOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileHandOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileHandOff
    }

public val Icons.Themed.MobileInfo: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileInfo
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileInfo
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileInfo
    }

public val Icons.Themed.MobileLandscape: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileLandscape
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileLandscape
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileLandscape
    }

public val Icons.Themed.MobileLayout: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileLayout
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileLayout
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileLayout
    }

public val Icons.Themed.MobileLockLandscape: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileLockLandscape
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileLockLandscape
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileLockLandscape
    }

public val Icons.Themed.MobileLockPortrait: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileLockPortrait
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileLockPortrait
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileLockPortrait
    }

public val Icons.Themed.MobileLoupe: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileLoupe
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileLoupe
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileLoupe
    }

public val Icons.Themed.MobileMenu: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileMenu
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileMenu
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileMenu
    }

public val Icons.Themed.MobileOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileOff
    }

public val Icons.Themed.MobileQuestion: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileQuestion
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileQuestion
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileQuestion
    }

public val Icons.Themed.MobileRotate: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileRotate
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileRotate
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileRotate
    }

public val Icons.Themed.MobileRotateLock: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileRotateLock
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileRotateLock
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileRotateLock
    }

public val Icons.Themed.MobileScreenShare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileScreenShare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileScreenShare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileScreenShare
    }

public val Icons.Themed.MobileScreensaver: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileScreensaver
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileScreensaver
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileScreensaver
    }

public val Icons.Themed.MobileSensorHi: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileSensorHi
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileSensorHi
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileSensorHi
    }

public val Icons.Themed.MobileSensorLo: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileSensorLo
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileSensorLo
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileSensorLo
    }

public val Icons.Themed.MobileShare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileShare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileShare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileShare
    }

public val Icons.Themed.MobileShareStack: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileShareStack
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileShareStack
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileShareStack
    }

public val Icons.Themed.MobileSound: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileSound
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileSound
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileSound
    }

public val Icons.Themed.MobileSound2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedMobileSound2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedMobileSound2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpMobileSound2
    }
