// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme as SymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.SelectAll as OutlinedSelectAll
import io.github.hlcaptain.symbols.material.rounded.vectors.SelectAll as RoundedSelectAll
import io.github.hlcaptain.symbols.material.sharp.vectors.SelectAll as SharpSelectAll
import io.github.hlcaptain.symbols.material.outlined.vectors.SelectCheckBox as OutlinedSelectCheckBox
import io.github.hlcaptain.symbols.material.rounded.vectors.SelectCheckBox as RoundedSelectCheckBox
import io.github.hlcaptain.symbols.material.sharp.vectors.SelectCheckBox as SharpSelectCheckBox
import io.github.hlcaptain.symbols.material.outlined.vectors.SelectToSpeak as OutlinedSelectToSpeak
import io.github.hlcaptain.symbols.material.rounded.vectors.SelectToSpeak as RoundedSelectToSpeak
import io.github.hlcaptain.symbols.material.sharp.vectors.SelectToSpeak as SharpSelectToSpeak
import io.github.hlcaptain.symbols.material.outlined.vectors.SelectWindow as OutlinedSelectWindow
import io.github.hlcaptain.symbols.material.rounded.vectors.SelectWindow as RoundedSelectWindow
import io.github.hlcaptain.symbols.material.sharp.vectors.SelectWindow as SharpSelectWindow
import io.github.hlcaptain.symbols.material.outlined.vectors.SelectWindow2 as OutlinedSelectWindow2
import io.github.hlcaptain.symbols.material.rounded.vectors.SelectWindow2 as RoundedSelectWindow2
import io.github.hlcaptain.symbols.material.sharp.vectors.SelectWindow2 as SharpSelectWindow2
import io.github.hlcaptain.symbols.material.outlined.vectors.SelectWindowOff as OutlinedSelectWindowOff
import io.github.hlcaptain.symbols.material.rounded.vectors.SelectWindowOff as RoundedSelectWindowOff
import io.github.hlcaptain.symbols.material.sharp.vectors.SelectWindowOff as SharpSelectWindowOff
import io.github.hlcaptain.symbols.material.outlined.vectors.SelfCare as OutlinedSelfCare
import io.github.hlcaptain.symbols.material.rounded.vectors.SelfCare as RoundedSelfCare
import io.github.hlcaptain.symbols.material.sharp.vectors.SelfCare as SharpSelfCare
import io.github.hlcaptain.symbols.material.outlined.vectors.SelfImprovement as OutlinedSelfImprovement
import io.github.hlcaptain.symbols.material.rounded.vectors.SelfImprovement as RoundedSelfImprovement
import io.github.hlcaptain.symbols.material.sharp.vectors.SelfImprovement as SharpSelfImprovement
import io.github.hlcaptain.symbols.material.outlined.vectors.Sell as OutlinedSell
import io.github.hlcaptain.symbols.material.rounded.vectors.Sell as RoundedSell
import io.github.hlcaptain.symbols.material.sharp.vectors.Sell as SharpSell
import io.github.hlcaptain.symbols.material.outlined.vectors.Send as OutlinedSend
import io.github.hlcaptain.symbols.material.rounded.vectors.Send as RoundedSend
import io.github.hlcaptain.symbols.material.sharp.vectors.Send as SharpSend
import io.github.hlcaptain.symbols.material.outlined.vectors.SendAndArchive as OutlinedSendAndArchive
import io.github.hlcaptain.symbols.material.rounded.vectors.SendAndArchive as RoundedSendAndArchive
import io.github.hlcaptain.symbols.material.sharp.vectors.SendAndArchive as SharpSendAndArchive
import io.github.hlcaptain.symbols.material.outlined.vectors.SendMoney as OutlinedSendMoney
import io.github.hlcaptain.symbols.material.rounded.vectors.SendMoney as RoundedSendMoney
import io.github.hlcaptain.symbols.material.sharp.vectors.SendMoney as SharpSendMoney
import io.github.hlcaptain.symbols.material.outlined.vectors.SendTimeExtension as OutlinedSendTimeExtension
import io.github.hlcaptain.symbols.material.rounded.vectors.SendTimeExtension as RoundedSendTimeExtension
import io.github.hlcaptain.symbols.material.sharp.vectors.SendTimeExtension as SharpSendTimeExtension
import io.github.hlcaptain.symbols.material.outlined.vectors.SendToMobile as OutlinedSendToMobile
import io.github.hlcaptain.symbols.material.rounded.vectors.SendToMobile as RoundedSendToMobile
import io.github.hlcaptain.symbols.material.sharp.vectors.SendToMobile as SharpSendToMobile
import io.github.hlcaptain.symbols.material.outlined.vectors.SensorDoor as OutlinedSensorDoor
import io.github.hlcaptain.symbols.material.rounded.vectors.SensorDoor as RoundedSensorDoor
import io.github.hlcaptain.symbols.material.sharp.vectors.SensorDoor as SharpSensorDoor
import io.github.hlcaptain.symbols.material.outlined.vectors.SensorOccupied as OutlinedSensorOccupied
import io.github.hlcaptain.symbols.material.rounded.vectors.SensorOccupied as RoundedSensorOccupied
import io.github.hlcaptain.symbols.material.sharp.vectors.SensorOccupied as SharpSensorOccupied
import io.github.hlcaptain.symbols.material.outlined.vectors.SensorWindow as OutlinedSensorWindow
import io.github.hlcaptain.symbols.material.rounded.vectors.SensorWindow as RoundedSensorWindow
import io.github.hlcaptain.symbols.material.sharp.vectors.SensorWindow as SharpSensorWindow
import io.github.hlcaptain.symbols.material.outlined.vectors.Sensors as OutlinedSensors
import io.github.hlcaptain.symbols.material.rounded.vectors.Sensors as RoundedSensors
import io.github.hlcaptain.symbols.material.sharp.vectors.Sensors as SharpSensors
import io.github.hlcaptain.symbols.material.outlined.vectors.SensorsKrx as OutlinedSensorsKrx
import io.github.hlcaptain.symbols.material.rounded.vectors.SensorsKrx as RoundedSensorsKrx
import io.github.hlcaptain.symbols.material.sharp.vectors.SensorsKrx as SharpSensorsKrx
import io.github.hlcaptain.symbols.material.outlined.vectors.SensorsKrxOff as OutlinedSensorsKrxOff
import io.github.hlcaptain.symbols.material.rounded.vectors.SensorsKrxOff as RoundedSensorsKrxOff
import io.github.hlcaptain.symbols.material.sharp.vectors.SensorsKrxOff as SharpSensorsKrxOff
import io.github.hlcaptain.symbols.material.outlined.vectors.SensorsOff as OutlinedSensorsOff
import io.github.hlcaptain.symbols.material.rounded.vectors.SensorsOff as RoundedSensorsOff
import io.github.hlcaptain.symbols.material.sharp.vectors.SensorsOff as SharpSensorsOff
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentCalm as OutlinedSentimentCalm
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentCalm as RoundedSentimentCalm
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentCalm as SharpSentimentCalm
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentContent as OutlinedSentimentContent
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentContent as RoundedSentimentContent
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentContent as SharpSentimentContent
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentDissatisfied as OutlinedSentimentDissatisfied
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentDissatisfied as RoundedSentimentDissatisfied
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentDissatisfied as SharpSentimentDissatisfied
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentExcited as OutlinedSentimentExcited
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentExcited as RoundedSentimentExcited
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentExcited as SharpSentimentExcited
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentExtremelyDissatisfied as OutlinedSentimentExtremelyDissatisfied
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentExtremelyDissatisfied as RoundedSentimentExtremelyDissatisfied
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentExtremelyDissatisfied as SharpSentimentExtremelyDissatisfied
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentFrustrated as OutlinedSentimentFrustrated
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentFrustrated as RoundedSentimentFrustrated
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentFrustrated as SharpSentimentFrustrated
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentNeutral as OutlinedSentimentNeutral
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentNeutral as RoundedSentimentNeutral
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentNeutral as SharpSentimentNeutral
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentSad as OutlinedSentimentSad
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentSad as RoundedSentimentSad
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentSad as SharpSentimentSad
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentSatisfied as OutlinedSentimentSatisfied
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentSatisfied as RoundedSentimentSatisfied
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentSatisfied as SharpSentimentSatisfied
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentSatisfiedAlt as OutlinedSentimentSatisfiedAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentSatisfiedAlt as RoundedSentimentSatisfiedAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentSatisfiedAlt as SharpSentimentSatisfiedAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentStressed as OutlinedSentimentStressed
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentStressed as RoundedSentimentStressed
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentStressed as SharpSentimentStressed
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentVeryDissatisfied as OutlinedSentimentVeryDissatisfied
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentVeryDissatisfied as RoundedSentimentVeryDissatisfied
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentVeryDissatisfied as SharpSentimentVeryDissatisfied
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentVerySatisfied as OutlinedSentimentVerySatisfied
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentVerySatisfied as RoundedSentimentVerySatisfied
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentVerySatisfied as SharpSentimentVerySatisfied
import io.github.hlcaptain.symbols.material.outlined.vectors.SentimentWorried as OutlinedSentimentWorried
import io.github.hlcaptain.symbols.material.rounded.vectors.SentimentWorried as RoundedSentimentWorried
import io.github.hlcaptain.symbols.material.sharp.vectors.SentimentWorried as SharpSentimentWorried
import io.github.hlcaptain.symbols.material.outlined.vectors.Serif as OutlinedSerif
import io.github.hlcaptain.symbols.material.rounded.vectors.Serif as RoundedSerif
import io.github.hlcaptain.symbols.material.sharp.vectors.Serif as SharpSerif
import io.github.hlcaptain.symbols.material.outlined.vectors.ServerPerson as OutlinedServerPerson
import io.github.hlcaptain.symbols.material.rounded.vectors.ServerPerson as RoundedServerPerson
import io.github.hlcaptain.symbols.material.sharp.vectors.ServerPerson as SharpServerPerson
import io.github.hlcaptain.symbols.material.outlined.vectors.ServiceToolbox as OutlinedServiceToolbox
import io.github.hlcaptain.symbols.material.rounded.vectors.ServiceToolbox as RoundedServiceToolbox
import io.github.hlcaptain.symbols.material.sharp.vectors.ServiceToolbox as SharpServiceToolbox
import io.github.hlcaptain.symbols.material.outlined.vectors.SetMeal as OutlinedSetMeal
import io.github.hlcaptain.symbols.material.rounded.vectors.SetMeal as RoundedSetMeal
import io.github.hlcaptain.symbols.material.sharp.vectors.SetMeal as SharpSetMeal
import io.github.hlcaptain.symbols.material.outlined.vectors.Settings as OutlinedSettings
import io.github.hlcaptain.symbols.material.rounded.vectors.Settings as RoundedSettings
import io.github.hlcaptain.symbols.material.sharp.vectors.Settings as SharpSettings
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsAccessibility as OutlinedSettingsAccessibility
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsAccessibility as RoundedSettingsAccessibility
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsAccessibility as SharpSettingsAccessibility
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsAccountBox as OutlinedSettingsAccountBox
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsAccountBox as RoundedSettingsAccountBox
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsAccountBox as SharpSettingsAccountBox
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsAlert as OutlinedSettingsAlert
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsAlert as RoundedSettingsAlert
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsAlert as SharpSettingsAlert
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsApplications as OutlinedSettingsApplications
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsApplications as RoundedSettingsApplications
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsApplications as SharpSettingsApplications
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsBRoll as OutlinedSettingsBRoll
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsBRoll as RoundedSettingsBRoll
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsBRoll as SharpSettingsBRoll
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsBackupRestore as OutlinedSettingsBackupRestore
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsBackupRestore as RoundedSettingsBackupRestore
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsBackupRestore as SharpSettingsBackupRestore
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsBluetooth as OutlinedSettingsBluetooth
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsBluetooth as RoundedSettingsBluetooth
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsBluetooth as SharpSettingsBluetooth
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsBrightness as OutlinedSettingsBrightness
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsBrightness as RoundedSettingsBrightness
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsBrightness as SharpSettingsBrightness
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsCell as OutlinedSettingsCell
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsCell as RoundedSettingsCell
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsCell as SharpSettingsCell
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsCinematicBlur as OutlinedSettingsCinematicBlur
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsCinematicBlur as RoundedSettingsCinematicBlur
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsCinematicBlur as SharpSettingsCinematicBlur
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsEthernet as OutlinedSettingsEthernet
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsEthernet as RoundedSettingsEthernet
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsEthernet as SharpSettingsEthernet
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsHeart as OutlinedSettingsHeart
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsHeart as RoundedSettingsHeart
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsHeart as SharpSettingsHeart
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsInputAntenna as OutlinedSettingsInputAntenna
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsInputAntenna as RoundedSettingsInputAntenna
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsInputAntenna as SharpSettingsInputAntenna
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsInputComponent as OutlinedSettingsInputComponent
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsInputComponent as RoundedSettingsInputComponent
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsInputComponent as SharpSettingsInputComponent
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsInputComposite as OutlinedSettingsInputComposite
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsInputComposite as RoundedSettingsInputComposite
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsInputComposite as SharpSettingsInputComposite
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsInputHdmi as OutlinedSettingsInputHdmi
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsInputHdmi as RoundedSettingsInputHdmi
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsInputHdmi as SharpSettingsInputHdmi
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsInputSvideo as OutlinedSettingsInputSvideo
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsInputSvideo as RoundedSettingsInputSvideo
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsInputSvideo as SharpSettingsInputSvideo
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsMotionMode as OutlinedSettingsMotionMode
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsMotionMode as RoundedSettingsMotionMode
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsMotionMode as SharpSettingsMotionMode
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsNightSight as OutlinedSettingsNightSight
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsNightSight as RoundedSettingsNightSight
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsNightSight as SharpSettingsNightSight
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsOverscan as OutlinedSettingsOverscan
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsOverscan as RoundedSettingsOverscan
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsOverscan as SharpSettingsOverscan
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsPanorama as OutlinedSettingsPanorama
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsPanorama as RoundedSettingsPanorama
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsPanorama as SharpSettingsPanorama
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsPhone as OutlinedSettingsPhone
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsPhone as RoundedSettingsPhone
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsPhone as SharpSettingsPhone
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsPhotoCamera as OutlinedSettingsPhotoCamera
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsPhotoCamera as RoundedSettingsPhotoCamera
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsPhotoCamera as SharpSettingsPhotoCamera
import io.github.hlcaptain.symbols.material.outlined.vectors.SettingsPower as OutlinedSettingsPower
import io.github.hlcaptain.symbols.material.rounded.vectors.SettingsPower as RoundedSettingsPower
import io.github.hlcaptain.symbols.material.sharp.vectors.SettingsPower as SharpSettingsPower

public val Icons.Themed.SelectAll: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelectAll
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelectAll
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelectAll
    }

public val Icons.Themed.SelectCheckBox: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelectCheckBox
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelectCheckBox
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelectCheckBox
    }

public val Icons.Themed.SelectToSpeak: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelectToSpeak
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelectToSpeak
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelectToSpeak
    }

public val Icons.Themed.SelectWindow: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelectWindow
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelectWindow
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelectWindow
    }

public val Icons.Themed.SelectWindow2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelectWindow2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelectWindow2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelectWindow2
    }

public val Icons.Themed.SelectWindowOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelectWindowOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelectWindowOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelectWindowOff
    }

public val Icons.Themed.SelfCare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelfCare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelfCare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelfCare
    }

public val Icons.Themed.SelfImprovement: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelfImprovement
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelfImprovement
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelfImprovement
    }

public val Icons.Themed.Sell: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSell
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSell
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSell
    }

public val Icons.Themed.Send: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSend
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSend
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSend
    }

public val Icons.Themed.SendAndArchive: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSendAndArchive
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSendAndArchive
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSendAndArchive
    }

public val Icons.Themed.SendMoney: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSendMoney
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSendMoney
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSendMoney
    }

public val Icons.Themed.SendTimeExtension: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSendTimeExtension
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSendTimeExtension
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSendTimeExtension
    }

public val Icons.Themed.SendToMobile: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSendToMobile
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSendToMobile
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSendToMobile
    }

public val Icons.Themed.SensorDoor: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensorDoor
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensorDoor
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensorDoor
    }

public val Icons.Themed.SensorOccupied: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensorOccupied
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensorOccupied
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensorOccupied
    }

public val Icons.Themed.SensorWindow: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensorWindow
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensorWindow
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensorWindow
    }

public val Icons.Themed.Sensors: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensors
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensors
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensors
    }

public val Icons.Themed.SensorsKrx: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensorsKrx
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensorsKrx
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensorsKrx
    }

public val Icons.Themed.SensorsKrxOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensorsKrxOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensorsKrxOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensorsKrxOff
    }

public val Icons.Themed.SensorsOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSensorsOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSensorsOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSensorsOff
    }

public val Icons.Themed.SentimentCalm: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentCalm
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentCalm
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentCalm
    }

public val Icons.Themed.SentimentContent: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentContent
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentContent
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentContent
    }

public val Icons.Themed.SentimentDissatisfied: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentDissatisfied
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentDissatisfied
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentDissatisfied
    }

public val Icons.Themed.SentimentExcited: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentExcited
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentExcited
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentExcited
    }

public val Icons.Themed.SentimentExtremelyDissatisfied: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentExtremelyDissatisfied
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentExtremelyDissatisfied
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentExtremelyDissatisfied
    }

public val Icons.Themed.SentimentFrustrated: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentFrustrated
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentFrustrated
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentFrustrated
    }

public val Icons.Themed.SentimentNeutral: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentNeutral
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentNeutral
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentNeutral
    }

public val Icons.Themed.SentimentSad: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentSad
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentSad
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentSad
    }

public val Icons.Themed.SentimentSatisfied: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentSatisfied
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentSatisfied
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentSatisfied
    }

public val Icons.Themed.SentimentSatisfiedAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentSatisfiedAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentSatisfiedAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentSatisfiedAlt
    }

public val Icons.Themed.SentimentStressed: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentStressed
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentStressed
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentStressed
    }

public val Icons.Themed.SentimentVeryDissatisfied: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentVeryDissatisfied
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentVeryDissatisfied
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentVeryDissatisfied
    }

public val Icons.Themed.SentimentVerySatisfied: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentVerySatisfied
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentVerySatisfied
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentVerySatisfied
    }

public val Icons.Themed.SentimentWorried: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSentimentWorried
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSentimentWorried
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSentimentWorried
    }

public val Icons.Themed.Serif: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSerif
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSerif
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSerif
    }

public val Icons.Themed.ServerPerson: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedServerPerson
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedServerPerson
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpServerPerson
    }

public val Icons.Themed.ServiceToolbox: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedServiceToolbox
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedServiceToolbox
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpServiceToolbox
    }

public val Icons.Themed.SetMeal: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSetMeal
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSetMeal
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSetMeal
    }

public val Icons.Themed.Settings: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettings
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettings
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettings
    }

public val Icons.Themed.SettingsAccessibility: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsAccessibility
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsAccessibility
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsAccessibility
    }

public val Icons.Themed.SettingsAccountBox: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsAccountBox
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsAccountBox
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsAccountBox
    }

public val Icons.Themed.SettingsAlert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsAlert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsAlert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsAlert
    }

public val Icons.Themed.SettingsApplications: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsApplications
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsApplications
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsApplications
    }

public val Icons.Themed.SettingsBRoll: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsBRoll
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsBRoll
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsBRoll
    }

public val Icons.Themed.SettingsBackupRestore: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsBackupRestore
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsBackupRestore
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsBackupRestore
    }

public val Icons.Themed.SettingsBluetooth: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsBluetooth
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsBluetooth
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsBluetooth
    }

public val Icons.Themed.SettingsBrightness: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsBrightness
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsBrightness
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsBrightness
    }

public val Icons.Themed.SettingsCell: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsCell
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsCell
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsCell
    }

public val Icons.Themed.SettingsCinematicBlur: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsCinematicBlur
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsCinematicBlur
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsCinematicBlur
    }

public val Icons.Themed.SettingsEthernet: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsEthernet
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsEthernet
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsEthernet
    }

public val Icons.Themed.SettingsHeart: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsHeart
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsHeart
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsHeart
    }

public val Icons.Themed.SettingsInputAntenna: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsInputAntenna
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsInputAntenna
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsInputAntenna
    }

public val Icons.Themed.SettingsInputComponent: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsInputComponent
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsInputComponent
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsInputComponent
    }

public val Icons.Themed.SettingsInputComposite: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsInputComposite
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsInputComposite
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsInputComposite
    }

public val Icons.Themed.SettingsInputHdmi: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsInputHdmi
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsInputHdmi
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsInputHdmi
    }

public val Icons.Themed.SettingsInputSvideo: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsInputSvideo
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsInputSvideo
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsInputSvideo
    }

public val Icons.Themed.SettingsMotionMode: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsMotionMode
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsMotionMode
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsMotionMode
    }

public val Icons.Themed.SettingsNightSight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsNightSight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsNightSight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsNightSight
    }

public val Icons.Themed.SettingsOverscan: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsOverscan
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsOverscan
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsOverscan
    }

public val Icons.Themed.SettingsPanorama: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsPanorama
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsPanorama
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsPanorama
    }

public val Icons.Themed.SettingsPhone: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsPhone
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsPhone
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsPhone
    }

public val Icons.Themed.SettingsPhotoCamera: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsPhotoCamera
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsPhotoCamera
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsPhotoCamera
    }

public val Icons.Themed.SettingsPower: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSettingsPower
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSettingsPower
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSettingsPower
    }
