// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme as SymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.UnfoldLessDouble as OutlinedUnfoldLessDouble
import io.github.hlcaptain.symbols.material.rounded.vectors.UnfoldLessDouble as RoundedUnfoldLessDouble
import io.github.hlcaptain.symbols.material.sharp.vectors.UnfoldLessDouble as SharpUnfoldLessDouble
import io.github.hlcaptain.symbols.material.outlined.vectors.UnfoldMore as OutlinedUnfoldMore
import io.github.hlcaptain.symbols.material.rounded.vectors.UnfoldMore as RoundedUnfoldMore
import io.github.hlcaptain.symbols.material.sharp.vectors.UnfoldMore as SharpUnfoldMore
import io.github.hlcaptain.symbols.material.outlined.vectors.UnfoldMoreDouble as OutlinedUnfoldMoreDouble
import io.github.hlcaptain.symbols.material.rounded.vectors.UnfoldMoreDouble as RoundedUnfoldMoreDouble
import io.github.hlcaptain.symbols.material.sharp.vectors.UnfoldMoreDouble as SharpUnfoldMoreDouble
import io.github.hlcaptain.symbols.material.outlined.vectors.Ungroup as OutlinedUngroup
import io.github.hlcaptain.symbols.material.rounded.vectors.Ungroup as RoundedUngroup
import io.github.hlcaptain.symbols.material.sharp.vectors.Ungroup as SharpUngroup
import io.github.hlcaptain.symbols.material.outlined.vectors.UniversalCurrency as OutlinedUniversalCurrency
import io.github.hlcaptain.symbols.material.rounded.vectors.UniversalCurrency as RoundedUniversalCurrency
import io.github.hlcaptain.symbols.material.sharp.vectors.UniversalCurrency as SharpUniversalCurrency
import io.github.hlcaptain.symbols.material.outlined.vectors.UniversalCurrencyAlt as OutlinedUniversalCurrencyAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.UniversalCurrencyAlt as RoundedUniversalCurrencyAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.UniversalCurrencyAlt as SharpUniversalCurrencyAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.UniversalLocal as OutlinedUniversalLocal
import io.github.hlcaptain.symbols.material.rounded.vectors.UniversalLocal as RoundedUniversalLocal
import io.github.hlcaptain.symbols.material.sharp.vectors.UniversalLocal as SharpUniversalLocal
import io.github.hlcaptain.symbols.material.outlined.vectors.Unknown2 as OutlinedUnknown2
import io.github.hlcaptain.symbols.material.rounded.vectors.Unknown2 as RoundedUnknown2
import io.github.hlcaptain.symbols.material.sharp.vectors.Unknown2 as SharpUnknown2
import io.github.hlcaptain.symbols.material.outlined.vectors.Unknown5 as OutlinedUnknown5
import io.github.hlcaptain.symbols.material.rounded.vectors.Unknown5 as RoundedUnknown5
import io.github.hlcaptain.symbols.material.sharp.vectors.Unknown5 as SharpUnknown5
import io.github.hlcaptain.symbols.material.outlined.vectors.Unknown7 as OutlinedUnknown7
import io.github.hlcaptain.symbols.material.rounded.vectors.Unknown7 as RoundedUnknown7
import io.github.hlcaptain.symbols.material.sharp.vectors.Unknown7 as SharpUnknown7
import io.github.hlcaptain.symbols.material.outlined.vectors.UnknownDocument as OutlinedUnknownDocument
import io.github.hlcaptain.symbols.material.rounded.vectors.UnknownDocument as RoundedUnknownDocument
import io.github.hlcaptain.symbols.material.sharp.vectors.UnknownDocument as SharpUnknownDocument
import io.github.hlcaptain.symbols.material.outlined.vectors.UnknownMed as OutlinedUnknownMed
import io.github.hlcaptain.symbols.material.rounded.vectors.UnknownMed as RoundedUnknownMed
import io.github.hlcaptain.symbols.material.sharp.vectors.UnknownMed as SharpUnknownMed
import io.github.hlcaptain.symbols.material.outlined.vectors.Unlicense as OutlinedUnlicense
import io.github.hlcaptain.symbols.material.rounded.vectors.Unlicense as RoundedUnlicense
import io.github.hlcaptain.symbols.material.sharp.vectors.Unlicense as SharpUnlicense
import io.github.hlcaptain.symbols.material.outlined.vectors.UnpavedRoad as OutlinedUnpavedRoad
import io.github.hlcaptain.symbols.material.rounded.vectors.UnpavedRoad as RoundedUnpavedRoad
import io.github.hlcaptain.symbols.material.sharp.vectors.UnpavedRoad as SharpUnpavedRoad
import io.github.hlcaptain.symbols.material.outlined.vectors.Unpin as OutlinedUnpin
import io.github.hlcaptain.symbols.material.rounded.vectors.Unpin as RoundedUnpin
import io.github.hlcaptain.symbols.material.sharp.vectors.Unpin as SharpUnpin
import io.github.hlcaptain.symbols.material.outlined.vectors.Unpublished as OutlinedUnpublished
import io.github.hlcaptain.symbols.material.rounded.vectors.Unpublished as RoundedUnpublished
import io.github.hlcaptain.symbols.material.sharp.vectors.Unpublished as SharpUnpublished
import io.github.hlcaptain.symbols.material.outlined.vectors.Unsubscribe as OutlinedUnsubscribe
import io.github.hlcaptain.symbols.material.rounded.vectors.Unsubscribe as RoundedUnsubscribe
import io.github.hlcaptain.symbols.material.sharp.vectors.Unsubscribe as SharpUnsubscribe
import io.github.hlcaptain.symbols.material.outlined.vectors.Upcoming as OutlinedUpcoming
import io.github.hlcaptain.symbols.material.rounded.vectors.Upcoming as RoundedUpcoming
import io.github.hlcaptain.symbols.material.sharp.vectors.Upcoming as SharpUpcoming
import io.github.hlcaptain.symbols.material.outlined.vectors.Update as OutlinedUpdate
import io.github.hlcaptain.symbols.material.rounded.vectors.Update as RoundedUpdate
import io.github.hlcaptain.symbols.material.sharp.vectors.Update as SharpUpdate
import io.github.hlcaptain.symbols.material.outlined.vectors.UpdateDisabled as OutlinedUpdateDisabled
import io.github.hlcaptain.symbols.material.rounded.vectors.UpdateDisabled as RoundedUpdateDisabled
import io.github.hlcaptain.symbols.material.sharp.vectors.UpdateDisabled as SharpUpdateDisabled
import io.github.hlcaptain.symbols.material.outlined.vectors.Upgrade as OutlinedUpgrade
import io.github.hlcaptain.symbols.material.rounded.vectors.Upgrade as RoundedUpgrade
import io.github.hlcaptain.symbols.material.sharp.vectors.Upgrade as SharpUpgrade
import io.github.hlcaptain.symbols.material.outlined.vectors.UpiPay as OutlinedUpiPay
import io.github.hlcaptain.symbols.material.rounded.vectors.UpiPay as RoundedUpiPay
import io.github.hlcaptain.symbols.material.sharp.vectors.UpiPay as SharpUpiPay
import io.github.hlcaptain.symbols.material.outlined.vectors.Upload as OutlinedUpload
import io.github.hlcaptain.symbols.material.rounded.vectors.Upload as RoundedUpload
import io.github.hlcaptain.symbols.material.sharp.vectors.Upload as SharpUpload
import io.github.hlcaptain.symbols.material.outlined.vectors.Upload2 as OutlinedUpload2
import io.github.hlcaptain.symbols.material.rounded.vectors.Upload2 as RoundedUpload2
import io.github.hlcaptain.symbols.material.sharp.vectors.Upload2 as SharpUpload2
import io.github.hlcaptain.symbols.material.outlined.vectors.UploadFile as OutlinedUploadFile
import io.github.hlcaptain.symbols.material.rounded.vectors.UploadFile as RoundedUploadFile
import io.github.hlcaptain.symbols.material.sharp.vectors.UploadFile as SharpUploadFile
import io.github.hlcaptain.symbols.material.outlined.vectors.Uppercase as OutlinedUppercase
import io.github.hlcaptain.symbols.material.rounded.vectors.Uppercase as RoundedUppercase
import io.github.hlcaptain.symbols.material.sharp.vectors.Uppercase as SharpUppercase
import io.github.hlcaptain.symbols.material.outlined.vectors.Urology as OutlinedUrology
import io.github.hlcaptain.symbols.material.rounded.vectors.Urology as RoundedUrology
import io.github.hlcaptain.symbols.material.sharp.vectors.Urology as SharpUrology
import io.github.hlcaptain.symbols.material.outlined.vectors.Usb as OutlinedUsb
import io.github.hlcaptain.symbols.material.rounded.vectors.Usb as RoundedUsb
import io.github.hlcaptain.symbols.material.sharp.vectors.Usb as SharpUsb
import io.github.hlcaptain.symbols.material.outlined.vectors.UsbOff as OutlinedUsbOff
import io.github.hlcaptain.symbols.material.rounded.vectors.UsbOff as RoundedUsbOff
import io.github.hlcaptain.symbols.material.sharp.vectors.UsbOff as SharpUsbOff
import io.github.hlcaptain.symbols.material.outlined.vectors.UserAttributes as OutlinedUserAttributes
import io.github.hlcaptain.symbols.material.rounded.vectors.UserAttributes as RoundedUserAttributes
import io.github.hlcaptain.symbols.material.sharp.vectors.UserAttributes as SharpUserAttributes
import io.github.hlcaptain.symbols.material.outlined.vectors.Vaccines as OutlinedVaccines
import io.github.hlcaptain.symbols.material.rounded.vectors.Vaccines as RoundedVaccines
import io.github.hlcaptain.symbols.material.sharp.vectors.Vaccines as SharpVaccines
import io.github.hlcaptain.symbols.material.outlined.vectors.Vacuum as OutlinedVacuum
import io.github.hlcaptain.symbols.material.rounded.vectors.Vacuum as RoundedVacuum
import io.github.hlcaptain.symbols.material.sharp.vectors.Vacuum as SharpVacuum
import io.github.hlcaptain.symbols.material.outlined.vectors.Valve as OutlinedValve
import io.github.hlcaptain.symbols.material.rounded.vectors.Valve as RoundedValve
import io.github.hlcaptain.symbols.material.sharp.vectors.Valve as SharpValve
import io.github.hlcaptain.symbols.material.outlined.vectors.VapeFree as OutlinedVapeFree
import io.github.hlcaptain.symbols.material.rounded.vectors.VapeFree as RoundedVapeFree
import io.github.hlcaptain.symbols.material.sharp.vectors.VapeFree as SharpVapeFree
import io.github.hlcaptain.symbols.material.outlined.vectors.VapingRooms as OutlinedVapingRooms
import io.github.hlcaptain.symbols.material.rounded.vectors.VapingRooms as RoundedVapingRooms
import io.github.hlcaptain.symbols.material.sharp.vectors.VapingRooms as SharpVapingRooms
import io.github.hlcaptain.symbols.material.outlined.vectors.VariableAdd as OutlinedVariableAdd
import io.github.hlcaptain.symbols.material.rounded.vectors.VariableAdd as RoundedVariableAdd
import io.github.hlcaptain.symbols.material.sharp.vectors.VariableAdd as SharpVariableAdd
import io.github.hlcaptain.symbols.material.outlined.vectors.VariableInsert as OutlinedVariableInsert
import io.github.hlcaptain.symbols.material.rounded.vectors.VariableInsert as RoundedVariableInsert
import io.github.hlcaptain.symbols.material.sharp.vectors.VariableInsert as SharpVariableInsert
import io.github.hlcaptain.symbols.material.outlined.vectors.VariableRemove as OutlinedVariableRemove
import io.github.hlcaptain.symbols.material.rounded.vectors.VariableRemove as RoundedVariableRemove
import io.github.hlcaptain.symbols.material.sharp.vectors.VariableRemove as SharpVariableRemove
import io.github.hlcaptain.symbols.material.outlined.vectors.Variables as OutlinedVariables
import io.github.hlcaptain.symbols.material.rounded.vectors.Variables as RoundedVariables
import io.github.hlcaptain.symbols.material.sharp.vectors.Variables as SharpVariables
import io.github.hlcaptain.symbols.material.outlined.vectors.Ventilator as OutlinedVentilator
import io.github.hlcaptain.symbols.material.rounded.vectors.Ventilator as RoundedVentilator
import io.github.hlcaptain.symbols.material.sharp.vectors.Ventilator as SharpVentilator
import io.github.hlcaptain.symbols.material.outlined.vectors.Verified as OutlinedVerified
import io.github.hlcaptain.symbols.material.rounded.vectors.Verified as RoundedVerified
import io.github.hlcaptain.symbols.material.sharp.vectors.Verified as SharpVerified
import io.github.hlcaptain.symbols.material.outlined.vectors.VerifiedOff as OutlinedVerifiedOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VerifiedOff as RoundedVerifiedOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VerifiedOff as SharpVerifiedOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VerifiedUser as OutlinedVerifiedUser
import io.github.hlcaptain.symbols.material.rounded.vectors.VerifiedUser as RoundedVerifiedUser
import io.github.hlcaptain.symbols.material.sharp.vectors.VerifiedUser as SharpVerifiedUser
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalAlignBottom as OutlinedVerticalAlignBottom
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalAlignBottom as RoundedVerticalAlignBottom
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalAlignBottom as SharpVerticalAlignBottom
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalAlignCenter as OutlinedVerticalAlignCenter
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalAlignCenter as RoundedVerticalAlignCenter
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalAlignCenter as SharpVerticalAlignCenter
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalAlignTop as OutlinedVerticalAlignTop
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalAlignTop as RoundedVerticalAlignTop
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalAlignTop as SharpVerticalAlignTop
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalDistribute as OutlinedVerticalDistribute
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalDistribute as RoundedVerticalDistribute
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalDistribute as SharpVerticalDistribute
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalShades as OutlinedVerticalShades
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalShades as RoundedVerticalShades
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalShades as SharpVerticalShades
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalShadesClosed as OutlinedVerticalShadesClosed
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalShadesClosed as RoundedVerticalShadesClosed
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalShadesClosed as SharpVerticalShadesClosed
import io.github.hlcaptain.symbols.material.outlined.vectors.VerticalSplit as OutlinedVerticalSplit
import io.github.hlcaptain.symbols.material.rounded.vectors.VerticalSplit as RoundedVerticalSplit
import io.github.hlcaptain.symbols.material.sharp.vectors.VerticalSplit as SharpVerticalSplit
import io.github.hlcaptain.symbols.material.outlined.vectors.Vibration as OutlinedVibration
import io.github.hlcaptain.symbols.material.rounded.vectors.Vibration as RoundedVibration
import io.github.hlcaptain.symbols.material.sharp.vectors.Vibration as SharpVibration
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoCall as OutlinedVideoCall
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoCall as RoundedVideoCall
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoCall as SharpVideoCall
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoCameraBack as OutlinedVideoCameraBack
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoCameraBack as RoundedVideoCameraBack
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoCameraBack as SharpVideoCameraBack
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoCameraBackAdd as OutlinedVideoCameraBackAdd
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoCameraBackAdd as RoundedVideoCameraBackAdd
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoCameraBackAdd as SharpVideoCameraBackAdd
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoCameraFront as OutlinedVideoCameraFront
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoCameraFront as RoundedVideoCameraFront
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoCameraFront as SharpVideoCameraFront
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoCameraFrontOff as OutlinedVideoCameraFrontOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoCameraFrontOff as RoundedVideoCameraFrontOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoCameraFrontOff as SharpVideoCameraFrontOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoChat as OutlinedVideoChat
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoChat as RoundedVideoChat
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoChat as SharpVideoChat
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoFile as OutlinedVideoFile
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoFile as RoundedVideoFile
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoFile as SharpVideoFile
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoLabel as OutlinedVideoLabel
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoLabel as RoundedVideoLabel
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoLabel as SharpVideoLabel
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoLibrary as OutlinedVideoLibrary
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoLibrary as RoundedVideoLibrary
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoLibrary as SharpVideoLibrary
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoSearch as OutlinedVideoSearch
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoSearch as RoundedVideoSearch
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoSearch as SharpVideoSearch
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoSettings as OutlinedVideoSettings
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoSettings as RoundedVideoSettings
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoSettings as SharpVideoSettings
import io.github.hlcaptain.symbols.material.outlined.vectors.VideoStable as OutlinedVideoStable
import io.github.hlcaptain.symbols.material.rounded.vectors.VideoStable as RoundedVideoStable
import io.github.hlcaptain.symbols.material.sharp.vectors.VideoStable as SharpVideoStable
import io.github.hlcaptain.symbols.material.outlined.vectors.Videocam as OutlinedVideocam
import io.github.hlcaptain.symbols.material.rounded.vectors.Videocam as RoundedVideocam
import io.github.hlcaptain.symbols.material.sharp.vectors.Videocam as SharpVideocam

public val Icons.Themed.UnfoldLessDouble: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnfoldLessDouble
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnfoldLessDouble
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnfoldLessDouble
    }

public val Icons.Themed.UnfoldMore: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnfoldMore
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnfoldMore
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnfoldMore
    }

public val Icons.Themed.UnfoldMoreDouble: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnfoldMoreDouble
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnfoldMoreDouble
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnfoldMoreDouble
    }

public val Icons.Themed.Ungroup: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUngroup
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUngroup
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUngroup
    }

public val Icons.Themed.UniversalCurrency: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUniversalCurrency
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUniversalCurrency
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUniversalCurrency
    }

public val Icons.Themed.UniversalCurrencyAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUniversalCurrencyAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUniversalCurrencyAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUniversalCurrencyAlt
    }

public val Icons.Themed.UniversalLocal: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUniversalLocal
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUniversalLocal
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUniversalLocal
    }

public val Icons.Themed.Unknown2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnknown2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnknown2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnknown2
    }

public val Icons.Themed.Unknown5: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnknown5
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnknown5
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnknown5
    }

public val Icons.Themed.Unknown7: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnknown7
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnknown7
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnknown7
    }

public val Icons.Themed.UnknownDocument: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnknownDocument
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnknownDocument
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnknownDocument
    }

public val Icons.Themed.UnknownMed: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnknownMed
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnknownMed
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnknownMed
    }

public val Icons.Themed.Unlicense: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnlicense
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnlicense
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnlicense
    }

public val Icons.Themed.UnpavedRoad: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnpavedRoad
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnpavedRoad
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnpavedRoad
    }

public val Icons.Themed.Unpin: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnpin
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnpin
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnpin
    }

public val Icons.Themed.Unpublished: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnpublished
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnpublished
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnpublished
    }

public val Icons.Themed.Unsubscribe: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUnsubscribe
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUnsubscribe
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUnsubscribe
    }

public val Icons.Themed.Upcoming: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpcoming
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpcoming
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpcoming
    }

public val Icons.Themed.Update: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpdate
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpdate
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpdate
    }

public val Icons.Themed.UpdateDisabled: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpdateDisabled
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpdateDisabled
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpdateDisabled
    }

public val Icons.Themed.Upgrade: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpgrade
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpgrade
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpgrade
    }

public val Icons.Themed.UpiPay: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpiPay
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpiPay
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpiPay
    }

public val Icons.Themed.Upload: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpload
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpload
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpload
    }

public val Icons.Themed.Upload2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUpload2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUpload2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUpload2
    }

public val Icons.Themed.UploadFile: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUploadFile
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUploadFile
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUploadFile
    }

public val Icons.Themed.Uppercase: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUppercase
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUppercase
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUppercase
    }

public val Icons.Themed.Urology: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUrology
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUrology
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUrology
    }

public val Icons.Themed.Usb: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUsb
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUsb
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUsb
    }

public val Icons.Themed.UsbOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUsbOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUsbOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUsbOff
    }

public val Icons.Themed.UserAttributes: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedUserAttributes
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedUserAttributes
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpUserAttributes
    }

public val Icons.Themed.Vaccines: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVaccines
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVaccines
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVaccines
    }

public val Icons.Themed.Vacuum: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVacuum
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVacuum
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVacuum
    }

public val Icons.Themed.Valve: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedValve
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedValve
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpValve
    }

public val Icons.Themed.VapeFree: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVapeFree
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVapeFree
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVapeFree
    }

public val Icons.Themed.VapingRooms: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVapingRooms
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVapingRooms
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVapingRooms
    }

public val Icons.Themed.VariableAdd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVariableAdd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVariableAdd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVariableAdd
    }

public val Icons.Themed.VariableInsert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVariableInsert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVariableInsert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVariableInsert
    }

public val Icons.Themed.VariableRemove: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVariableRemove
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVariableRemove
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVariableRemove
    }

public val Icons.Themed.Variables: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVariables
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVariables
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVariables
    }

public val Icons.Themed.Ventilator: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVentilator
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVentilator
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVentilator
    }

public val Icons.Themed.Verified: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerified
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerified
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerified
    }

public val Icons.Themed.VerifiedOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerifiedOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerifiedOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerifiedOff
    }

public val Icons.Themed.VerifiedUser: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerifiedUser
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerifiedUser
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerifiedUser
    }

public val Icons.Themed.VerticalAlignBottom: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalAlignBottom
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalAlignBottom
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalAlignBottom
    }

public val Icons.Themed.VerticalAlignCenter: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalAlignCenter
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalAlignCenter
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalAlignCenter
    }

public val Icons.Themed.VerticalAlignTop: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalAlignTop
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalAlignTop
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalAlignTop
    }

public val Icons.Themed.VerticalDistribute: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalDistribute
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalDistribute
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalDistribute
    }

public val Icons.Themed.VerticalShades: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalShades
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalShades
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalShades
    }

public val Icons.Themed.VerticalShadesClosed: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalShadesClosed
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalShadesClosed
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalShadesClosed
    }

public val Icons.Themed.VerticalSplit: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVerticalSplit
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVerticalSplit
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVerticalSplit
    }

public val Icons.Themed.Vibration: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVibration
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVibration
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVibration
    }

public val Icons.Themed.VideoCall: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoCall
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoCall
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoCall
    }

public val Icons.Themed.VideoCameraBack: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoCameraBack
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoCameraBack
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoCameraBack
    }

public val Icons.Themed.VideoCameraBackAdd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoCameraBackAdd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoCameraBackAdd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoCameraBackAdd
    }

public val Icons.Themed.VideoCameraFront: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoCameraFront
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoCameraFront
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoCameraFront
    }

public val Icons.Themed.VideoCameraFrontOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoCameraFrontOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoCameraFrontOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoCameraFrontOff
    }

public val Icons.Themed.VideoChat: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoChat
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoChat
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoChat
    }

public val Icons.Themed.VideoFile: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoFile
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoFile
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoFile
    }

public val Icons.Themed.VideoLabel: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoLabel
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoLabel
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoLabel
    }

public val Icons.Themed.VideoLibrary: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoLibrary
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoLibrary
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoLibrary
    }

public val Icons.Themed.VideoSearch: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoSearch
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoSearch
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoSearch
    }

public val Icons.Themed.VideoSettings: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoSettings
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoSettings
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoSettings
    }

public val Icons.Themed.VideoStable: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideoStable
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideoStable
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideoStable
    }

public val Icons.Themed.Videocam: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideocam
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideocam
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideocam
    }
