// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.TextIncrease as OutlinedTextIncrease
import io.github.hlcaptain.symbols.material.rounded.vectors.TextIncrease as RoundedTextIncrease
import io.github.hlcaptain.symbols.material.sharp.vectors.TextIncrease as SharpTextIncrease
import io.github.hlcaptain.symbols.material.outlined.vectors.TextRotateUp as OutlinedTextRotateUp
import io.github.hlcaptain.symbols.material.rounded.vectors.TextRotateUp as RoundedTextRotateUp
import io.github.hlcaptain.symbols.material.sharp.vectors.TextRotateUp as SharpTextRotateUp
import io.github.hlcaptain.symbols.material.outlined.vectors.TextRotateVertical as OutlinedTextRotateVertical
import io.github.hlcaptain.symbols.material.rounded.vectors.TextRotateVertical as RoundedTextRotateVertical
import io.github.hlcaptain.symbols.material.sharp.vectors.TextRotateVertical as SharpTextRotateVertical
import io.github.hlcaptain.symbols.material.outlined.vectors.TextRotationAngledown as OutlinedTextRotationAngledown
import io.github.hlcaptain.symbols.material.rounded.vectors.TextRotationAngledown as RoundedTextRotationAngledown
import io.github.hlcaptain.symbols.material.sharp.vectors.TextRotationAngledown as SharpTextRotationAngledown
import io.github.hlcaptain.symbols.material.outlined.vectors.TextRotationAngleup as OutlinedTextRotationAngleup
import io.github.hlcaptain.symbols.material.rounded.vectors.TextRotationAngleup as RoundedTextRotationAngleup
import io.github.hlcaptain.symbols.material.sharp.vectors.TextRotationAngleup as SharpTextRotationAngleup
import io.github.hlcaptain.symbols.material.outlined.vectors.TextRotationDown as OutlinedTextRotationDown
import io.github.hlcaptain.symbols.material.rounded.vectors.TextRotationDown as RoundedTextRotationDown
import io.github.hlcaptain.symbols.material.sharp.vectors.TextRotationDown as SharpTextRotationDown
import io.github.hlcaptain.symbols.material.outlined.vectors.TextRotationNone as OutlinedTextRotationNone
import io.github.hlcaptain.symbols.material.rounded.vectors.TextRotationNone as RoundedTextRotationNone
import io.github.hlcaptain.symbols.material.sharp.vectors.TextRotationNone as SharpTextRotationNone
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectEnd as OutlinedTextSelectEnd
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectEnd as RoundedTextSelectEnd
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectEnd as SharpTextSelectEnd
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectJumpToBeginning as OutlinedTextSelectJumpToBeginning
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectJumpToBeginning as RoundedTextSelectJumpToBeginning
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectJumpToBeginning as SharpTextSelectJumpToBeginning
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectJumpToEnd as OutlinedTextSelectJumpToEnd
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectJumpToEnd as RoundedTextSelectJumpToEnd
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectJumpToEnd as SharpTextSelectJumpToEnd
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectMoveBackCharacter as OutlinedTextSelectMoveBackCharacter
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectMoveBackCharacter as RoundedTextSelectMoveBackCharacter
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectMoveBackCharacter as SharpTextSelectMoveBackCharacter
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectMoveBackWord as OutlinedTextSelectMoveBackWord
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectMoveBackWord as RoundedTextSelectMoveBackWord
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectMoveBackWord as SharpTextSelectMoveBackWord
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectMoveDown as OutlinedTextSelectMoveDown
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectMoveDown as RoundedTextSelectMoveDown
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectMoveDown as SharpTextSelectMoveDown
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectMoveForwardCharacter as OutlinedTextSelectMoveForwardCharacter
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectMoveForwardCharacter as RoundedTextSelectMoveForwardCharacter
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectMoveForwardCharacter as SharpTextSelectMoveForwardCharacter
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectMoveForwardWord as OutlinedTextSelectMoveForwardWord
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectMoveForwardWord as RoundedTextSelectMoveForwardWord
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectMoveForwardWord as SharpTextSelectMoveForwardWord
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectMoveUp as OutlinedTextSelectMoveUp
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectMoveUp as RoundedTextSelectMoveUp
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectMoveUp as SharpTextSelectMoveUp
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSelectStart as OutlinedTextSelectStart
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSelectStart as RoundedTextSelectStart
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSelectStart as SharpTextSelectStart
import io.github.hlcaptain.symbols.material.outlined.vectors.TextSnippet as OutlinedTextSnippet
import io.github.hlcaptain.symbols.material.rounded.vectors.TextSnippet as RoundedTextSnippet
import io.github.hlcaptain.symbols.material.sharp.vectors.TextSnippet as SharpTextSnippet
import io.github.hlcaptain.symbols.material.outlined.vectors.TextToSpeech as OutlinedTextToSpeech
import io.github.hlcaptain.symbols.material.rounded.vectors.TextToSpeech as RoundedTextToSpeech
import io.github.hlcaptain.symbols.material.sharp.vectors.TextToSpeech as SharpTextToSpeech
import io.github.hlcaptain.symbols.material.outlined.vectors.TextUp as OutlinedTextUp
import io.github.hlcaptain.symbols.material.rounded.vectors.TextUp as RoundedTextUp
import io.github.hlcaptain.symbols.material.sharp.vectors.TextUp as SharpTextUp
import io.github.hlcaptain.symbols.material.outlined.vectors.Textsms as OutlinedTextsms
import io.github.hlcaptain.symbols.material.rounded.vectors.Textsms as RoundedTextsms
import io.github.hlcaptain.symbols.material.sharp.vectors.Textsms as SharpTextsms
import io.github.hlcaptain.symbols.material.outlined.vectors.Texture as OutlinedTexture
import io.github.hlcaptain.symbols.material.rounded.vectors.Texture as RoundedTexture
import io.github.hlcaptain.symbols.material.sharp.vectors.Texture as SharpTexture
import io.github.hlcaptain.symbols.material.outlined.vectors.TextureAdd as OutlinedTextureAdd
import io.github.hlcaptain.symbols.material.rounded.vectors.TextureAdd as RoundedTextureAdd
import io.github.hlcaptain.symbols.material.sharp.vectors.TextureAdd as SharpTextureAdd
import io.github.hlcaptain.symbols.material.outlined.vectors.TextureMinus as OutlinedTextureMinus
import io.github.hlcaptain.symbols.material.rounded.vectors.TextureMinus as RoundedTextureMinus
import io.github.hlcaptain.symbols.material.sharp.vectors.TextureMinus as SharpTextureMinus
import io.github.hlcaptain.symbols.material.outlined.vectors.TheaterComedy as OutlinedTheaterComedy
import io.github.hlcaptain.symbols.material.rounded.vectors.TheaterComedy as RoundedTheaterComedy
import io.github.hlcaptain.symbols.material.sharp.vectors.TheaterComedy as SharpTheaterComedy
import io.github.hlcaptain.symbols.material.outlined.vectors.Theaters as OutlinedTheaters
import io.github.hlcaptain.symbols.material.rounded.vectors.Theaters as RoundedTheaters
import io.github.hlcaptain.symbols.material.sharp.vectors.Theaters as SharpTheaters
import io.github.hlcaptain.symbols.material.outlined.vectors.Thermometer as OutlinedThermometer
import io.github.hlcaptain.symbols.material.rounded.vectors.Thermometer as RoundedThermometer
import io.github.hlcaptain.symbols.material.sharp.vectors.Thermometer as SharpThermometer
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermometerAdd as OutlinedThermometerAdd
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermometerAdd as RoundedThermometerAdd
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermometerAdd as SharpThermometerAdd
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermometerGain as OutlinedThermometerGain
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermometerGain as RoundedThermometerGain
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermometerGain as SharpThermometerGain
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermometerLoss as OutlinedThermometerLoss
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermometerLoss as RoundedThermometerLoss
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermometerLoss as SharpThermometerLoss
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermometerMinus as OutlinedThermometerMinus
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermometerMinus as RoundedThermometerMinus
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermometerMinus as SharpThermometerMinus
import io.github.hlcaptain.symbols.material.outlined.vectors.Thermostat as OutlinedThermostat
import io.github.hlcaptain.symbols.material.rounded.vectors.Thermostat as RoundedThermostat
import io.github.hlcaptain.symbols.material.sharp.vectors.Thermostat as SharpThermostat
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermostatArrowDown as OutlinedThermostatArrowDown
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermostatArrowDown as RoundedThermostatArrowDown
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermostatArrowDown as SharpThermostatArrowDown
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermostatArrowUp as OutlinedThermostatArrowUp
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermostatArrowUp as RoundedThermostatArrowUp
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermostatArrowUp as SharpThermostatArrowUp
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermostatAuto as OutlinedThermostatAuto
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermostatAuto as RoundedThermostatAuto
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermostatAuto as SharpThermostatAuto
import io.github.hlcaptain.symbols.material.outlined.vectors.ThermostatCarbon as OutlinedThermostatCarbon
import io.github.hlcaptain.symbols.material.rounded.vectors.ThermostatCarbon as RoundedThermostatCarbon
import io.github.hlcaptain.symbols.material.sharp.vectors.ThermostatCarbon as SharpThermostatCarbon
import io.github.hlcaptain.symbols.material.outlined.vectors.ThingsToDo as OutlinedThingsToDo
import io.github.hlcaptain.symbols.material.rounded.vectors.ThingsToDo as RoundedThingsToDo
import io.github.hlcaptain.symbols.material.sharp.vectors.ThingsToDo as SharpThingsToDo
import io.github.hlcaptain.symbols.material.outlined.vectors.ThreadUnread as OutlinedThreadUnread
import io.github.hlcaptain.symbols.material.rounded.vectors.ThreadUnread as RoundedThreadUnread
import io.github.hlcaptain.symbols.material.sharp.vectors.ThreadUnread as SharpThreadUnread
import io.github.hlcaptain.symbols.material.outlined.vectors.ThreatIntelligence as OutlinedThreatIntelligence
import io.github.hlcaptain.symbols.material.rounded.vectors.ThreatIntelligence as RoundedThreatIntelligence
import io.github.hlcaptain.symbols.material.sharp.vectors.ThreatIntelligence as SharpThreatIntelligence
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbDown as OutlinedThumbDown
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbDown as RoundedThumbDown
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbDown as SharpThumbDown
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbDownAlt as OutlinedThumbDownAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbDownAlt as RoundedThumbDownAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbDownAlt as SharpThumbDownAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbDownFilled as OutlinedThumbDownFilled
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbDownFilled as RoundedThumbDownFilled
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbDownFilled as SharpThumbDownFilled
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbDownOff as OutlinedThumbDownOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbDownOff as RoundedThumbDownOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbDownOff as SharpThumbDownOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbDownOffAlt as OutlinedThumbDownOffAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbDownOffAlt as RoundedThumbDownOffAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbDownOffAlt as SharpThumbDownOffAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbUp as OutlinedThumbUp
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbUp as RoundedThumbUp
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbUp as SharpThumbUp
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbUpAlt as OutlinedThumbUpAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbUpAlt as RoundedThumbUpAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbUpAlt as SharpThumbUpAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbUpFilled as OutlinedThumbUpFilled
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbUpFilled as RoundedThumbUpFilled
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbUpFilled as SharpThumbUpFilled
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbUpOff as OutlinedThumbUpOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbUpOff as RoundedThumbUpOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbUpOff as SharpThumbUpOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbUpOffAlt as OutlinedThumbUpOffAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbUpOffAlt as RoundedThumbUpOffAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbUpOffAlt as SharpThumbUpOffAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbnailBar as OutlinedThumbnailBar
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbnailBar as RoundedThumbnailBar
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbnailBar as SharpThumbnailBar
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbsUpDouble as OutlinedThumbsUpDouble
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbsUpDouble as RoundedThumbsUpDouble
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbsUpDouble as SharpThumbsUpDouble
import io.github.hlcaptain.symbols.material.outlined.vectors.ThumbsUpDown as OutlinedThumbsUpDown
import io.github.hlcaptain.symbols.material.rounded.vectors.ThumbsUpDown as RoundedThumbsUpDown
import io.github.hlcaptain.symbols.material.sharp.vectors.ThumbsUpDown as SharpThumbsUpDown
import io.github.hlcaptain.symbols.material.outlined.vectors.Thunderstorm as OutlinedThunderstorm
import io.github.hlcaptain.symbols.material.rounded.vectors.Thunderstorm as RoundedThunderstorm
import io.github.hlcaptain.symbols.material.sharp.vectors.Thunderstorm as SharpThunderstorm
import io.github.hlcaptain.symbols.material.outlined.vectors.Tibia as OutlinedTibia
import io.github.hlcaptain.symbols.material.rounded.vectors.Tibia as RoundedTibia
import io.github.hlcaptain.symbols.material.sharp.vectors.Tibia as SharpTibia
import io.github.hlcaptain.symbols.material.outlined.vectors.TibiaAlt as OutlinedTibiaAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.TibiaAlt as RoundedTibiaAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.TibiaAlt as SharpTibiaAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.TileLarge as OutlinedTileLarge
import io.github.hlcaptain.symbols.material.rounded.vectors.TileLarge as RoundedTileLarge
import io.github.hlcaptain.symbols.material.sharp.vectors.TileLarge as SharpTileLarge
import io.github.hlcaptain.symbols.material.outlined.vectors.TileMedium as OutlinedTileMedium
import io.github.hlcaptain.symbols.material.rounded.vectors.TileMedium as RoundedTileMedium
import io.github.hlcaptain.symbols.material.sharp.vectors.TileMedium as SharpTileMedium
import io.github.hlcaptain.symbols.material.outlined.vectors.TileSmall as OutlinedTileSmall
import io.github.hlcaptain.symbols.material.rounded.vectors.TileSmall as RoundedTileSmall
import io.github.hlcaptain.symbols.material.sharp.vectors.TileSmall as SharpTileSmall
import io.github.hlcaptain.symbols.material.outlined.vectors.TimeAuto as OutlinedTimeAuto
import io.github.hlcaptain.symbols.material.rounded.vectors.TimeAuto as RoundedTimeAuto
import io.github.hlcaptain.symbols.material.sharp.vectors.TimeAuto as SharpTimeAuto
import io.github.hlcaptain.symbols.material.outlined.vectors.TimeToLeave as OutlinedTimeToLeave
import io.github.hlcaptain.symbols.material.rounded.vectors.TimeToLeave as RoundedTimeToLeave
import io.github.hlcaptain.symbols.material.sharp.vectors.TimeToLeave as SharpTimeToLeave
import io.github.hlcaptain.symbols.material.outlined.vectors.Timelapse as OutlinedTimelapse
import io.github.hlcaptain.symbols.material.rounded.vectors.Timelapse as RoundedTimelapse
import io.github.hlcaptain.symbols.material.sharp.vectors.Timelapse as SharpTimelapse
import io.github.hlcaptain.symbols.material.outlined.vectors.Timeline as OutlinedTimeline
import io.github.hlcaptain.symbols.material.rounded.vectors.Timeline as RoundedTimeline
import io.github.hlcaptain.symbols.material.sharp.vectors.Timeline as SharpTimeline
import io.github.hlcaptain.symbols.material.outlined.vectors.Timer as OutlinedTimer
import io.github.hlcaptain.symbols.material.rounded.vectors.Timer as RoundedTimer
import io.github.hlcaptain.symbols.material.sharp.vectors.Timer as SharpTimer
import io.github.hlcaptain.symbols.material.outlined.vectors.Timer1 as OutlinedTimer1
import io.github.hlcaptain.symbols.material.rounded.vectors.Timer1 as RoundedTimer1
import io.github.hlcaptain.symbols.material.sharp.vectors.Timer1 as SharpTimer1

public val Icons.Themed.TextIncrease: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextIncrease
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextIncrease
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextIncrease
    }

public val Icons.Themed.TextRotateUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextRotateUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextRotateUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextRotateUp
    }

public val Icons.Themed.TextRotateVertical: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextRotateVertical
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextRotateVertical
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextRotateVertical
    }

public val Icons.Themed.TextRotationAngledown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextRotationAngledown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextRotationAngledown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextRotationAngledown
    }

public val Icons.Themed.TextRotationAngleup: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextRotationAngleup
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextRotationAngleup
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextRotationAngleup
    }

public val Icons.Themed.TextRotationDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextRotationDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextRotationDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextRotationDown
    }

public val Icons.Themed.TextRotationNone: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextRotationNone
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextRotationNone
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextRotationNone
    }

public val Icons.Themed.TextSelectEnd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectEnd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectEnd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectEnd
    }

public val Icons.Themed.TextSelectJumpToBeginning: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectJumpToBeginning
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectJumpToBeginning
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectJumpToBeginning
    }

public val Icons.Themed.TextSelectJumpToEnd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectJumpToEnd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectJumpToEnd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectJumpToEnd
    }

public val Icons.Themed.TextSelectMoveBackCharacter: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectMoveBackCharacter
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectMoveBackCharacter
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectMoveBackCharacter
    }

public val Icons.Themed.TextSelectMoveBackWord: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectMoveBackWord
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectMoveBackWord
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectMoveBackWord
    }

public val Icons.Themed.TextSelectMoveDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectMoveDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectMoveDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectMoveDown
    }

public val Icons.Themed.TextSelectMoveForwardCharacter: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectMoveForwardCharacter
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectMoveForwardCharacter
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectMoveForwardCharacter
    }

public val Icons.Themed.TextSelectMoveForwardWord: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectMoveForwardWord
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectMoveForwardWord
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectMoveForwardWord
    }

public val Icons.Themed.TextSelectMoveUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectMoveUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectMoveUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectMoveUp
    }

public val Icons.Themed.TextSelectStart: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSelectStart
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSelectStart
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSelectStart
    }

public val Icons.Themed.TextSnippet: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextSnippet
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextSnippet
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextSnippet
    }

public val Icons.Themed.TextToSpeech: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextToSpeech
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextToSpeech
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextToSpeech
    }

public val Icons.Themed.TextUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextUp
    }

public val Icons.Themed.Textsms: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextsms
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextsms
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextsms
    }

public val Icons.Themed.Texture: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTexture
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTexture
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTexture
    }

public val Icons.Themed.TextureAdd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextureAdd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextureAdd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextureAdd
    }

public val Icons.Themed.TextureMinus: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTextureMinus
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTextureMinus
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTextureMinus
    }

public val Icons.Themed.TheaterComedy: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTheaterComedy
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTheaterComedy
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTheaterComedy
    }

public val Icons.Themed.Theaters: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTheaters
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTheaters
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTheaters
    }

public val Icons.Themed.Thermometer: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermometer
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermometer
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermometer
    }

public val Icons.Themed.ThermometerAdd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermometerAdd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermometerAdd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermometerAdd
    }

public val Icons.Themed.ThermometerGain: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermometerGain
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermometerGain
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermometerGain
    }

public val Icons.Themed.ThermometerLoss: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermometerLoss
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermometerLoss
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermometerLoss
    }

public val Icons.Themed.ThermometerMinus: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermometerMinus
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermometerMinus
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermometerMinus
    }

public val Icons.Themed.Thermostat: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermostat
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermostat
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermostat
    }

public val Icons.Themed.ThermostatArrowDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermostatArrowDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermostatArrowDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermostatArrowDown
    }

public val Icons.Themed.ThermostatArrowUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermostatArrowUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermostatArrowUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermostatArrowUp
    }

public val Icons.Themed.ThermostatAuto: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermostatAuto
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermostatAuto
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermostatAuto
    }

public val Icons.Themed.ThermostatCarbon: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThermostatCarbon
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThermostatCarbon
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThermostatCarbon
    }

public val Icons.Themed.ThingsToDo: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThingsToDo
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThingsToDo
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThingsToDo
    }

public val Icons.Themed.ThreadUnread: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThreadUnread
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThreadUnread
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThreadUnread
    }

public val Icons.Themed.ThreatIntelligence: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThreatIntelligence
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThreatIntelligence
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThreatIntelligence
    }

public val Icons.Themed.ThumbDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbDown
    }

public val Icons.Themed.ThumbDownAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbDownAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbDownAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbDownAlt
    }

public val Icons.Themed.ThumbDownFilled: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbDownFilled
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbDownFilled
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbDownFilled
    }

public val Icons.Themed.ThumbDownOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbDownOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbDownOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbDownOff
    }

public val Icons.Themed.ThumbDownOffAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbDownOffAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbDownOffAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbDownOffAlt
    }

public val Icons.Themed.ThumbUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbUp
    }

public val Icons.Themed.ThumbUpAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbUpAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbUpAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbUpAlt
    }

public val Icons.Themed.ThumbUpFilled: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbUpFilled
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbUpFilled
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbUpFilled
    }

public val Icons.Themed.ThumbUpOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbUpOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbUpOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbUpOff
    }

public val Icons.Themed.ThumbUpOffAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbUpOffAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbUpOffAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbUpOffAlt
    }

public val Icons.Themed.ThumbnailBar: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbnailBar
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbnailBar
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbnailBar
    }

public val Icons.Themed.ThumbsUpDouble: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbsUpDouble
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbsUpDouble
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbsUpDouble
    }

public val Icons.Themed.ThumbsUpDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThumbsUpDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThumbsUpDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThumbsUpDown
    }

public val Icons.Themed.Thunderstorm: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedThunderstorm
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedThunderstorm
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpThunderstorm
    }

public val Icons.Themed.Tibia: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTibia
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTibia
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTibia
    }

public val Icons.Themed.TibiaAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTibiaAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTibiaAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTibiaAlt
    }

public val Icons.Themed.TileLarge: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTileLarge
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTileLarge
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTileLarge
    }

public val Icons.Themed.TileMedium: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTileMedium
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTileMedium
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTileMedium
    }

public val Icons.Themed.TileSmall: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTileSmall
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTileSmall
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTileSmall
    }

public val Icons.Themed.TimeAuto: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTimeAuto
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTimeAuto
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTimeAuto
    }

public val Icons.Themed.TimeToLeave: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTimeToLeave
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTimeToLeave
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTimeToLeave
    }

public val Icons.Themed.Timelapse: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTimelapse
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTimelapse
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTimelapse
    }

public val Icons.Themed.Timeline: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTimeline
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTimeline
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTimeline
    }

public val Icons.Themed.Timer: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTimer
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTimer
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTimer
    }

public val Icons.Themed.Timer1: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedTimer1
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedTimer1
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpTimer1
    }
