// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme as SymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.SaveAs as OutlinedSaveAs
import io.github.hlcaptain.symbols.material.rounded.vectors.SaveAs as RoundedSaveAs
import io.github.hlcaptain.symbols.material.sharp.vectors.SaveAs as SharpSaveAs
import io.github.hlcaptain.symbols.material.outlined.vectors.SaveClock as OutlinedSaveClock
import io.github.hlcaptain.symbols.material.rounded.vectors.SaveClock as RoundedSaveClock
import io.github.hlcaptain.symbols.material.sharp.vectors.SaveClock as SharpSaveClock
import io.github.hlcaptain.symbols.material.outlined.vectors.SavedSearch as OutlinedSavedSearch
import io.github.hlcaptain.symbols.material.rounded.vectors.SavedSearch as RoundedSavedSearch
import io.github.hlcaptain.symbols.material.sharp.vectors.SavedSearch as SharpSavedSearch
import io.github.hlcaptain.symbols.material.outlined.vectors.Savings as OutlinedSavings
import io.github.hlcaptain.symbols.material.rounded.vectors.Savings as RoundedSavings
import io.github.hlcaptain.symbols.material.sharp.vectors.Savings as SharpSavings
import io.github.hlcaptain.symbols.material.outlined.vectors.Scale as OutlinedScale
import io.github.hlcaptain.symbols.material.rounded.vectors.Scale as RoundedScale
import io.github.hlcaptain.symbols.material.sharp.vectors.Scale as SharpScale
import io.github.hlcaptain.symbols.material.outlined.vectors.Scan as OutlinedScan
import io.github.hlcaptain.symbols.material.rounded.vectors.Scan as RoundedScan
import io.github.hlcaptain.symbols.material.sharp.vectors.Scan as SharpScan
import io.github.hlcaptain.symbols.material.outlined.vectors.ScanDelete as OutlinedScanDelete
import io.github.hlcaptain.symbols.material.rounded.vectors.ScanDelete as RoundedScanDelete
import io.github.hlcaptain.symbols.material.sharp.vectors.ScanDelete as SharpScanDelete
import io.github.hlcaptain.symbols.material.outlined.vectors.Scanner as OutlinedScanner
import io.github.hlcaptain.symbols.material.rounded.vectors.Scanner as RoundedScanner
import io.github.hlcaptain.symbols.material.sharp.vectors.Scanner as SharpScanner
import io.github.hlcaptain.symbols.material.outlined.vectors.ScatterPlot as OutlinedScatterPlot
import io.github.hlcaptain.symbols.material.rounded.vectors.ScatterPlot as RoundedScatterPlot
import io.github.hlcaptain.symbols.material.sharp.vectors.ScatterPlot as SharpScatterPlot
import io.github.hlcaptain.symbols.material.outlined.vectors.Scene as OutlinedScene
import io.github.hlcaptain.symbols.material.rounded.vectors.Scene as RoundedScene
import io.github.hlcaptain.symbols.material.sharp.vectors.Scene as SharpScene
import io.github.hlcaptain.symbols.material.outlined.vectors.Schedule as OutlinedSchedule
import io.github.hlcaptain.symbols.material.rounded.vectors.Schedule as RoundedSchedule
import io.github.hlcaptain.symbols.material.sharp.vectors.Schedule as SharpSchedule
import io.github.hlcaptain.symbols.material.outlined.vectors.ScheduleSend as OutlinedScheduleSend
import io.github.hlcaptain.symbols.material.rounded.vectors.ScheduleSend as RoundedScheduleSend
import io.github.hlcaptain.symbols.material.sharp.vectors.ScheduleSend as SharpScheduleSend
import io.github.hlcaptain.symbols.material.outlined.vectors.Schema as OutlinedSchema
import io.github.hlcaptain.symbols.material.rounded.vectors.Schema as RoundedSchema
import io.github.hlcaptain.symbols.material.sharp.vectors.Schema as SharpSchema
import io.github.hlcaptain.symbols.material.outlined.vectors.School as OutlinedSchool
import io.github.hlcaptain.symbols.material.rounded.vectors.School as RoundedSchool
import io.github.hlcaptain.symbols.material.sharp.vectors.School as SharpSchool
import io.github.hlcaptain.symbols.material.outlined.vectors.Science as OutlinedScience
import io.github.hlcaptain.symbols.material.rounded.vectors.Science as RoundedScience
import io.github.hlcaptain.symbols.material.sharp.vectors.Science as SharpScience
import io.github.hlcaptain.symbols.material.outlined.vectors.ScienceOff as OutlinedScienceOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ScienceOff as RoundedScienceOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ScienceOff as SharpScienceOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Scooter as OutlinedScooter
import io.github.hlcaptain.symbols.material.rounded.vectors.Scooter as RoundedScooter
import io.github.hlcaptain.symbols.material.sharp.vectors.Scooter as SharpScooter
import io.github.hlcaptain.symbols.material.outlined.vectors.Score as OutlinedScore
import io.github.hlcaptain.symbols.material.rounded.vectors.Score as RoundedScore
import io.github.hlcaptain.symbols.material.sharp.vectors.Score as SharpScore
import io.github.hlcaptain.symbols.material.outlined.vectors.Scoreboard as OutlinedScoreboard
import io.github.hlcaptain.symbols.material.rounded.vectors.Scoreboard as RoundedScoreboard
import io.github.hlcaptain.symbols.material.sharp.vectors.Scoreboard as SharpScoreboard
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenLockLandscape as OutlinedScreenLockLandscape
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenLockLandscape as RoundedScreenLockLandscape
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenLockLandscape as SharpScreenLockLandscape
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenLockPortrait as OutlinedScreenLockPortrait
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenLockPortrait as RoundedScreenLockPortrait
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenLockPortrait as SharpScreenLockPortrait
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenLockRotation as OutlinedScreenLockRotation
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenLockRotation as RoundedScreenLockRotation
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenLockRotation as SharpScreenLockRotation
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenRecord as OutlinedScreenRecord
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenRecord as RoundedScreenRecord
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenRecord as SharpScreenRecord
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenRotation as OutlinedScreenRotation
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenRotation as RoundedScreenRotation
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenRotation as SharpScreenRotation
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenRotationAlt as OutlinedScreenRotationAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenRotationAlt as RoundedScreenRotationAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenRotationAlt as SharpScreenRotationAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenRotationUp as OutlinedScreenRotationUp
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenRotationUp as RoundedScreenRotationUp
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenRotationUp as SharpScreenRotationUp
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenSearchDesktop as OutlinedScreenSearchDesktop
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenSearchDesktop as RoundedScreenSearchDesktop
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenSearchDesktop as SharpScreenSearchDesktop
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenShare as OutlinedScreenShare
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenShare as RoundedScreenShare
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenShare as SharpScreenShare
import io.github.hlcaptain.symbols.material.outlined.vectors.Screenshot as OutlinedScreenshot
import io.github.hlcaptain.symbols.material.rounded.vectors.Screenshot as RoundedScreenshot
import io.github.hlcaptain.symbols.material.sharp.vectors.Screenshot as SharpScreenshot
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenshotFrame as OutlinedScreenshotFrame
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenshotFrame as RoundedScreenshotFrame
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenshotFrame as SharpScreenshotFrame
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenshotFrame2 as OutlinedScreenshotFrame2
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenshotFrame2 as RoundedScreenshotFrame2
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenshotFrame2 as SharpScreenshotFrame2
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenshotKeyboard as OutlinedScreenshotKeyboard
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenshotKeyboard as RoundedScreenshotKeyboard
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenshotKeyboard as SharpScreenshotKeyboard
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenshotMonitor as OutlinedScreenshotMonitor
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenshotMonitor as RoundedScreenshotMonitor
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenshotMonitor as SharpScreenshotMonitor
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenshotRegion as OutlinedScreenshotRegion
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenshotRegion as RoundedScreenshotRegion
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenshotRegion as SharpScreenshotRegion
import io.github.hlcaptain.symbols.material.outlined.vectors.ScreenshotTablet as OutlinedScreenshotTablet
import io.github.hlcaptain.symbols.material.rounded.vectors.ScreenshotTablet as RoundedScreenshotTablet
import io.github.hlcaptain.symbols.material.sharp.vectors.ScreenshotTablet as SharpScreenshotTablet
import io.github.hlcaptain.symbols.material.outlined.vectors.Script as OutlinedScript
import io.github.hlcaptain.symbols.material.rounded.vectors.Script as RoundedScript
import io.github.hlcaptain.symbols.material.sharp.vectors.Script as SharpScript
import io.github.hlcaptain.symbols.material.outlined.vectors.ScrollableHeader as OutlinedScrollableHeader
import io.github.hlcaptain.symbols.material.rounded.vectors.ScrollableHeader as RoundedScrollableHeader
import io.github.hlcaptain.symbols.material.sharp.vectors.ScrollableHeader as SharpScrollableHeader
import io.github.hlcaptain.symbols.material.outlined.vectors.ScubaDiving as OutlinedScubaDiving
import io.github.hlcaptain.symbols.material.rounded.vectors.ScubaDiving as RoundedScubaDiving
import io.github.hlcaptain.symbols.material.sharp.vectors.ScubaDiving as SharpScubaDiving
import io.github.hlcaptain.symbols.material.outlined.vectors.Sd as OutlinedSd
import io.github.hlcaptain.symbols.material.rounded.vectors.Sd as RoundedSd
import io.github.hlcaptain.symbols.material.sharp.vectors.Sd as SharpSd
import io.github.hlcaptain.symbols.material.outlined.vectors.SdCard as OutlinedSdCard
import io.github.hlcaptain.symbols.material.rounded.vectors.SdCard as RoundedSdCard
import io.github.hlcaptain.symbols.material.sharp.vectors.SdCard as SharpSdCard
import io.github.hlcaptain.symbols.material.outlined.vectors.SdCardAlert as OutlinedSdCardAlert
import io.github.hlcaptain.symbols.material.rounded.vectors.SdCardAlert as RoundedSdCardAlert
import io.github.hlcaptain.symbols.material.sharp.vectors.SdCardAlert as SharpSdCardAlert
import io.github.hlcaptain.symbols.material.outlined.vectors.SdStorage as OutlinedSdStorage
import io.github.hlcaptain.symbols.material.rounded.vectors.SdStorage as RoundedSdStorage
import io.github.hlcaptain.symbols.material.sharp.vectors.SdStorage as SharpSdStorage
import io.github.hlcaptain.symbols.material.outlined.vectors.Sdk as OutlinedSdk
import io.github.hlcaptain.symbols.material.rounded.vectors.Sdk as RoundedSdk
import io.github.hlcaptain.symbols.material.sharp.vectors.Sdk as SharpSdk
import io.github.hlcaptain.symbols.material.outlined.vectors.Search as OutlinedSearch
import io.github.hlcaptain.symbols.material.rounded.vectors.Search as RoundedSearch
import io.github.hlcaptain.symbols.material.sharp.vectors.Search as SharpSearch
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchActivity as OutlinedSearchActivity
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchActivity as RoundedSearchActivity
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchActivity as SharpSearchActivity
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchCheck as OutlinedSearchCheck
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchCheck as RoundedSearchCheck
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchCheck as SharpSearchCheck
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchCheck2 as OutlinedSearchCheck2
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchCheck2 as RoundedSearchCheck2
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchCheck2 as SharpSearchCheck2
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchGear as OutlinedSearchGear
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchGear as RoundedSearchGear
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchGear as SharpSearchGear
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchHandsFree as OutlinedSearchHandsFree
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchHandsFree as RoundedSearchHandsFree
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchHandsFree as SharpSearchHandsFree
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchInsights as OutlinedSearchInsights
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchInsights as RoundedSearchInsights
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchInsights as SharpSearchInsights
import io.github.hlcaptain.symbols.material.outlined.vectors.SearchOff as OutlinedSearchOff
import io.github.hlcaptain.symbols.material.rounded.vectors.SearchOff as RoundedSearchOff
import io.github.hlcaptain.symbols.material.sharp.vectors.SearchOff as SharpSearchOff
import io.github.hlcaptain.symbols.material.outlined.vectors.SeatCoolLeft as OutlinedSeatCoolLeft
import io.github.hlcaptain.symbols.material.rounded.vectors.SeatCoolLeft as RoundedSeatCoolLeft
import io.github.hlcaptain.symbols.material.sharp.vectors.SeatCoolLeft as SharpSeatCoolLeft
import io.github.hlcaptain.symbols.material.outlined.vectors.SeatCoolRight as OutlinedSeatCoolRight
import io.github.hlcaptain.symbols.material.rounded.vectors.SeatCoolRight as RoundedSeatCoolRight
import io.github.hlcaptain.symbols.material.sharp.vectors.SeatCoolRight as SharpSeatCoolRight
import io.github.hlcaptain.symbols.material.outlined.vectors.SeatHeatLeft as OutlinedSeatHeatLeft
import io.github.hlcaptain.symbols.material.rounded.vectors.SeatHeatLeft as RoundedSeatHeatLeft
import io.github.hlcaptain.symbols.material.sharp.vectors.SeatHeatLeft as SharpSeatHeatLeft
import io.github.hlcaptain.symbols.material.outlined.vectors.SeatHeatRight as OutlinedSeatHeatRight
import io.github.hlcaptain.symbols.material.rounded.vectors.SeatHeatRight as RoundedSeatHeatRight
import io.github.hlcaptain.symbols.material.sharp.vectors.SeatHeatRight as SharpSeatHeatRight
import io.github.hlcaptain.symbols.material.outlined.vectors.SeatVentLeft as OutlinedSeatVentLeft
import io.github.hlcaptain.symbols.material.rounded.vectors.SeatVentLeft as RoundedSeatVentLeft
import io.github.hlcaptain.symbols.material.sharp.vectors.SeatVentLeft as SharpSeatVentLeft
import io.github.hlcaptain.symbols.material.outlined.vectors.SeatVentRight as OutlinedSeatVentRight
import io.github.hlcaptain.symbols.material.rounded.vectors.SeatVentRight as RoundedSeatVentRight
import io.github.hlcaptain.symbols.material.sharp.vectors.SeatVentRight as SharpSeatVentRight
import io.github.hlcaptain.symbols.material.outlined.vectors.Security as OutlinedSecurity
import io.github.hlcaptain.symbols.material.rounded.vectors.Security as RoundedSecurity
import io.github.hlcaptain.symbols.material.sharp.vectors.Security as SharpSecurity
import io.github.hlcaptain.symbols.material.outlined.vectors.SecurityKey as OutlinedSecurityKey
import io.github.hlcaptain.symbols.material.rounded.vectors.SecurityKey as RoundedSecurityKey
import io.github.hlcaptain.symbols.material.sharp.vectors.SecurityKey as SharpSecurityKey
import io.github.hlcaptain.symbols.material.outlined.vectors.SecurityUpdate as OutlinedSecurityUpdate
import io.github.hlcaptain.symbols.material.rounded.vectors.SecurityUpdate as RoundedSecurityUpdate
import io.github.hlcaptain.symbols.material.sharp.vectors.SecurityUpdate as SharpSecurityUpdate
import io.github.hlcaptain.symbols.material.outlined.vectors.SecurityUpdateGood as OutlinedSecurityUpdateGood
import io.github.hlcaptain.symbols.material.rounded.vectors.SecurityUpdateGood as RoundedSecurityUpdateGood
import io.github.hlcaptain.symbols.material.sharp.vectors.SecurityUpdateGood as SharpSecurityUpdateGood
import io.github.hlcaptain.symbols.material.outlined.vectors.SecurityUpdateWarning as OutlinedSecurityUpdateWarning
import io.github.hlcaptain.symbols.material.rounded.vectors.SecurityUpdateWarning as RoundedSecurityUpdateWarning
import io.github.hlcaptain.symbols.material.sharp.vectors.SecurityUpdateWarning as SharpSecurityUpdateWarning
import io.github.hlcaptain.symbols.material.outlined.vectors.Segment as OutlinedSegment
import io.github.hlcaptain.symbols.material.rounded.vectors.Segment as RoundedSegment
import io.github.hlcaptain.symbols.material.sharp.vectors.Segment as SharpSegment
import io.github.hlcaptain.symbols.material.outlined.vectors.Select as OutlinedSelect
import io.github.hlcaptain.symbols.material.rounded.vectors.Select as RoundedSelect
import io.github.hlcaptain.symbols.material.sharp.vectors.Select as SharpSelect

val Icons.Themed.SaveAs: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSaveAs
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSaveAs
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSaveAs
    }

val Icons.Themed.SaveClock: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSaveClock
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSaveClock
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSaveClock
    }

val Icons.Themed.SavedSearch: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSavedSearch
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSavedSearch
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSavedSearch
    }

val Icons.Themed.Savings: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSavings
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSavings
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSavings
    }

val Icons.Themed.Scale: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScale
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScale
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScale
    }

val Icons.Themed.Scan: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScan
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScan
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScan
    }

val Icons.Themed.ScanDelete: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScanDelete
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScanDelete
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScanDelete
    }

val Icons.Themed.Scanner: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScanner
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScanner
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScanner
    }

val Icons.Themed.ScatterPlot: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScatterPlot
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScatterPlot
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScatterPlot
    }

val Icons.Themed.Scene: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScene
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScene
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScene
    }

val Icons.Themed.Schedule: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSchedule
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSchedule
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSchedule
    }

val Icons.Themed.ScheduleSend: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScheduleSend
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScheduleSend
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScheduleSend
    }

val Icons.Themed.Schema: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSchema
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSchema
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSchema
    }

val Icons.Themed.School: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSchool
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSchool
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSchool
    }

val Icons.Themed.Science: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScience
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScience
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScience
    }

val Icons.Themed.ScienceOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScienceOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScienceOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScienceOff
    }

val Icons.Themed.Scooter: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScooter
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScooter
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScooter
    }

val Icons.Themed.Score: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScore
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScore
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScore
    }

val Icons.Themed.Scoreboard: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScoreboard
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScoreboard
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScoreboard
    }

val Icons.Themed.ScreenLockLandscape: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenLockLandscape
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenLockLandscape
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenLockLandscape
    }

val Icons.Themed.ScreenLockPortrait: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenLockPortrait
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenLockPortrait
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenLockPortrait
    }

val Icons.Themed.ScreenLockRotation: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenLockRotation
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenLockRotation
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenLockRotation
    }

val Icons.Themed.ScreenRecord: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenRecord
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenRecord
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenRecord
    }

val Icons.Themed.ScreenRotation: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenRotation
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenRotation
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenRotation
    }

val Icons.Themed.ScreenRotationAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenRotationAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenRotationAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenRotationAlt
    }

val Icons.Themed.ScreenRotationUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenRotationUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenRotationUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenRotationUp
    }

val Icons.Themed.ScreenSearchDesktop: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenSearchDesktop
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenSearchDesktop
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenSearchDesktop
    }

val Icons.Themed.ScreenShare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenShare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenShare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenShare
    }

val Icons.Themed.Screenshot: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshot
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshot
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshot
    }

val Icons.Themed.ScreenshotFrame: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshotFrame
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshotFrame
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshotFrame
    }

val Icons.Themed.ScreenshotFrame2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshotFrame2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshotFrame2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshotFrame2
    }

val Icons.Themed.ScreenshotKeyboard: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshotKeyboard
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshotKeyboard
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshotKeyboard
    }

val Icons.Themed.ScreenshotMonitor: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshotMonitor
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshotMonitor
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshotMonitor
    }

val Icons.Themed.ScreenshotRegion: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshotRegion
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshotRegion
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshotRegion
    }

val Icons.Themed.ScreenshotTablet: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScreenshotTablet
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScreenshotTablet
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScreenshotTablet
    }

val Icons.Themed.Script: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScript
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScript
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScript
    }

val Icons.Themed.ScrollableHeader: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScrollableHeader
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScrollableHeader
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScrollableHeader
    }

val Icons.Themed.ScubaDiving: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedScubaDiving
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedScubaDiving
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpScubaDiving
    }

val Icons.Themed.Sd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSd
    }

val Icons.Themed.SdCard: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSdCard
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSdCard
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSdCard
    }

val Icons.Themed.SdCardAlert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSdCardAlert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSdCardAlert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSdCardAlert
    }

val Icons.Themed.SdStorage: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSdStorage
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSdStorage
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSdStorage
    }

val Icons.Themed.Sdk: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSdk
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSdk
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSdk
    }

val Icons.Themed.Search: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearch
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearch
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearch
    }

val Icons.Themed.SearchActivity: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchActivity
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchActivity
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchActivity
    }

val Icons.Themed.SearchCheck: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchCheck
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchCheck
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchCheck
    }

val Icons.Themed.SearchCheck2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchCheck2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchCheck2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchCheck2
    }

val Icons.Themed.SearchGear: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchGear
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchGear
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchGear
    }

val Icons.Themed.SearchHandsFree: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchHandsFree
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchHandsFree
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchHandsFree
    }

val Icons.Themed.SearchInsights: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchInsights
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchInsights
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchInsights
    }

val Icons.Themed.SearchOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSearchOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSearchOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSearchOff
    }

val Icons.Themed.SeatCoolLeft: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSeatCoolLeft
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSeatCoolLeft
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSeatCoolLeft
    }

val Icons.Themed.SeatCoolRight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSeatCoolRight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSeatCoolRight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSeatCoolRight
    }

val Icons.Themed.SeatHeatLeft: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSeatHeatLeft
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSeatHeatLeft
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSeatHeatLeft
    }

val Icons.Themed.SeatHeatRight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSeatHeatRight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSeatHeatRight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSeatHeatRight
    }

val Icons.Themed.SeatVentLeft: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSeatVentLeft
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSeatVentLeft
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSeatVentLeft
    }

val Icons.Themed.SeatVentRight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSeatVentRight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSeatVentRight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSeatVentRight
    }

val Icons.Themed.Security: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSecurity
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSecurity
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSecurity
    }

val Icons.Themed.SecurityKey: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSecurityKey
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSecurityKey
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSecurityKey
    }

val Icons.Themed.SecurityUpdate: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSecurityUpdate
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSecurityUpdate
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSecurityUpdate
    }

val Icons.Themed.SecurityUpdateGood: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSecurityUpdateGood
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSecurityUpdateGood
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSecurityUpdateGood
    }

val Icons.Themed.SecurityUpdateWarning: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSecurityUpdateWarning
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSecurityUpdateWarning
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSecurityUpdateWarning
    }

val Icons.Themed.Segment: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSegment
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSegment
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSegment
    }

val Icons.Themed.Select: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedSelect
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedSelect
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpSelect
    }
