// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme as SymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.FileJson as OutlinedFileJson
import io.github.hlcaptain.symbols.material.rounded.vectors.FileJson as RoundedFileJson
import io.github.hlcaptain.symbols.material.sharp.vectors.FileJson as SharpFileJson
import io.github.hlcaptain.symbols.material.outlined.vectors.FileMap as OutlinedFileMap
import io.github.hlcaptain.symbols.material.rounded.vectors.FileMap as RoundedFileMap
import io.github.hlcaptain.symbols.material.sharp.vectors.FileMap as SharpFileMap
import io.github.hlcaptain.symbols.material.outlined.vectors.FileMapStack as OutlinedFileMapStack
import io.github.hlcaptain.symbols.material.rounded.vectors.FileMapStack as RoundedFileMapStack
import io.github.hlcaptain.symbols.material.sharp.vectors.FileMapStack as SharpFileMapStack
import io.github.hlcaptain.symbols.material.outlined.vectors.FileOpen as OutlinedFileOpen
import io.github.hlcaptain.symbols.material.rounded.vectors.FileOpen as RoundedFileOpen
import io.github.hlcaptain.symbols.material.sharp.vectors.FileOpen as SharpFileOpen
import io.github.hlcaptain.symbols.material.outlined.vectors.FilePng as OutlinedFilePng
import io.github.hlcaptain.symbols.material.rounded.vectors.FilePng as RoundedFilePng
import io.github.hlcaptain.symbols.material.sharp.vectors.FilePng as SharpFilePng
import io.github.hlcaptain.symbols.material.outlined.vectors.FilePresent as OutlinedFilePresent
import io.github.hlcaptain.symbols.material.rounded.vectors.FilePresent as RoundedFilePresent
import io.github.hlcaptain.symbols.material.sharp.vectors.FilePresent as SharpFilePresent
import io.github.hlcaptain.symbols.material.outlined.vectors.FileSave as OutlinedFileSave
import io.github.hlcaptain.symbols.material.rounded.vectors.FileSave as RoundedFileSave
import io.github.hlcaptain.symbols.material.sharp.vectors.FileSave as SharpFileSave
import io.github.hlcaptain.symbols.material.outlined.vectors.FileSaveOff as OutlinedFileSaveOff
import io.github.hlcaptain.symbols.material.rounded.vectors.FileSaveOff as RoundedFileSaveOff
import io.github.hlcaptain.symbols.material.sharp.vectors.FileSaveOff as SharpFileSaveOff
import io.github.hlcaptain.symbols.material.outlined.vectors.FileUpload as OutlinedFileUpload
import io.github.hlcaptain.symbols.material.rounded.vectors.FileUpload as RoundedFileUpload
import io.github.hlcaptain.symbols.material.sharp.vectors.FileUpload as SharpFileUpload
import io.github.hlcaptain.symbols.material.outlined.vectors.FileUploadOff as OutlinedFileUploadOff
import io.github.hlcaptain.symbols.material.rounded.vectors.FileUploadOff as RoundedFileUploadOff
import io.github.hlcaptain.symbols.material.sharp.vectors.FileUploadOff as SharpFileUploadOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Files as OutlinedFiles
import io.github.hlcaptain.symbols.material.rounded.vectors.Files as RoundedFiles
import io.github.hlcaptain.symbols.material.sharp.vectors.Files as SharpFiles
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter as OutlinedFilter
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter as RoundedFilter
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter as SharpFilter
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter1 as OutlinedFilter1
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter1 as RoundedFilter1
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter1 as SharpFilter1
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter2 as OutlinedFilter2
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter2 as RoundedFilter2
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter2 as SharpFilter2
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter3 as OutlinedFilter3
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter3 as RoundedFilter3
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter3 as SharpFilter3
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter4 as OutlinedFilter4
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter4 as RoundedFilter4
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter4 as SharpFilter4
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter5 as OutlinedFilter5
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter5 as RoundedFilter5
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter5 as SharpFilter5
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter6 as OutlinedFilter6
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter6 as RoundedFilter6
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter6 as SharpFilter6
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter7 as OutlinedFilter7
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter7 as RoundedFilter7
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter7 as SharpFilter7
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter8 as OutlinedFilter8
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter8 as RoundedFilter8
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter8 as SharpFilter8
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter9 as OutlinedFilter9
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter9 as RoundedFilter9
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter9 as SharpFilter9
import io.github.hlcaptain.symbols.material.outlined.vectors.Filter9Plus as OutlinedFilter9Plus
import io.github.hlcaptain.symbols.material.rounded.vectors.Filter9Plus as RoundedFilter9Plus
import io.github.hlcaptain.symbols.material.sharp.vectors.Filter9Plus as SharpFilter9Plus
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterAlt as OutlinedFilterAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterAlt as RoundedFilterAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterAlt as SharpFilterAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterAltOff as OutlinedFilterAltOff
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterAltOff as RoundedFilterAltOff
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterAltOff as SharpFilterAltOff
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterArrowRight as OutlinedFilterArrowRight
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterArrowRight as RoundedFilterArrowRight
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterArrowRight as SharpFilterArrowRight
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterBAndW as OutlinedFilterBAndW
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterBAndW as RoundedFilterBAndW
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterBAndW as SharpFilterBAndW
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterCenterFocus as OutlinedFilterCenterFocus
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterCenterFocus as RoundedFilterCenterFocus
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterCenterFocus as SharpFilterCenterFocus
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterDrama as OutlinedFilterDrama
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterDrama as RoundedFilterDrama
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterDrama as SharpFilterDrama
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterFrames as OutlinedFilterFrames
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterFrames as RoundedFilterFrames
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterFrames as SharpFilterFrames
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterHdr as OutlinedFilterHdr
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterHdr as RoundedFilterHdr
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterHdr as SharpFilterHdr
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterList as OutlinedFilterList
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterList as RoundedFilterList
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterList as SharpFilterList
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterListAlt as OutlinedFilterListAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterListAlt as RoundedFilterListAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterListAlt as SharpFilterListAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterListOff as OutlinedFilterListOff
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterListOff as RoundedFilterListOff
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterListOff as SharpFilterListOff
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterNone as OutlinedFilterNone
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterNone as RoundedFilterNone
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterNone as SharpFilterNone
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterRetrolux as OutlinedFilterRetrolux
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterRetrolux as RoundedFilterRetrolux
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterRetrolux as SharpFilterRetrolux
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterTiltShift as OutlinedFilterTiltShift
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterTiltShift as RoundedFilterTiltShift
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterTiltShift as SharpFilterTiltShift
import io.github.hlcaptain.symbols.material.outlined.vectors.FilterVintage as OutlinedFilterVintage
import io.github.hlcaptain.symbols.material.rounded.vectors.FilterVintage as RoundedFilterVintage
import io.github.hlcaptain.symbols.material.sharp.vectors.FilterVintage as SharpFilterVintage
import io.github.hlcaptain.symbols.material.outlined.vectors.Finance as OutlinedFinance
import io.github.hlcaptain.symbols.material.rounded.vectors.Finance as RoundedFinance
import io.github.hlcaptain.symbols.material.sharp.vectors.Finance as SharpFinance
import io.github.hlcaptain.symbols.material.outlined.vectors.FinanceChip as OutlinedFinanceChip
import io.github.hlcaptain.symbols.material.rounded.vectors.FinanceChip as RoundedFinanceChip
import io.github.hlcaptain.symbols.material.sharp.vectors.FinanceChip as SharpFinanceChip
import io.github.hlcaptain.symbols.material.outlined.vectors.FinanceMode as OutlinedFinanceMode
import io.github.hlcaptain.symbols.material.rounded.vectors.FinanceMode as RoundedFinanceMode
import io.github.hlcaptain.symbols.material.sharp.vectors.FinanceMode as SharpFinanceMode
import io.github.hlcaptain.symbols.material.outlined.vectors.FindInPage as OutlinedFindInPage
import io.github.hlcaptain.symbols.material.rounded.vectors.FindInPage as RoundedFindInPage
import io.github.hlcaptain.symbols.material.sharp.vectors.FindInPage as SharpFindInPage
import io.github.hlcaptain.symbols.material.outlined.vectors.FindReplace as OutlinedFindReplace
import io.github.hlcaptain.symbols.material.rounded.vectors.FindReplace as RoundedFindReplace
import io.github.hlcaptain.symbols.material.sharp.vectors.FindReplace as SharpFindReplace
import io.github.hlcaptain.symbols.material.outlined.vectors.Fingerprint as OutlinedFingerprint
import io.github.hlcaptain.symbols.material.rounded.vectors.Fingerprint as RoundedFingerprint
import io.github.hlcaptain.symbols.material.sharp.vectors.Fingerprint as SharpFingerprint
import io.github.hlcaptain.symbols.material.outlined.vectors.FingerprintOff as OutlinedFingerprintOff
import io.github.hlcaptain.symbols.material.rounded.vectors.FingerprintOff as RoundedFingerprintOff
import io.github.hlcaptain.symbols.material.sharp.vectors.FingerprintOff as SharpFingerprintOff
import io.github.hlcaptain.symbols.material.outlined.vectors.FireExtinguisher as OutlinedFireExtinguisher
import io.github.hlcaptain.symbols.material.rounded.vectors.FireExtinguisher as RoundedFireExtinguisher
import io.github.hlcaptain.symbols.material.sharp.vectors.FireExtinguisher as SharpFireExtinguisher
import io.github.hlcaptain.symbols.material.outlined.vectors.FireHydrant as OutlinedFireHydrant
import io.github.hlcaptain.symbols.material.rounded.vectors.FireHydrant as RoundedFireHydrant
import io.github.hlcaptain.symbols.material.sharp.vectors.FireHydrant as SharpFireHydrant
import io.github.hlcaptain.symbols.material.outlined.vectors.FireTruck as OutlinedFireTruck
import io.github.hlcaptain.symbols.material.rounded.vectors.FireTruck as RoundedFireTruck
import io.github.hlcaptain.symbols.material.sharp.vectors.FireTruck as SharpFireTruck
import io.github.hlcaptain.symbols.material.outlined.vectors.Fireplace as OutlinedFireplace
import io.github.hlcaptain.symbols.material.rounded.vectors.Fireplace as RoundedFireplace
import io.github.hlcaptain.symbols.material.sharp.vectors.Fireplace as SharpFireplace
import io.github.hlcaptain.symbols.material.outlined.vectors.FirstPage as OutlinedFirstPage
import io.github.hlcaptain.symbols.material.rounded.vectors.FirstPage as RoundedFirstPage
import io.github.hlcaptain.symbols.material.sharp.vectors.FirstPage as SharpFirstPage
import io.github.hlcaptain.symbols.material.outlined.vectors.FitPage as OutlinedFitPage
import io.github.hlcaptain.symbols.material.rounded.vectors.FitPage as RoundedFitPage
import io.github.hlcaptain.symbols.material.sharp.vectors.FitPage as SharpFitPage
import io.github.hlcaptain.symbols.material.outlined.vectors.FitPageHeight as OutlinedFitPageHeight
import io.github.hlcaptain.symbols.material.rounded.vectors.FitPageHeight as RoundedFitPageHeight
import io.github.hlcaptain.symbols.material.sharp.vectors.FitPageHeight as SharpFitPageHeight
import io.github.hlcaptain.symbols.material.outlined.vectors.FitPageWidth as OutlinedFitPageWidth
import io.github.hlcaptain.symbols.material.rounded.vectors.FitPageWidth as RoundedFitPageWidth
import io.github.hlcaptain.symbols.material.sharp.vectors.FitPageWidth as SharpFitPageWidth
import io.github.hlcaptain.symbols.material.outlined.vectors.FitScreen as OutlinedFitScreen
import io.github.hlcaptain.symbols.material.rounded.vectors.FitScreen as RoundedFitScreen
import io.github.hlcaptain.symbols.material.sharp.vectors.FitScreen as SharpFitScreen
import io.github.hlcaptain.symbols.material.outlined.vectors.FitWidth as OutlinedFitWidth
import io.github.hlcaptain.symbols.material.rounded.vectors.FitWidth as RoundedFitWidth
import io.github.hlcaptain.symbols.material.sharp.vectors.FitWidth as SharpFitWidth
import io.github.hlcaptain.symbols.material.outlined.vectors.FitnessCenter as OutlinedFitnessCenter
import io.github.hlcaptain.symbols.material.rounded.vectors.FitnessCenter as RoundedFitnessCenter
import io.github.hlcaptain.symbols.material.sharp.vectors.FitnessCenter as SharpFitnessCenter
import io.github.hlcaptain.symbols.material.outlined.vectors.FitnessTracker as OutlinedFitnessTracker
import io.github.hlcaptain.symbols.material.rounded.vectors.FitnessTracker as RoundedFitnessTracker
import io.github.hlcaptain.symbols.material.sharp.vectors.FitnessTracker as SharpFitnessTracker
import io.github.hlcaptain.symbols.material.outlined.vectors.FitnessTrackers as OutlinedFitnessTrackers
import io.github.hlcaptain.symbols.material.rounded.vectors.FitnessTrackers as RoundedFitnessTrackers
import io.github.hlcaptain.symbols.material.sharp.vectors.FitnessTrackers as SharpFitnessTrackers
import io.github.hlcaptain.symbols.material.outlined.vectors.Flag as OutlinedFlag
import io.github.hlcaptain.symbols.material.rounded.vectors.Flag as RoundedFlag
import io.github.hlcaptain.symbols.material.sharp.vectors.Flag as SharpFlag
import io.github.hlcaptain.symbols.material.outlined.vectors.Flag2 as OutlinedFlag2
import io.github.hlcaptain.symbols.material.rounded.vectors.Flag2 as RoundedFlag2
import io.github.hlcaptain.symbols.material.sharp.vectors.Flag2 as SharpFlag2
import io.github.hlcaptain.symbols.material.outlined.vectors.FlagCheck as OutlinedFlagCheck
import io.github.hlcaptain.symbols.material.rounded.vectors.FlagCheck as RoundedFlagCheck
import io.github.hlcaptain.symbols.material.sharp.vectors.FlagCheck as SharpFlagCheck
import io.github.hlcaptain.symbols.material.outlined.vectors.FlagCircle as OutlinedFlagCircle
import io.github.hlcaptain.symbols.material.rounded.vectors.FlagCircle as RoundedFlagCircle
import io.github.hlcaptain.symbols.material.sharp.vectors.FlagCircle as SharpFlagCircle
import io.github.hlcaptain.symbols.material.outlined.vectors.FlagFilled as OutlinedFlagFilled
import io.github.hlcaptain.symbols.material.rounded.vectors.FlagFilled as RoundedFlagFilled
import io.github.hlcaptain.symbols.material.sharp.vectors.FlagFilled as SharpFlagFilled
import io.github.hlcaptain.symbols.material.outlined.vectors.Flaky as OutlinedFlaky
import io.github.hlcaptain.symbols.material.rounded.vectors.Flaky as RoundedFlaky
import io.github.hlcaptain.symbols.material.sharp.vectors.Flaky as SharpFlaky
import io.github.hlcaptain.symbols.material.outlined.vectors.Flare as OutlinedFlare
import io.github.hlcaptain.symbols.material.rounded.vectors.Flare as RoundedFlare
import io.github.hlcaptain.symbols.material.sharp.vectors.Flare as SharpFlare

public val Icons.Themed.FileJson: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileJson
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileJson
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileJson
    }

public val Icons.Themed.FileMap: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileMap
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileMap
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileMap
    }

public val Icons.Themed.FileMapStack: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileMapStack
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileMapStack
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileMapStack
    }

public val Icons.Themed.FileOpen: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileOpen
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileOpen
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileOpen
    }

public val Icons.Themed.FilePng: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilePng
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilePng
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilePng
    }

public val Icons.Themed.FilePresent: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilePresent
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilePresent
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilePresent
    }

public val Icons.Themed.FileSave: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileSave
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileSave
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileSave
    }

public val Icons.Themed.FileSaveOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileSaveOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileSaveOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileSaveOff
    }

public val Icons.Themed.FileUpload: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileUpload
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileUpload
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileUpload
    }

public val Icons.Themed.FileUploadOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFileUploadOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFileUploadOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFileUploadOff
    }

public val Icons.Themed.Files: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFiles
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFiles
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFiles
    }

public val Icons.Themed.Filter: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter
    }

public val Icons.Themed.Filter1: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter1
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter1
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter1
    }

public val Icons.Themed.Filter2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter2
    }

public val Icons.Themed.Filter3: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter3
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter3
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter3
    }

public val Icons.Themed.Filter4: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter4
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter4
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter4
    }

public val Icons.Themed.Filter5: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter5
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter5
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter5
    }

public val Icons.Themed.Filter6: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter6
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter6
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter6
    }

public val Icons.Themed.Filter7: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter7
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter7
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter7
    }

public val Icons.Themed.Filter8: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter8
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter8
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter8
    }

public val Icons.Themed.Filter9: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter9
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter9
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter9
    }

public val Icons.Themed.Filter9Plus: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilter9Plus
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilter9Plus
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilter9Plus
    }

public val Icons.Themed.FilterAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterAlt
    }

public val Icons.Themed.FilterAltOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterAltOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterAltOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterAltOff
    }

public val Icons.Themed.FilterArrowRight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterArrowRight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterArrowRight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterArrowRight
    }

public val Icons.Themed.FilterBAndW: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterBAndW
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterBAndW
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterBAndW
    }

public val Icons.Themed.FilterCenterFocus: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterCenterFocus
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterCenterFocus
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterCenterFocus
    }

public val Icons.Themed.FilterDrama: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterDrama
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterDrama
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterDrama
    }

public val Icons.Themed.FilterFrames: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterFrames
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterFrames
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterFrames
    }

public val Icons.Themed.FilterHdr: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterHdr
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterHdr
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterHdr
    }

public val Icons.Themed.FilterList: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterList
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterList
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterList
    }

public val Icons.Themed.FilterListAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterListAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterListAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterListAlt
    }

public val Icons.Themed.FilterListOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterListOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterListOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterListOff
    }

public val Icons.Themed.FilterNone: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterNone
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterNone
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterNone
    }

public val Icons.Themed.FilterRetrolux: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterRetrolux
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterRetrolux
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterRetrolux
    }

public val Icons.Themed.FilterTiltShift: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterTiltShift
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterTiltShift
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterTiltShift
    }

public val Icons.Themed.FilterVintage: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFilterVintage
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFilterVintage
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFilterVintage
    }

public val Icons.Themed.Finance: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFinance
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFinance
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFinance
    }

public val Icons.Themed.FinanceChip: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFinanceChip
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFinanceChip
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFinanceChip
    }

public val Icons.Themed.FinanceMode: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFinanceMode
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFinanceMode
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFinanceMode
    }

public val Icons.Themed.FindInPage: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFindInPage
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFindInPage
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFindInPage
    }

public val Icons.Themed.FindReplace: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFindReplace
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFindReplace
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFindReplace
    }

public val Icons.Themed.Fingerprint: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFingerprint
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFingerprint
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFingerprint
    }

public val Icons.Themed.FingerprintOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFingerprintOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFingerprintOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFingerprintOff
    }

public val Icons.Themed.FireExtinguisher: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFireExtinguisher
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFireExtinguisher
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFireExtinguisher
    }

public val Icons.Themed.FireHydrant: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFireHydrant
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFireHydrant
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFireHydrant
    }

public val Icons.Themed.FireTruck: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFireTruck
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFireTruck
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFireTruck
    }

public val Icons.Themed.Fireplace: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFireplace
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFireplace
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFireplace
    }

public val Icons.Themed.FirstPage: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFirstPage
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFirstPage
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFirstPage
    }

public val Icons.Themed.FitPage: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitPage
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitPage
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitPage
    }

public val Icons.Themed.FitPageHeight: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitPageHeight
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitPageHeight
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitPageHeight
    }

public val Icons.Themed.FitPageWidth: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitPageWidth
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitPageWidth
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitPageWidth
    }

public val Icons.Themed.FitScreen: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitScreen
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitScreen
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitScreen
    }

public val Icons.Themed.FitWidth: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitWidth
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitWidth
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitWidth
    }

public val Icons.Themed.FitnessCenter: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitnessCenter
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitnessCenter
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitnessCenter
    }

public val Icons.Themed.FitnessTracker: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitnessTracker
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitnessTracker
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitnessTracker
    }

public val Icons.Themed.FitnessTrackers: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFitnessTrackers
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFitnessTrackers
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFitnessTrackers
    }

public val Icons.Themed.Flag: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlag
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlag
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlag
    }

public val Icons.Themed.Flag2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlag2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlag2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlag2
    }

public val Icons.Themed.FlagCheck: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlagCheck
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlagCheck
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlagCheck
    }

public val Icons.Themed.FlagCircle: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlagCircle
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlagCircle
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlagCircle
    }

public val Icons.Themed.FlagFilled: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlagFilled
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlagFilled
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlagFilled
    }

public val Icons.Themed.Flaky: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlaky
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlaky
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlaky
    }

public val Icons.Themed.Flare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedFlare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedFlare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpFlare
    }
