// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.VideocamAlert as OutlinedVideocamAlert
import io.github.hlcaptain.symbols.material.rounded.vectors.VideocamAlert as RoundedVideocamAlert
import io.github.hlcaptain.symbols.material.sharp.vectors.VideocamAlert as SharpVideocamAlert
import io.github.hlcaptain.symbols.material.outlined.vectors.VideocamOff as OutlinedVideocamOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VideocamOff as RoundedVideocamOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VideocamOff as SharpVideocamOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VideogameAsset as OutlinedVideogameAsset
import io.github.hlcaptain.symbols.material.rounded.vectors.VideogameAsset as RoundedVideogameAsset
import io.github.hlcaptain.symbols.material.sharp.vectors.VideogameAsset as SharpVideogameAsset
import io.github.hlcaptain.symbols.material.outlined.vectors.VideogameAssetOff as OutlinedVideogameAssetOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VideogameAssetOff as RoundedVideogameAssetOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VideogameAssetOff as SharpVideogameAssetOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewAgenda as OutlinedViewAgenda
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewAgenda as RoundedViewAgenda
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewAgenda as SharpViewAgenda
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewApps as OutlinedViewApps
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewApps as RoundedViewApps
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewApps as SharpViewApps
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewArray as OutlinedViewArray
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewArray as RoundedViewArray
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewArray as SharpViewArray
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewCarousel as OutlinedViewCarousel
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewCarousel as RoundedViewCarousel
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewCarousel as SharpViewCarousel
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewColumn as OutlinedViewColumn
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewColumn as RoundedViewColumn
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewColumn as SharpViewColumn
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewColumn2 as OutlinedViewColumn2
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewColumn2 as RoundedViewColumn2
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewColumn2 as SharpViewColumn2
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewComfy as OutlinedViewComfy
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewComfy as RoundedViewComfy
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewComfy as SharpViewComfy
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewComfyAlt as OutlinedViewComfyAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewComfyAlt as RoundedViewComfyAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewComfyAlt as SharpViewComfyAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewCompact as OutlinedViewCompact
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewCompact as RoundedViewCompact
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewCompact as SharpViewCompact
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewCompactAlt as OutlinedViewCompactAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewCompactAlt as RoundedViewCompactAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewCompactAlt as SharpViewCompactAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewCozy as OutlinedViewCozy
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewCozy as RoundedViewCozy
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewCozy as SharpViewCozy
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewDay as OutlinedViewDay
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewDay as RoundedViewDay
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewDay as SharpViewDay
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewHeadline as OutlinedViewHeadline
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewHeadline as RoundedViewHeadline
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewHeadline as SharpViewHeadline
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewInAr as OutlinedViewInAr
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewInAr as RoundedViewInAr
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewInAr as SharpViewInAr
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewInArNew as OutlinedViewInArNew
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewInArNew as RoundedViewInArNew
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewInArNew as SharpViewInArNew
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewInArOff as OutlinedViewInArOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewInArOff as RoundedViewInArOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewInArOff as SharpViewInArOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewKanban as OutlinedViewKanban
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewKanban as RoundedViewKanban
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewKanban as SharpViewKanban
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewList as OutlinedViewList
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewList as RoundedViewList
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewList as SharpViewList
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewModule as OutlinedViewModule
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewModule as RoundedViewModule
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewModule as SharpViewModule
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewObjectTrack as OutlinedViewObjectTrack
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewObjectTrack as RoundedViewObjectTrack
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewObjectTrack as SharpViewObjectTrack
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewQuilt as OutlinedViewQuilt
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewQuilt as RoundedViewQuilt
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewQuilt as SharpViewQuilt
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewRealSize as OutlinedViewRealSize
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewRealSize as RoundedViewRealSize
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewRealSize as SharpViewRealSize
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewSidebar as OutlinedViewSidebar
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewSidebar as RoundedViewSidebar
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewSidebar as SharpViewSidebar
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewStream as OutlinedViewStream
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewStream as RoundedViewStream
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewStream as SharpViewStream
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewTimeline as OutlinedViewTimeline
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewTimeline as RoundedViewTimeline
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewTimeline as SharpViewTimeline
import io.github.hlcaptain.symbols.material.outlined.vectors.ViewWeek as OutlinedViewWeek
import io.github.hlcaptain.symbols.material.rounded.vectors.ViewWeek as RoundedViewWeek
import io.github.hlcaptain.symbols.material.sharp.vectors.ViewWeek as SharpViewWeek
import io.github.hlcaptain.symbols.material.outlined.vectors.Vignette as OutlinedVignette
import io.github.hlcaptain.symbols.material.rounded.vectors.Vignette as RoundedVignette
import io.github.hlcaptain.symbols.material.sharp.vectors.Vignette as SharpVignette
import io.github.hlcaptain.symbols.material.outlined.vectors.Vignette2 as OutlinedVignette2
import io.github.hlcaptain.symbols.material.rounded.vectors.Vignette2 as RoundedVignette2
import io.github.hlcaptain.symbols.material.sharp.vectors.Vignette2 as SharpVignette2
import io.github.hlcaptain.symbols.material.outlined.vectors.Villa as OutlinedVilla
import io.github.hlcaptain.symbols.material.rounded.vectors.Villa as RoundedVilla
import io.github.hlcaptain.symbols.material.sharp.vectors.Villa as SharpVilla
import io.github.hlcaptain.symbols.material.outlined.vectors.Visibility as OutlinedVisibility
import io.github.hlcaptain.symbols.material.rounded.vectors.Visibility as RoundedVisibility
import io.github.hlcaptain.symbols.material.sharp.vectors.Visibility as SharpVisibility
import io.github.hlcaptain.symbols.material.outlined.vectors.VisibilityLock as OutlinedVisibilityLock
import io.github.hlcaptain.symbols.material.rounded.vectors.VisibilityLock as RoundedVisibilityLock
import io.github.hlcaptain.symbols.material.sharp.vectors.VisibilityLock as SharpVisibilityLock
import io.github.hlcaptain.symbols.material.outlined.vectors.VisibilityOff as OutlinedVisibilityOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VisibilityOff as RoundedVisibilityOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VisibilityOff as SharpVisibilityOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VitalSigns as OutlinedVitalSigns
import io.github.hlcaptain.symbols.material.rounded.vectors.VitalSigns as RoundedVitalSigns
import io.github.hlcaptain.symbols.material.sharp.vectors.VitalSigns as SharpVitalSigns
import io.github.hlcaptain.symbols.material.outlined.vectors.Vitals as OutlinedVitals
import io.github.hlcaptain.symbols.material.rounded.vectors.Vitals as RoundedVitals
import io.github.hlcaptain.symbols.material.sharp.vectors.Vitals as SharpVitals
import io.github.hlcaptain.symbols.material.outlined.vectors.Vo2Max as OutlinedVo2Max
import io.github.hlcaptain.symbols.material.rounded.vectors.Vo2Max as RoundedVo2Max
import io.github.hlcaptain.symbols.material.sharp.vectors.Vo2Max as SharpVo2Max
import io.github.hlcaptain.symbols.material.outlined.vectors.VoiceChat as OutlinedVoiceChat
import io.github.hlcaptain.symbols.material.rounded.vectors.VoiceChat as RoundedVoiceChat
import io.github.hlcaptain.symbols.material.sharp.vectors.VoiceChat as SharpVoiceChat
import io.github.hlcaptain.symbols.material.outlined.vectors.VoiceOverOff as OutlinedVoiceOverOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VoiceOverOff as RoundedVoiceOverOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VoiceOverOff as SharpVoiceOverOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VoiceSelection as OutlinedVoiceSelection
import io.github.hlcaptain.symbols.material.rounded.vectors.VoiceSelection as RoundedVoiceSelection
import io.github.hlcaptain.symbols.material.sharp.vectors.VoiceSelection as SharpVoiceSelection
import io.github.hlcaptain.symbols.material.outlined.vectors.VoiceSelectionOff as OutlinedVoiceSelectionOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VoiceSelectionOff as RoundedVoiceSelectionOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VoiceSelectionOff as SharpVoiceSelectionOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Voicemail as OutlinedVoicemail
import io.github.hlcaptain.symbols.material.rounded.vectors.Voicemail as RoundedVoicemail
import io.github.hlcaptain.symbols.material.sharp.vectors.Voicemail as SharpVoicemail
import io.github.hlcaptain.symbols.material.outlined.vectors.Voicemail2 as OutlinedVoicemail2
import io.github.hlcaptain.symbols.material.rounded.vectors.Voicemail2 as RoundedVoicemail2
import io.github.hlcaptain.symbols.material.sharp.vectors.Voicemail2 as SharpVoicemail2
import io.github.hlcaptain.symbols.material.outlined.vectors.Volcano as OutlinedVolcano
import io.github.hlcaptain.symbols.material.rounded.vectors.Volcano as RoundedVolcano
import io.github.hlcaptain.symbols.material.sharp.vectors.Volcano as SharpVolcano
import io.github.hlcaptain.symbols.material.outlined.vectors.VolumeDown as OutlinedVolumeDown
import io.github.hlcaptain.symbols.material.rounded.vectors.VolumeDown as RoundedVolumeDown
import io.github.hlcaptain.symbols.material.sharp.vectors.VolumeDown as SharpVolumeDown
import io.github.hlcaptain.symbols.material.outlined.vectors.VolumeDownAlt as OutlinedVolumeDownAlt
import io.github.hlcaptain.symbols.material.rounded.vectors.VolumeDownAlt as RoundedVolumeDownAlt
import io.github.hlcaptain.symbols.material.sharp.vectors.VolumeDownAlt as SharpVolumeDownAlt
import io.github.hlcaptain.symbols.material.outlined.vectors.VolumeMute as OutlinedVolumeMute
import io.github.hlcaptain.symbols.material.rounded.vectors.VolumeMute as RoundedVolumeMute
import io.github.hlcaptain.symbols.material.sharp.vectors.VolumeMute as SharpVolumeMute
import io.github.hlcaptain.symbols.material.outlined.vectors.VolumeOff as OutlinedVolumeOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VolumeOff as RoundedVolumeOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VolumeOff as SharpVolumeOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VolumeUp as OutlinedVolumeUp
import io.github.hlcaptain.symbols.material.rounded.vectors.VolumeUp as RoundedVolumeUp
import io.github.hlcaptain.symbols.material.sharp.vectors.VolumeUp as SharpVolumeUp
import io.github.hlcaptain.symbols.material.outlined.vectors.VolunteerActivism as OutlinedVolunteerActivism
import io.github.hlcaptain.symbols.material.rounded.vectors.VolunteerActivism as RoundedVolunteerActivism
import io.github.hlcaptain.symbols.material.sharp.vectors.VolunteerActivism as SharpVolunteerActivism
import io.github.hlcaptain.symbols.material.outlined.vectors.VotingChip as OutlinedVotingChip
import io.github.hlcaptain.symbols.material.rounded.vectors.VotingChip as RoundedVotingChip
import io.github.hlcaptain.symbols.material.sharp.vectors.VotingChip as SharpVotingChip
import io.github.hlcaptain.symbols.material.outlined.vectors.VpnKey as OutlinedVpnKey
import io.github.hlcaptain.symbols.material.rounded.vectors.VpnKey as RoundedVpnKey
import io.github.hlcaptain.symbols.material.sharp.vectors.VpnKey as SharpVpnKey
import io.github.hlcaptain.symbols.material.outlined.vectors.VpnKeyAlert as OutlinedVpnKeyAlert
import io.github.hlcaptain.symbols.material.rounded.vectors.VpnKeyAlert as RoundedVpnKeyAlert
import io.github.hlcaptain.symbols.material.sharp.vectors.VpnKeyAlert as SharpVpnKeyAlert
import io.github.hlcaptain.symbols.material.outlined.vectors.VpnKeyOff as OutlinedVpnKeyOff
import io.github.hlcaptain.symbols.material.rounded.vectors.VpnKeyOff as RoundedVpnKeyOff
import io.github.hlcaptain.symbols.material.sharp.vectors.VpnKeyOff as SharpVpnKeyOff
import io.github.hlcaptain.symbols.material.outlined.vectors.VpnLock as OutlinedVpnLock
import io.github.hlcaptain.symbols.material.rounded.vectors.VpnLock as RoundedVpnLock
import io.github.hlcaptain.symbols.material.sharp.vectors.VpnLock as SharpVpnLock
import io.github.hlcaptain.symbols.material.outlined.vectors.VpnLock2 as OutlinedVpnLock2
import io.github.hlcaptain.symbols.material.rounded.vectors.VpnLock2 as RoundedVpnLock2
import io.github.hlcaptain.symbols.material.sharp.vectors.VpnLock2 as SharpVpnLock2
import io.github.hlcaptain.symbols.material.outlined.vectors.Vr180Create2d as OutlinedVr180Create2d
import io.github.hlcaptain.symbols.material.rounded.vectors.Vr180Create2d as RoundedVr180Create2d
import io.github.hlcaptain.symbols.material.sharp.vectors.Vr180Create2d as SharpVr180Create2d
import io.github.hlcaptain.symbols.material.outlined.vectors.Vr180Create2dOff as OutlinedVr180Create2dOff
import io.github.hlcaptain.symbols.material.rounded.vectors.Vr180Create2dOff as RoundedVr180Create2dOff
import io.github.hlcaptain.symbols.material.sharp.vectors.Vr180Create2dOff as SharpVr180Create2dOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Vrpano as OutlinedVrpano
import io.github.hlcaptain.symbols.material.rounded.vectors.Vrpano as RoundedVrpano
import io.github.hlcaptain.symbols.material.sharp.vectors.Vrpano as SharpVrpano
import io.github.hlcaptain.symbols.material.outlined.vectors.WallArt as OutlinedWallArt
import io.github.hlcaptain.symbols.material.rounded.vectors.WallArt as RoundedWallArt
import io.github.hlcaptain.symbols.material.sharp.vectors.WallArt as SharpWallArt
import io.github.hlcaptain.symbols.material.outlined.vectors.WallLamp as OutlinedWallLamp
import io.github.hlcaptain.symbols.material.rounded.vectors.WallLamp as RoundedWallLamp
import io.github.hlcaptain.symbols.material.sharp.vectors.WallLamp as SharpWallLamp
import io.github.hlcaptain.symbols.material.outlined.vectors.Wallet as OutlinedWallet
import io.github.hlcaptain.symbols.material.rounded.vectors.Wallet as RoundedWallet
import io.github.hlcaptain.symbols.material.sharp.vectors.Wallet as SharpWallet

public val Icons.Themed.VideocamAlert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideocamAlert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideocamAlert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideocamAlert
    }

public val Icons.Themed.VideocamOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideocamOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideocamOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideocamOff
    }

public val Icons.Themed.VideogameAsset: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideogameAsset
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideogameAsset
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideogameAsset
    }

public val Icons.Themed.VideogameAssetOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVideogameAssetOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVideogameAssetOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVideogameAssetOff
    }

public val Icons.Themed.ViewAgenda: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewAgenda
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewAgenda
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewAgenda
    }

public val Icons.Themed.ViewApps: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewApps
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewApps
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewApps
    }

public val Icons.Themed.ViewArray: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewArray
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewArray
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewArray
    }

public val Icons.Themed.ViewCarousel: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewCarousel
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewCarousel
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewCarousel
    }

public val Icons.Themed.ViewColumn: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewColumn
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewColumn
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewColumn
    }

public val Icons.Themed.ViewColumn2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewColumn2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewColumn2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewColumn2
    }

public val Icons.Themed.ViewComfy: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewComfy
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewComfy
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewComfy
    }

public val Icons.Themed.ViewComfyAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewComfyAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewComfyAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewComfyAlt
    }

public val Icons.Themed.ViewCompact: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewCompact
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewCompact
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewCompact
    }

public val Icons.Themed.ViewCompactAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewCompactAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewCompactAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewCompactAlt
    }

public val Icons.Themed.ViewCozy: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewCozy
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewCozy
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewCozy
    }

public val Icons.Themed.ViewDay: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewDay
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewDay
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewDay
    }

public val Icons.Themed.ViewHeadline: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewHeadline
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewHeadline
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewHeadline
    }

public val Icons.Themed.ViewInAr: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewInAr
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewInAr
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewInAr
    }

public val Icons.Themed.ViewInArNew: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewInArNew
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewInArNew
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewInArNew
    }

public val Icons.Themed.ViewInArOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewInArOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewInArOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewInArOff
    }

public val Icons.Themed.ViewKanban: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewKanban
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewKanban
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewKanban
    }

public val Icons.Themed.ViewList: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewList
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewList
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewList
    }

public val Icons.Themed.ViewModule: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewModule
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewModule
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewModule
    }

public val Icons.Themed.ViewObjectTrack: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewObjectTrack
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewObjectTrack
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewObjectTrack
    }

public val Icons.Themed.ViewQuilt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewQuilt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewQuilt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewQuilt
    }

public val Icons.Themed.ViewRealSize: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewRealSize
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewRealSize
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewRealSize
    }

public val Icons.Themed.ViewSidebar: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewSidebar
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewSidebar
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewSidebar
    }

public val Icons.Themed.ViewStream: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewStream
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewStream
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewStream
    }

public val Icons.Themed.ViewTimeline: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewTimeline
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewTimeline
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewTimeline
    }

public val Icons.Themed.ViewWeek: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedViewWeek
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedViewWeek
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpViewWeek
    }

public val Icons.Themed.Vignette: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVignette
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVignette
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVignette
    }

public val Icons.Themed.Vignette2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVignette2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVignette2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVignette2
    }

public val Icons.Themed.Villa: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVilla
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVilla
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVilla
    }

public val Icons.Themed.Visibility: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVisibility
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVisibility
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVisibility
    }

public val Icons.Themed.VisibilityLock: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVisibilityLock
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVisibilityLock
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVisibilityLock
    }

public val Icons.Themed.VisibilityOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVisibilityOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVisibilityOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVisibilityOff
    }

public val Icons.Themed.VitalSigns: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVitalSigns
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVitalSigns
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVitalSigns
    }

public val Icons.Themed.Vitals: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVitals
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVitals
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVitals
    }

public val Icons.Themed.Vo2Max: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVo2Max
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVo2Max
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVo2Max
    }

public val Icons.Themed.VoiceChat: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVoiceChat
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVoiceChat
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVoiceChat
    }

public val Icons.Themed.VoiceOverOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVoiceOverOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVoiceOverOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVoiceOverOff
    }

public val Icons.Themed.VoiceSelection: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVoiceSelection
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVoiceSelection
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVoiceSelection
    }

public val Icons.Themed.VoiceSelectionOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVoiceSelectionOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVoiceSelectionOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVoiceSelectionOff
    }

public val Icons.Themed.Voicemail: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVoicemail
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVoicemail
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVoicemail
    }

public val Icons.Themed.Voicemail2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVoicemail2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVoicemail2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVoicemail2
    }

public val Icons.Themed.Volcano: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolcano
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolcano
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolcano
    }

public val Icons.Themed.VolumeDown: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolumeDown
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolumeDown
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolumeDown
    }

public val Icons.Themed.VolumeDownAlt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolumeDownAlt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolumeDownAlt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolumeDownAlt
    }

public val Icons.Themed.VolumeMute: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolumeMute
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolumeMute
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolumeMute
    }

public val Icons.Themed.VolumeOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolumeOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolumeOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolumeOff
    }

public val Icons.Themed.VolumeUp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolumeUp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolumeUp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolumeUp
    }

public val Icons.Themed.VolunteerActivism: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVolunteerActivism
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVolunteerActivism
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVolunteerActivism
    }

public val Icons.Themed.VotingChip: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVotingChip
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVotingChip
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVotingChip
    }

public val Icons.Themed.VpnKey: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVpnKey
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVpnKey
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVpnKey
    }

public val Icons.Themed.VpnKeyAlert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVpnKeyAlert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVpnKeyAlert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVpnKeyAlert
    }

public val Icons.Themed.VpnKeyOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVpnKeyOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVpnKeyOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVpnKeyOff
    }

public val Icons.Themed.VpnLock: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVpnLock
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVpnLock
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVpnLock
    }

public val Icons.Themed.VpnLock2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVpnLock2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVpnLock2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVpnLock2
    }

public val Icons.Themed.Vr180Create2d: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVr180Create2d
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVr180Create2d
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVr180Create2d
    }

public val Icons.Themed.Vr180Create2dOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVr180Create2dOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVr180Create2dOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVr180Create2dOff
    }

public val Icons.Themed.Vrpano: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedVrpano
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedVrpano
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpVrpano
    }

public val Icons.Themed.WallArt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedWallArt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedWallArt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpWallArt
    }

public val Icons.Themed.WallLamp: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedWallLamp
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedWallLamp
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpWallLamp
    }

public val Icons.Themed.Wallet: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (MaterialSymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedWallet
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedWallet
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpWallet
    }
