// Generated by tools/generate_material_vectors.py. DO NOT EDIT.
// Derived from Google Material Symbols 2.874 at the documented default axes.
// Copyright Google LLC. Licensed under Apache-2.0.
// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.
package io.github.hlcaptain.symbols.material.vectors.themed

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.vector.ImageVector
import io.github.hlcaptain.symbols.material.Icons
import io.github.hlcaptain.symbols.material.MaterialSymbolStyle
import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme as SymbolsTheme
import io.github.hlcaptain.symbols.material.outlined.vectors.ContentCut as OutlinedContentCut
import io.github.hlcaptain.symbols.material.rounded.vectors.ContentCut as RoundedContentCut
import io.github.hlcaptain.symbols.material.sharp.vectors.ContentCut as SharpContentCut
import io.github.hlcaptain.symbols.material.outlined.vectors.ContentPaste as OutlinedContentPaste
import io.github.hlcaptain.symbols.material.rounded.vectors.ContentPaste as RoundedContentPaste
import io.github.hlcaptain.symbols.material.sharp.vectors.ContentPaste as SharpContentPaste
import io.github.hlcaptain.symbols.material.outlined.vectors.ContentPasteGo as OutlinedContentPasteGo
import io.github.hlcaptain.symbols.material.rounded.vectors.ContentPasteGo as RoundedContentPasteGo
import io.github.hlcaptain.symbols.material.sharp.vectors.ContentPasteGo as SharpContentPasteGo
import io.github.hlcaptain.symbols.material.outlined.vectors.ContentPasteOff as OutlinedContentPasteOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ContentPasteOff as RoundedContentPasteOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ContentPasteOff as SharpContentPasteOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ContentPasteSearch as OutlinedContentPasteSearch
import io.github.hlcaptain.symbols.material.rounded.vectors.ContentPasteSearch as RoundedContentPasteSearch
import io.github.hlcaptain.symbols.material.sharp.vectors.ContentPasteSearch as SharpContentPasteSearch
import io.github.hlcaptain.symbols.material.outlined.vectors.ContextualToken as OutlinedContextualToken
import io.github.hlcaptain.symbols.material.rounded.vectors.ContextualToken as RoundedContextualToken
import io.github.hlcaptain.symbols.material.sharp.vectors.ContextualToken as SharpContextualToken
import io.github.hlcaptain.symbols.material.outlined.vectors.ContextualTokenAdd as OutlinedContextualTokenAdd
import io.github.hlcaptain.symbols.material.rounded.vectors.ContextualTokenAdd as RoundedContextualTokenAdd
import io.github.hlcaptain.symbols.material.sharp.vectors.ContextualTokenAdd as SharpContextualTokenAdd
import io.github.hlcaptain.symbols.material.outlined.vectors.Contract as OutlinedContract
import io.github.hlcaptain.symbols.material.rounded.vectors.Contract as RoundedContract
import io.github.hlcaptain.symbols.material.sharp.vectors.Contract as SharpContract
import io.github.hlcaptain.symbols.material.outlined.vectors.ContractDelete as OutlinedContractDelete
import io.github.hlcaptain.symbols.material.rounded.vectors.ContractDelete as RoundedContractDelete
import io.github.hlcaptain.symbols.material.sharp.vectors.ContractDelete as SharpContractDelete
import io.github.hlcaptain.symbols.material.outlined.vectors.ContractEdit as OutlinedContractEdit
import io.github.hlcaptain.symbols.material.rounded.vectors.ContractEdit as RoundedContractEdit
import io.github.hlcaptain.symbols.material.sharp.vectors.ContractEdit as SharpContractEdit
import io.github.hlcaptain.symbols.material.outlined.vectors.Contrast as OutlinedContrast
import io.github.hlcaptain.symbols.material.rounded.vectors.Contrast as RoundedContrast
import io.github.hlcaptain.symbols.material.sharp.vectors.Contrast as SharpContrast
import io.github.hlcaptain.symbols.material.outlined.vectors.ContrastCircle as OutlinedContrastCircle
import io.github.hlcaptain.symbols.material.rounded.vectors.ContrastCircle as RoundedContrastCircle
import io.github.hlcaptain.symbols.material.sharp.vectors.ContrastCircle as SharpContrastCircle
import io.github.hlcaptain.symbols.material.outlined.vectors.ContrastRtlOff as OutlinedContrastRtlOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ContrastRtlOff as RoundedContrastRtlOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ContrastRtlOff as SharpContrastRtlOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ContrastSquare as OutlinedContrastSquare
import io.github.hlcaptain.symbols.material.rounded.vectors.ContrastSquare as RoundedContrastSquare
import io.github.hlcaptain.symbols.material.sharp.vectors.ContrastSquare as SharpContrastSquare
import io.github.hlcaptain.symbols.material.outlined.vectors.ControlCamera as OutlinedControlCamera
import io.github.hlcaptain.symbols.material.rounded.vectors.ControlCamera as RoundedControlCamera
import io.github.hlcaptain.symbols.material.sharp.vectors.ControlCamera as SharpControlCamera
import io.github.hlcaptain.symbols.material.outlined.vectors.ControlPoint as OutlinedControlPoint
import io.github.hlcaptain.symbols.material.rounded.vectors.ControlPoint as RoundedControlPoint
import io.github.hlcaptain.symbols.material.sharp.vectors.ControlPoint as SharpControlPoint
import io.github.hlcaptain.symbols.material.outlined.vectors.ControlPointDuplicate as OutlinedControlPointDuplicate
import io.github.hlcaptain.symbols.material.rounded.vectors.ControlPointDuplicate as RoundedControlPointDuplicate
import io.github.hlcaptain.symbols.material.sharp.vectors.ControlPointDuplicate as SharpControlPointDuplicate
import io.github.hlcaptain.symbols.material.outlined.vectors.ControllerGen as OutlinedControllerGen
import io.github.hlcaptain.symbols.material.rounded.vectors.ControllerGen as RoundedControllerGen
import io.github.hlcaptain.symbols.material.sharp.vectors.ControllerGen as SharpControllerGen
import io.github.hlcaptain.symbols.material.outlined.vectors.Conversation as OutlinedConversation
import io.github.hlcaptain.symbols.material.rounded.vectors.Conversation as RoundedConversation
import io.github.hlcaptain.symbols.material.sharp.vectors.Conversation as SharpConversation
import io.github.hlcaptain.symbols.material.outlined.vectors.ConversionPath as OutlinedConversionPath
import io.github.hlcaptain.symbols.material.rounded.vectors.ConversionPath as RoundedConversionPath
import io.github.hlcaptain.symbols.material.sharp.vectors.ConversionPath as SharpConversionPath
import io.github.hlcaptain.symbols.material.outlined.vectors.ConversionPathOff as OutlinedConversionPathOff
import io.github.hlcaptain.symbols.material.rounded.vectors.ConversionPathOff as RoundedConversionPathOff
import io.github.hlcaptain.symbols.material.sharp.vectors.ConversionPathOff as SharpConversionPathOff
import io.github.hlcaptain.symbols.material.outlined.vectors.ConvertToText as OutlinedConvertToText
import io.github.hlcaptain.symbols.material.rounded.vectors.ConvertToText as RoundedConvertToText
import io.github.hlcaptain.symbols.material.sharp.vectors.ConvertToText as SharpConvertToText
import io.github.hlcaptain.symbols.material.outlined.vectors.ConveyorBelt as OutlinedConveyorBelt
import io.github.hlcaptain.symbols.material.rounded.vectors.ConveyorBelt as RoundedConveyorBelt
import io.github.hlcaptain.symbols.material.sharp.vectors.ConveyorBelt as SharpConveyorBelt
import io.github.hlcaptain.symbols.material.outlined.vectors.Cookie as OutlinedCookie
import io.github.hlcaptain.symbols.material.rounded.vectors.Cookie as RoundedCookie
import io.github.hlcaptain.symbols.material.sharp.vectors.Cookie as SharpCookie
import io.github.hlcaptain.symbols.material.outlined.vectors.CookieOff as OutlinedCookieOff
import io.github.hlcaptain.symbols.material.rounded.vectors.CookieOff as RoundedCookieOff
import io.github.hlcaptain.symbols.material.sharp.vectors.CookieOff as SharpCookieOff
import io.github.hlcaptain.symbols.material.outlined.vectors.Cooking as OutlinedCooking
import io.github.hlcaptain.symbols.material.rounded.vectors.Cooking as RoundedCooking
import io.github.hlcaptain.symbols.material.sharp.vectors.Cooking as SharpCooking
import io.github.hlcaptain.symbols.material.outlined.vectors.CoolToDry as OutlinedCoolToDry
import io.github.hlcaptain.symbols.material.rounded.vectors.CoolToDry as RoundedCoolToDry
import io.github.hlcaptain.symbols.material.sharp.vectors.CoolToDry as SharpCoolToDry
import io.github.hlcaptain.symbols.material.outlined.vectors.CopyAll as OutlinedCopyAll
import io.github.hlcaptain.symbols.material.rounded.vectors.CopyAll as RoundedCopyAll
import io.github.hlcaptain.symbols.material.sharp.vectors.CopyAll as SharpCopyAll
import io.github.hlcaptain.symbols.material.outlined.vectors.Copyright as OutlinedCopyright
import io.github.hlcaptain.symbols.material.rounded.vectors.Copyright as RoundedCopyright
import io.github.hlcaptain.symbols.material.sharp.vectors.Copyright as SharpCopyright
import io.github.hlcaptain.symbols.material.outlined.vectors.Coronavirus as OutlinedCoronavirus
import io.github.hlcaptain.symbols.material.rounded.vectors.Coronavirus as RoundedCoronavirus
import io.github.hlcaptain.symbols.material.sharp.vectors.Coronavirus as SharpCoronavirus
import io.github.hlcaptain.symbols.material.outlined.vectors.CorporateFare as OutlinedCorporateFare
import io.github.hlcaptain.symbols.material.rounded.vectors.CorporateFare as RoundedCorporateFare
import io.github.hlcaptain.symbols.material.sharp.vectors.CorporateFare as SharpCorporateFare
import io.github.hlcaptain.symbols.material.outlined.vectors.Cottage as OutlinedCottage
import io.github.hlcaptain.symbols.material.rounded.vectors.Cottage as RoundedCottage
import io.github.hlcaptain.symbols.material.sharp.vectors.Cottage as SharpCottage
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter0 as OutlinedCounter0
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter0 as RoundedCounter0
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter0 as SharpCounter0
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter1 as OutlinedCounter1
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter1 as RoundedCounter1
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter1 as SharpCounter1
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter2 as OutlinedCounter2
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter2 as RoundedCounter2
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter2 as SharpCounter2
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter3 as OutlinedCounter3
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter3 as RoundedCounter3
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter3 as SharpCounter3
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter4 as OutlinedCounter4
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter4 as RoundedCounter4
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter4 as SharpCounter4
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter5 as OutlinedCounter5
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter5 as RoundedCounter5
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter5 as SharpCounter5
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter6 as OutlinedCounter6
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter6 as RoundedCounter6
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter6 as SharpCounter6
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter7 as OutlinedCounter7
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter7 as RoundedCounter7
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter7 as SharpCounter7
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter8 as OutlinedCounter8
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter8 as RoundedCounter8
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter8 as SharpCounter8
import io.github.hlcaptain.symbols.material.outlined.vectors.Counter9 as OutlinedCounter9
import io.github.hlcaptain.symbols.material.rounded.vectors.Counter9 as RoundedCounter9
import io.github.hlcaptain.symbols.material.sharp.vectors.Counter9 as SharpCounter9
import io.github.hlcaptain.symbols.material.outlined.vectors.Countertops as OutlinedCountertops
import io.github.hlcaptain.symbols.material.rounded.vectors.Countertops as RoundedCountertops
import io.github.hlcaptain.symbols.material.sharp.vectors.Countertops as SharpCountertops
import io.github.hlcaptain.symbols.material.outlined.vectors.Create as OutlinedCreate
import io.github.hlcaptain.symbols.material.rounded.vectors.Create as RoundedCreate
import io.github.hlcaptain.symbols.material.sharp.vectors.Create as SharpCreate
import io.github.hlcaptain.symbols.material.outlined.vectors.CreateNewFolder as OutlinedCreateNewFolder
import io.github.hlcaptain.symbols.material.rounded.vectors.CreateNewFolder as RoundedCreateNewFolder
import io.github.hlcaptain.symbols.material.sharp.vectors.CreateNewFolder as SharpCreateNewFolder
import io.github.hlcaptain.symbols.material.outlined.vectors.CreditCard as OutlinedCreditCard
import io.github.hlcaptain.symbols.material.rounded.vectors.CreditCard as RoundedCreditCard
import io.github.hlcaptain.symbols.material.sharp.vectors.CreditCard as SharpCreditCard
import io.github.hlcaptain.symbols.material.outlined.vectors.CreditCardClock as OutlinedCreditCardClock
import io.github.hlcaptain.symbols.material.rounded.vectors.CreditCardClock as RoundedCreditCardClock
import io.github.hlcaptain.symbols.material.sharp.vectors.CreditCardClock as SharpCreditCardClock
import io.github.hlcaptain.symbols.material.outlined.vectors.CreditCardGear as OutlinedCreditCardGear
import io.github.hlcaptain.symbols.material.rounded.vectors.CreditCardGear as RoundedCreditCardGear
import io.github.hlcaptain.symbols.material.sharp.vectors.CreditCardGear as SharpCreditCardGear
import io.github.hlcaptain.symbols.material.outlined.vectors.CreditCardHeart as OutlinedCreditCardHeart
import io.github.hlcaptain.symbols.material.rounded.vectors.CreditCardHeart as RoundedCreditCardHeart
import io.github.hlcaptain.symbols.material.sharp.vectors.CreditCardHeart as SharpCreditCardHeart
import io.github.hlcaptain.symbols.material.outlined.vectors.CreditCardOff as OutlinedCreditCardOff
import io.github.hlcaptain.symbols.material.rounded.vectors.CreditCardOff as RoundedCreditCardOff
import io.github.hlcaptain.symbols.material.sharp.vectors.CreditCardOff as SharpCreditCardOff
import io.github.hlcaptain.symbols.material.outlined.vectors.CreditScore as OutlinedCreditScore
import io.github.hlcaptain.symbols.material.rounded.vectors.CreditScore as RoundedCreditScore
import io.github.hlcaptain.symbols.material.sharp.vectors.CreditScore as SharpCreditScore
import io.github.hlcaptain.symbols.material.outlined.vectors.Crib as OutlinedCrib
import io.github.hlcaptain.symbols.material.rounded.vectors.Crib as RoundedCrib
import io.github.hlcaptain.symbols.material.sharp.vectors.Crib as SharpCrib
import io.github.hlcaptain.symbols.material.outlined.vectors.CrisisAlert as OutlinedCrisisAlert
import io.github.hlcaptain.symbols.material.rounded.vectors.CrisisAlert as RoundedCrisisAlert
import io.github.hlcaptain.symbols.material.sharp.vectors.CrisisAlert as SharpCrisisAlert
import io.github.hlcaptain.symbols.material.outlined.vectors.Crop as OutlinedCrop
import io.github.hlcaptain.symbols.material.rounded.vectors.Crop as RoundedCrop
import io.github.hlcaptain.symbols.material.sharp.vectors.Crop as SharpCrop
import io.github.hlcaptain.symbols.material.outlined.vectors.Crop169 as OutlinedCrop169
import io.github.hlcaptain.symbols.material.rounded.vectors.Crop169 as RoundedCrop169
import io.github.hlcaptain.symbols.material.sharp.vectors.Crop169 as SharpCrop169
import io.github.hlcaptain.symbols.material.outlined.vectors.Crop32 as OutlinedCrop32
import io.github.hlcaptain.symbols.material.rounded.vectors.Crop32 as RoundedCrop32
import io.github.hlcaptain.symbols.material.sharp.vectors.Crop32 as SharpCrop32
import io.github.hlcaptain.symbols.material.outlined.vectors.Crop54 as OutlinedCrop54
import io.github.hlcaptain.symbols.material.rounded.vectors.Crop54 as RoundedCrop54
import io.github.hlcaptain.symbols.material.sharp.vectors.Crop54 as SharpCrop54
import io.github.hlcaptain.symbols.material.outlined.vectors.Crop75 as OutlinedCrop75
import io.github.hlcaptain.symbols.material.rounded.vectors.Crop75 as RoundedCrop75
import io.github.hlcaptain.symbols.material.sharp.vectors.Crop75 as SharpCrop75
import io.github.hlcaptain.symbols.material.outlined.vectors.Crop916 as OutlinedCrop916
import io.github.hlcaptain.symbols.material.rounded.vectors.Crop916 as RoundedCrop916
import io.github.hlcaptain.symbols.material.sharp.vectors.Crop916 as SharpCrop916
import io.github.hlcaptain.symbols.material.outlined.vectors.CropDin as OutlinedCropDin
import io.github.hlcaptain.symbols.material.rounded.vectors.CropDin as RoundedCropDin
import io.github.hlcaptain.symbols.material.sharp.vectors.CropDin as SharpCropDin
import io.github.hlcaptain.symbols.material.outlined.vectors.CropFree as OutlinedCropFree
import io.github.hlcaptain.symbols.material.rounded.vectors.CropFree as RoundedCropFree
import io.github.hlcaptain.symbols.material.sharp.vectors.CropFree as SharpCropFree
import io.github.hlcaptain.symbols.material.outlined.vectors.CropLandscape as OutlinedCropLandscape
import io.github.hlcaptain.symbols.material.rounded.vectors.CropLandscape as RoundedCropLandscape
import io.github.hlcaptain.symbols.material.sharp.vectors.CropLandscape as SharpCropLandscape
import io.github.hlcaptain.symbols.material.outlined.vectors.CropOriginal as OutlinedCropOriginal
import io.github.hlcaptain.symbols.material.rounded.vectors.CropOriginal as RoundedCropOriginal
import io.github.hlcaptain.symbols.material.sharp.vectors.CropOriginal as SharpCropOriginal
import io.github.hlcaptain.symbols.material.outlined.vectors.CropPortrait as OutlinedCropPortrait
import io.github.hlcaptain.symbols.material.rounded.vectors.CropPortrait as RoundedCropPortrait
import io.github.hlcaptain.symbols.material.sharp.vectors.CropPortrait as SharpCropPortrait

public val Icons.Themed.ContentCut: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContentCut
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContentCut
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContentCut
    }

public val Icons.Themed.ContentPaste: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContentPaste
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContentPaste
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContentPaste
    }

public val Icons.Themed.ContentPasteGo: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContentPasteGo
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContentPasteGo
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContentPasteGo
    }

public val Icons.Themed.ContentPasteOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContentPasteOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContentPasteOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContentPasteOff
    }

public val Icons.Themed.ContentPasteSearch: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContentPasteSearch
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContentPasteSearch
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContentPasteSearch
    }

public val Icons.Themed.ContextualToken: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContextualToken
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContextualToken
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContextualToken
    }

public val Icons.Themed.ContextualTokenAdd: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContextualTokenAdd
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContextualTokenAdd
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContextualTokenAdd
    }

public val Icons.Themed.Contract: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContract
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContract
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContract
    }

public val Icons.Themed.ContractDelete: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContractDelete
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContractDelete
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContractDelete
    }

public val Icons.Themed.ContractEdit: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContractEdit
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContractEdit
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContractEdit
    }

public val Icons.Themed.Contrast: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContrast
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContrast
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContrast
    }

public val Icons.Themed.ContrastCircle: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContrastCircle
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContrastCircle
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContrastCircle
    }

public val Icons.Themed.ContrastRtlOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContrastRtlOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContrastRtlOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContrastRtlOff
    }

public val Icons.Themed.ContrastSquare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedContrastSquare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedContrastSquare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpContrastSquare
    }

public val Icons.Themed.ControlCamera: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedControlCamera
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedControlCamera
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpControlCamera
    }

public val Icons.Themed.ControlPoint: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedControlPoint
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedControlPoint
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpControlPoint
    }

public val Icons.Themed.ControlPointDuplicate: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedControlPointDuplicate
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedControlPointDuplicate
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpControlPointDuplicate
    }

public val Icons.Themed.ControllerGen: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedControllerGen
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedControllerGen
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpControllerGen
    }

public val Icons.Themed.Conversation: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedConversation
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedConversation
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpConversation
    }

public val Icons.Themed.ConversionPath: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedConversionPath
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedConversionPath
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpConversionPath
    }

public val Icons.Themed.ConversionPathOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedConversionPathOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedConversionPathOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpConversionPathOff
    }

public val Icons.Themed.ConvertToText: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedConvertToText
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedConvertToText
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpConvertToText
    }

public val Icons.Themed.ConveyorBelt: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedConveyorBelt
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedConveyorBelt
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpConveyorBelt
    }

public val Icons.Themed.Cookie: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCookie
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCookie
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCookie
    }

public val Icons.Themed.CookieOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCookieOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCookieOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCookieOff
    }

public val Icons.Themed.Cooking: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCooking
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCooking
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCooking
    }

public val Icons.Themed.CoolToDry: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCoolToDry
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCoolToDry
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCoolToDry
    }

public val Icons.Themed.CopyAll: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCopyAll
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCopyAll
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCopyAll
    }

public val Icons.Themed.Copyright: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCopyright
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCopyright
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCopyright
    }

public val Icons.Themed.Coronavirus: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCoronavirus
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCoronavirus
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCoronavirus
    }

public val Icons.Themed.CorporateFare: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCorporateFare
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCorporateFare
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCorporateFare
    }

public val Icons.Themed.Cottage: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCottage
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCottage
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCottage
    }

public val Icons.Themed.Counter0: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter0
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter0
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter0
    }

public val Icons.Themed.Counter1: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter1
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter1
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter1
    }

public val Icons.Themed.Counter2: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter2
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter2
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter2
    }

public val Icons.Themed.Counter3: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter3
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter3
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter3
    }

public val Icons.Themed.Counter4: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter4
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter4
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter4
    }

public val Icons.Themed.Counter5: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter5
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter5
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter5
    }

public val Icons.Themed.Counter6: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter6
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter6
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter6
    }

public val Icons.Themed.Counter7: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter7
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter7
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter7
    }

public val Icons.Themed.Counter8: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter8
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter8
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter8
    }

public val Icons.Themed.Counter9: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCounter9
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCounter9
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCounter9
    }

public val Icons.Themed.Countertops: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCountertops
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCountertops
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCountertops
    }

public val Icons.Themed.Create: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreate
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreate
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreate
    }

public val Icons.Themed.CreateNewFolder: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreateNewFolder
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreateNewFolder
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreateNewFolder
    }

public val Icons.Themed.CreditCard: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreditCard
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreditCard
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreditCard
    }

public val Icons.Themed.CreditCardClock: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreditCardClock
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreditCardClock
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreditCardClock
    }

public val Icons.Themed.CreditCardGear: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreditCardGear
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreditCardGear
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreditCardGear
    }

public val Icons.Themed.CreditCardHeart: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreditCardHeart
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreditCardHeart
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreditCardHeart
    }

public val Icons.Themed.CreditCardOff: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreditCardOff
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreditCardOff
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreditCardOff
    }

public val Icons.Themed.CreditScore: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCreditScore
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCreditScore
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCreditScore
    }

public val Icons.Themed.Crib: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrib
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrib
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrib
    }

public val Icons.Themed.CrisisAlert: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrisisAlert
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrisisAlert
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrisisAlert
    }

public val Icons.Themed.Crop: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrop
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrop
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrop
    }

public val Icons.Themed.Crop169: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrop169
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrop169
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrop169
    }

public val Icons.Themed.Crop32: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrop32
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrop32
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrop32
    }

public val Icons.Themed.Crop54: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrop54
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrop54
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrop54
    }

public val Icons.Themed.Crop75: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrop75
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrop75
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrop75
    }

public val Icons.Themed.Crop916: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCrop916
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCrop916
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCrop916
    }

public val Icons.Themed.CropDin: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCropDin
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCropDin
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCropDin
    }

public val Icons.Themed.CropFree: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCropFree
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCropFree
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCropFree
    }

public val Icons.Themed.CropLandscape: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCropLandscape
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCropLandscape
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCropLandscape
    }

public val Icons.Themed.CropOriginal: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCropOriginal
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCropOriginal
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCropOriginal
    }

public val Icons.Themed.CropPortrait: ImageVector
    @Composable
    @ReadOnlyComposable
    get() = when (SymbolsTheme.style) {
        MaterialSymbolStyle.Outlined -> Icons.Outlined.OutlinedCropPortrait
        MaterialSymbolStyle.Rounded -> Icons.Rounded.RoundedCropPortrait
        MaterialSymbolStyle.Sharp -> Icons.Sharp.SharpCropPortrait
    }
