#!/usr/bin/env python3
"""Generate sample-only SVG/XML reference pages from the pinned Material fonts."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from xml.sax.saxutils import escape

import generate_material_vectors as vectors


PACKAGE = "io.github.hlcaptain.symbols.sample.imagevectormigration.gallery"
PAGE_SIZE = 128
COLUMNS = 8
CELL = 40
ICON_X = 8
ICON_Y = 2
WIDTH = COLUMNS * CELL
HEIGHT = PAGE_SIZE // COLUMNS * CELL
KINDS = (("outlined", 0), ("rounded", 0), ("sharp", 0), ("rounded", 1))
HEADER = "// Generated by tools/generate_material_gallery.py. DO NOT EDIT.\n"


def render_reference(paths: tuple[str, ...], *, svg: bool) -> str:
    if svg:
        lines = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}">']
    else:
        lines = [
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
            f'    android:width="{WIDTH}dp" android:height="{HEIGHT}dp"',
            f'    android:viewportWidth="{WIDTH}" android:viewportHeight="{HEIGHT}">',
        ]
    for index, path in enumerate(paths):
        x = index % COLUMNS * CELL + ICON_X
        y = index // COLUMNS * CELL + ICON_Y
        if svg:
            lines.append(f'  <g transform="translate({x} {y})"><path fill="#000000" fill-rule="nonzero" d="{escape(path)}"/></g>')
        else:
            lines.extend((
                f'  <group android:translateX="{x}" android:translateY="{y}">',
                f'    <path android:fillColor="#FF000000" android:fillType="nonZero" android:pathData="{escape(path)}"/>',
                '  </group>',
            ))
    lines.append('</svg>' if svg else '</vector>')
    return '\n'.join(lines) + '\n'


def render_filled_selector(points: tuple[int, ...], names: dict[int, tuple[str, ...]]) -> str:
    lines = [HEADER.rstrip(), f"package {PACKAGE}", "",
             "import androidx.compose.ui.graphics.vector.ImageVector",
             "import io.github.hlcaptain.symbols.Symbols",
             "import io.github.hlcaptain.symbols.material.Filled",
             "import io.github.hlcaptain.symbols.material.Material",
             "import io.github.hlcaptain.symbols.material.Rounded"]
    for point in points:
        lines.append(f"import io.github.hlcaptain.symbols.material.rounded.vectors.{vectors.kotlin_identifier(names[point][0])}")
    lines += ["", "// This sample intentionally visits the entire catalog; production typed access stays direct.",
              "internal fun filledGalleryVector(index: Int): ImageVector = when (index / 64) {"]
    for start in range(0, len(points), 64):
        lines.append(f"    {start // 64} -> filledGalleryChunk{start // 64:03d}(index)")
    lines += ['    else -> error("Gallery index outside catalog: $index")', "}", ""]
    for start in range(0, len(points), 64):
        lines.append(f"private fun filledGalleryChunk{start // 64:03d}(index: Int): ImageVector = when (index) {{")
        for index, point in enumerate(points[start:start + 64], start):
            lines.append(f"    {index} -> Symbols.Material.Rounded.Filled.{vectors.kotlin_identifier(names[point][0])}")
        lines += ['    else -> error("Gallery index outside chunk: $index")', "}", ""]
    return '\n'.join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    entries = vectors.parse_codepoints(vectors.CODEPOINTS_PATH)
    names = vectors.group_names_by_code_point(entries)
    points = tuple(sorted(names))
    font, svg_pen, transform_pen, version = vectors.import_fonttools()
    output: dict[Path, str] = {}
    pages = []
    fonts = {}
    for style_name, fill in KINDS:
        style = vectors.Style(style_name, style_name.title())
        paths = vectors.extract_paths(style, points, font, svg_pen, transform_pen, fill=float(fill))
        fonts[style_name] = hashlib.sha256(style.font_path.read_bytes()).hexdigest()
        for number, start in enumerate(range(0, len(points), PAGE_SIZE)):
            name = f"material_gallery_{style_name}_fill{fill}_{number:03d}"
            page_paths = paths[start:start + PAGE_SIZE]
            for source_set, extension in (("nonAndroidMain", "svg"), ("androidMain", "xml")):
                path = args.output / source_set / "composeResources/drawable" / f"{name}.{extension}"
                output[path] = render_reference(page_paths, svg=extension == "svg")
            pages.append({"resource": name, "style": style_name, "fill": fill, "page": number,
                          "codepoints": [f"U+{point:04X}" for point in points[start:start + PAGE_SIZE]]})
    kotlin_dir = args.output / "commonMain/kotlin" / PACKAGE.replace('.', '/')
    output[kotlin_dir / "FilledGalleryVectors.generated.kt"] = render_filled_selector(points, names)
    constants = {"PageSize": PAGE_SIZE, "Columns": COLUMNS, "CellSize": CELL,
                 "IconX": ICON_X, "IconY": ICON_Y, "Width": WIDTH, "Height": HEIGHT,
                 "CodePointCount": len(points), "PagesPerKind": (len(points) + PAGE_SIZE - 1) // PAGE_SIZE}
    output[kotlin_dir / "MaterialGalleryGeometry.generated.kt"] = HEADER + f"package {PACKAGE}\n\n" + '\n'.join(
        f"internal const val Gallery{name}: Int = {value}" for name, value in constants.items()
    ) + '\n'
    output[args.output / "manifest.json"] = json.dumps({"fonttools": version, "font_sha256": fonts,
        "names": len(entries), "unique_codepoints": len(points), "cases": len(points) * len(KINDS),
        "pages": pages}, indent=2) + '\n'
    existing = set(args.output.rglob("*")) if args.output.exists() else set()
    for stale in existing - output.keys():
        if stale.is_file() and (stale.name.startswith("material_gallery_") or stale.name.endswith(".generated.kt")):
            stale.unlink()
    for path, content in output.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print(f"Generated {len(pages)} reference pages per platform, {len(points) * len(KINDS)} cases; fonts unchanged.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
