#!/usr/bin/env python3
"""Generate source-owned catalogs for the commonMain sample Preview."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

from generate_material_symbols import CatalogError, Entry, parse_codepoints


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = (
    REPOSITORY_ROOT
    / "composeApp/src/commonMain/kotlin/io/github/hlcaptain/symbols/sample"
    / "SampleCatalogs.generated.kt"
)
CATALOGS = (
    ("AcademmuniconsCatalog", "fonts/samples/academmunicons/Academmunicons.codepoints"),
    (
        "FontAwesomeCatalog",
        "fonts/samples/font-awesome-free-solid/FontAwesomeFreeSolid.codepoints",
    ),
    ("PowerlineCatalog", "fonts/samples/powerline/PowerlineSymbols.codepoints"),
    (
        "TablerFilledCatalog",
        "fonts/samples/tabler-icons-filled/TablerIconsFilled.codepoints",
    ),
    (
        "TablerOutlineCatalog",
        "fonts/samples/tabler-icons-outline/TablerIconsOutline.codepoints",
    ),
)
CHUNK_SIZE = 200


def render_catalog(name: str, entries: Sequence[Entry]) -> list[str]:
    function_name = name[0].lower() + name[1:]
    lines: list[str] = []
    chunks = [entries[i : i + CHUNK_SIZE] for i in range(0, len(entries), CHUNK_SIZE)]
    for index, chunk in enumerate(chunks):
        lines.append(
            f"private fun {function_name}{index:03d}(): List<DemoIcon> = listOf("
        )
        lines.extend(
            f'    DemoIcon("{entry.name}", 0x{entry.code_point:X}),' for entry in chunk
        )
        lines.extend((")", ""))

    lines.extend(
        (
            f"internal val {name}: List<DemoIcon> by lazy {{",
            f"    buildList({len(entries)}) {{",
            *(f"        addAll({function_name}{index:03d}())" for index in range(len(chunks))),
            "    }",
            "}",
            "",
        )
    )
    return lines


def render() -> str:
    lines = [
        "// Generated by tools/generate_sample_catalogs.py. DO NOT EDIT.",
        '@file:Suppress("LargeClass", "MagicNumber")',
        "package io.github.hlcaptain.symbols.sample",
        "",
    ]
    for name, relative_path in CATALOGS:
        lines.extend(render_catalog(name, parse_codepoints(REPOSITORY_ROOT / relative_path)))
    return "\n".join(lines)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    try:
        content = render()
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else None
        if current != content:
            if arguments.check:
                raise CatalogError(
                    f"Generated sample catalog is missing or stale: {OUTPUT}\n"
                    "Run tools/generate_sample_catalogs.py."
                )
            OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    except CatalogError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(f"{OUTPUT}: {'up to date' if current == content else 'generated'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
