#!/usr/bin/env python3
"""Generate deterministic Compose ImageVector packs from Material Symbols fonts.

This is a maintainer-only source generator. Consumer builds compile the checked-in
Kotlin snapshots and never invoke Python or FontTools.

Run with the repository's pinned FontTools environment:

    /tmp/symbols-fonttools/bin/python tools/generate_material_vectors.py
    /tmp/symbols-fonttools/bin/python tools/generate_material_vectors.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
CODEPOINTS_PATH = REPOSITORY_ROOT / "fonts/material/MaterialSymbols.codepoints"
PACKAGE_ROOT = "io/github/hlcaptain/symbols/material"
THEMED_PACKAGE = "io.github.hlcaptain.symbols.material.vectors.themed"
THEMED_SOURCE_DIRECTORY = (
    REPOSITORY_ROOT
    / "symbols/material-vectors-themed/src/commonMain/kotlin"
    / THEMED_PACKAGE.replace(".", "/")
)
PINNED_FONTTOOLS_VERSION = "4.60.2"
EXPECTED_NAME_COUNT = 4_102
EXPECTED_CODE_POINT_COUNT = 3_802
UNITS_PER_EM = 960
VIEWPORT_SIZE = 24
ICONS_PER_FILE = 64
AXIS_LOCATION = {
    "FILL": 0.0,
    "GRAD": 0.0,
    "opsz": 24.0,
    "wght": 400.0,
}
GENERATED_HEADER = (
    "// Generated by tools/generate_material_vectors.py. DO NOT EDIT.\n"
    "// Derived from Google Material Symbols 2.874 at the documented default axes.\n"
    "// Copyright Google LLC. Licensed under Apache-2.0.\n"
    "// See THIRD_PARTY_NOTICES.md for immutable provenance and modification details.\n"
)
CODEPOINT_LINE = re.compile(
    r"^(?P<name>[a-z0-9]+(?:_[a-z0-9]+)*)[ \t]+"
    r"(?P<code_point>[0-9a-fA-F]{1,6})[ \t]*$"
)
PATH_TOKEN = re.compile(
    r"[MLHVQZ]|[-+]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][-+]?\d+)?"
)
PATH_COMMANDS = frozenset("MLHVQZ")
PATH_OPERATION = {
    "L": ("lineTo", 2),
    "H": ("horizontalLineTo", 1),
    "V": ("verticalLineTo", 1),
    "Q": ("quadTo", 4),
}


class GenerationError(RuntimeError):
    """Raised when the checked-in inputs cannot produce a valid snapshot."""


@dataclass(frozen=True)
class Style:
    name: str
    title: str
    typed_root: str = "Icons"

    @property
    def font_path(self) -> Path:
        return (
            REPOSITORY_ROOT
            / f"fonts/material/{self.name}/composeResources/font"
            / f"material_symbols_{self.name}_variable.ttf"
        )

    @property
    def source_directory(self) -> Path:
        return (
            REPOSITORY_ROOT
            / f"symbols/material-vectors-{self.name}/src/commonMain/kotlin"
            / PACKAGE_ROOT
            / self.name
            / "vectors"
        )

    @property
    def package_name(self) -> str:
        return f"io.github.hlcaptain.symbols.material.{self.name}.vectors"


STYLES = (
    Style("outlined", "Outlined"),
    Style("rounded", "Rounded"),
    Style("sharp", "Sharp"),
)


def kotlin_identifier(name: str) -> str:
    """Convert a canonical snake_case name to its typed Kotlin property."""

    identifier = "".join(
        part[0].upper() + part[1:]
        for part in name.split("_")
    )
    return f"_{identifier}" if identifier[0].isdigit() else identifier


def import_fonttools() -> tuple[Any, Any, Any, str]:
    try:
        import fontTools
        from fontTools.pens.svgPathPen import SVGPathPen
        from fontTools.pens.transformPen import TransformPen
        from fontTools.ttLib import TTFont
    except ImportError as error:
        raise GenerationError(
            "FontTools is required for maintainer generation. Run this script with "
            "/tmp/symbols-fonttools/bin/python or install the pinned "
            f"fonttools=={PINNED_FONTTOOLS_VERSION}."
        ) from error

    if fontTools.__version__ != PINNED_FONTTOOLS_VERSION:
        raise GenerationError(
            f"Expected fonttools=={PINNED_FONTTOOLS_VERSION}, "
            f"found {fontTools.__version__}. Refusing non-deterministic generation."
        )
    return TTFont, SVGPathPen, TransformPen, fontTools.__version__


def parse_codepoints(path: Path) -> tuple[tuple[str, int], ...]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError as error:
        raise GenerationError(f"Codepoints file does not exist: {path}") from error

    entries: list[tuple[str, int]] = []
    names: set[str] = set()
    name_by_identifier: dict[str, str] = {}
    for line_number, line in enumerate(lines, start=1):
        if not line.strip():
            continue
        match = CODEPOINT_LINE.fullmatch(line)
        if match is None:
            raise GenerationError(
                f"{path}:{line_number}: expected '<snake_case_name> <hex_code_point>'"
            )
        name = match.group("name")
        if name in names:
            raise GenerationError(
                f"{path}:{line_number}: duplicate symbol name {name!r}"
            )
        identifier = kotlin_identifier(name)
        previous_name = name_by_identifier.get(identifier)
        if previous_name is not None:
            raise GenerationError(
                f"{path}:{line_number}: Kotlin identifier collision: "
                f"{previous_name!r} and {name!r} both become {identifier!r}"
            )
        names.add(name)
        name_by_identifier[identifier] = name
        code_point = int(match.group("code_point"), 16)
        if (
            code_point > 0x10FFFF
            or 0xD800 <= code_point <= 0xDFFF
        ):
            raise GenerationError(
                f"{path}:{line_number}: U+{code_point:04X} "
                "is not a Unicode scalar value"
            )
        entries.append((name, code_point))

    unique_code_points = {code_point for _, code_point in entries}
    if len(entries) != EXPECTED_NAME_COUNT:
        raise GenerationError(
            f"Expected {EXPECTED_NAME_COUNT:,} symbol names, found {len(entries):,}"
        )
    if len(unique_code_points) != EXPECTED_CODE_POINT_COUNT:
        raise GenerationError(
            "Expected "
            f"{EXPECTED_CODE_POINT_COUNT:,} unique code points, "
            f"found {len(unique_code_points):,}"
        )
    return tuple(entries)


def format_coordinate(value: float) -> str:
    """Format an SVG coordinate deterministically with at most four decimals."""

    if abs(value) < 0.00005:
        return "0"
    rendered = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if rendered == "-0" else rendered


def extract_paths(
    style: Style,
    code_points: Sequence[int],
    tt_font: Any,
    svg_path_pen: Any,
    transform_pen: Any,
) -> tuple[str, ...]:
    if not style.font_path.is_file():
        raise GenerationError(f"Font does not exist: {style.font_path}")

    font = tt_font(
        style.font_path,
        lazy=False,
        recalcBBoxes=False,
        recalcTimestamp=False,
    )
    try:
        units_per_em = font["head"].unitsPerEm
        if units_per_em != UNITS_PER_EM:
            raise GenerationError(
                f"{style.font_path}: expected UPEM {UNITS_PER_EM}, "
                f"found {units_per_em}"
            )

        axes = {axis.axisTag: axis for axis in font["fvar"].axes}
        if set(AXIS_LOCATION) - set(axes):
            missing = ", ".join(sorted(set(AXIS_LOCATION) - set(axes)))
            raise GenerationError(f"{style.font_path}: missing axes: {missing}")
        for tag, value in AXIS_LOCATION.items():
            axis = axes[tag]
            if not axis.minValue <= value <= axis.maxValue:
                raise GenerationError(
                    f"{style.font_path}: {tag}={value:g} is outside "
                    f"{axis.minValue:g}..{axis.maxValue:g}"
                )

        cmap = font.getBestCmap()
        missing_code_points = [value for value in code_points if value not in cmap]
        if missing_code_points:
            rendered = ", ".join(
                f"U+{value:04X}" for value in missing_code_points[:10]
            )
            raise GenerationError(
                f"{style.font_path}: missing catalog code points: {rendered}"
            )

        glyph_set = font.getGlyphSet(location=AXIS_LOCATION)
        scale = VIEWPORT_SIZE / UNITS_PER_EM
        # Font outlines are y-up in a 960 UPEM square. Compose vector paths are
        # y-down in a 24x24 viewport. Transform only; deliberately do not clamp
        # glyph overshoot outside that viewport.
        transform = (scale, 0, 0, -scale, 0, VIEWPORT_SIZE)
        paths: list[str] = []
        for code_point in code_points:
            pen = svg_path_pen(glyph_set, ntos=format_coordinate)
            glyph_set[cmap[code_point]].draw(transform_pen(pen, transform))
            commands = pen.getCommands()
            if not commands:
                raise GenerationError(
                    f"{style.font_path}: U+{code_point:04X} has no outline"
                )
            paths.append(commands)
        return tuple(paths)
    finally:
        font.close()


def render_int_array(values: Sequence[int]) -> list[str]:
    rendered = [f"0x{value:X}" for value in values]
    return [
        f"    {', '.join(rendered[start:start + 12])},"
        for start in range(0, len(rendered), 12)
    ]


def group_names_by_code_point(
    entries: Sequence[tuple[str, int]],
) -> dict[int, tuple[str, ...]]:
    grouped: defaultdict[int, list[str]] = defaultdict(list)
    for name, code_point in entries:
        grouped[code_point].append(name)
    return {
        code_point: tuple(sorted(names))
        for code_point, names in grouped.items()
    }


def tokenize_path(path: str) -> tuple[str, ...]:
    tokens: list[str] = []
    position = 0
    for match in PATH_TOKEN.finditer(path):
        separator = path[position : match.start()]
        if separator.strip(" ,\t\r\n"):
            raise GenerationError(
                f"Unsupported SVG path syntax near {separator!r} in {path!r}"
            )
        tokens.append(match.group())
        position = match.end()
    trailing = path[position:]
    if trailing.strip(" ,\t\r\n"):
        raise GenerationError(
            f"Unsupported SVG path syntax near {trailing!r} in {path!r}"
        )
    if not tokens:
        raise GenerationError("Cannot render an empty SVG path")
    return tuple(tokens)


def render_path_operations(path: str) -> tuple[str, ...]:
    """Render a compact absolute SVG path as shrinkable PathBuilder calls."""

    tokens = tokenize_path(path)
    operations: list[str] = []
    index = 0
    command: str | None = None
    while index < len(tokens):
        token = tokens[index]
        if token in PATH_COMMANDS:
            command = token
            index += 1
            if command == "Z":
                operations.append("close()")
                command = None
                continue
        elif command is None:
            raise GenerationError(
                f"SVG path operand {token!r} has no command in {path!r}"
            )

        if command == "M":
            operation, arity = "moveTo", 2
        elif command is not None:
            try:
                operation, arity = PATH_OPERATION[command]
            except KeyError as error:
                raise GenerationError(
                    f"Unsupported SVG path command {command!r} in {path!r}"
                ) from error
        else:
            raise GenerationError(f"Missing SVG path command in {path!r}")

        operands = tokens[index : index + arity]
        if len(operands) != arity or any(
            operand in PATH_COMMANDS for operand in operands
        ):
            raise GenerationError(
                f"SVG path command {command!r} has incomplete operands in {path!r}"
            )
        arguments = ", ".join(f"{operand}f" for operand in operands)
        operations.append(f"{operation}({arguments})")
        index += arity
        if command == "M":
            # Additional coordinate pairs after an SVG move are implicit lines.
            command = "L"

    return tuple(operations)


def render_public_api(style: Style) -> str:
    prefix = style.name
    title = style.title
    return "\n".join(
        (
            GENERATED_HEADER.rstrip(),
            f"package {style.package_name}",
            "",
            "import androidx.compose.ui.graphics.vector.ImageVector",
            "import io.github.hlcaptain.symbols.material.MaterialSymbol",
            "",
            "/**",
            f" * The {title} ImageVector snapshot for this symbol at",
            " * `FILL=0, GRAD=0, opsz=24, wght=400`.",
            " *",
            " * Repeated access, including access through code-point aliases, returns",
            " * the same lazily built instance. Each unique code point owns one default",
            " * cache, shared by its typed alias getters.",
            " */",
            f"public val MaterialSymbol.{prefix}ImageVector: ImageVector",
            f"    get() = as{title}ImageVector()",
            "",
            "/**",
            f" * Returns the cached {title} ImageVector snapshot for this symbol.",
            " *",
            " * [autoMirror] selects a separately cached vector whose renderer mirrors",
            " * it in right-to-left layout. The source outline itself is unchanged.",
            " */",
            (
                f"public fun MaterialSymbol.as{title}ImageVector("
                "autoMirror: Boolean = false): ImageVector {"
            ),
            f"    val vectorIndex = {prefix}VectorIndex(codePoint)",
            "    require(vectorIndex >= 0) {",
            (
                f'        "MaterialSymbol \'$name\' '
                "(U+${codePoint.toString(16).uppercase()}) "
                f'is not in the {title} vector snapshot"'
            ),
            "    }",
            f"    return {prefix}VectorAt(vectorIndex, autoMirror)",
            "}",
            "",
        )
    )


def render_index(style: Style, code_points: Sequence[int], chunk_count: int) -> str:
    prefix = style.name
    lines = [
        GENERATED_HEADER.rstrip(),
        f"package {style.package_name}",
        "",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "",
        f"internal const val {prefix}VectorCount: Int = {len(code_points)}",
        "",
        '@Suppress("MagicNumber")',
        f"internal val {prefix}VectorCodePoints: IntArray = intArrayOf(",
        *render_int_array(code_points),
        ")",
        "",
        f"internal fun {prefix}VectorIndex(codePoint: Int): Int {{",
        "    var low = 0",
        f"    var high = {prefix}VectorCodePoints.lastIndex",
        "    while (low <= high) {",
        "        val middle = (low + high).ushr(1)",
        f"        val candidate = {prefix}VectorCodePoints[middle]",
        "        when {",
        "            candidate < codePoint -> low = middle + 1",
        "            candidate > codePoint -> high = middle - 1",
        "            else -> return middle",
        "        }",
        "    }",
        "    return -1",
        "}",
        "",
        (
            f"internal fun {prefix}VectorAt("
            "index: Int, autoMirror: Boolean): ImageVector {"
        ),
        f'    require(index in 0 until {prefix}VectorCount) {{ "index: $index" }}',
        f"    return when (index / {ICONS_PER_FILE}) {{",
    ]
    for chunk_index in range(chunk_count):
        lines.append(
            f"        {chunk_index} -> "
            f"{prefix}VectorChunk{chunk_index:03d}(index, autoMirror)"
        )
    lines.extend(
        (
            '        else -> error("unreachable index: $index")',
            "    }",
            "}",
            "",
        )
    )
    return "\n".join(lines)


def render_icon_file(
    style: Style,
    chunk_index: int,
    start: int,
    code_points: Sequence[int],
    paths: Sequence[str],
    names_by_code_point: dict[int, tuple[str, ...]],
) -> str:
    prefix = style.name
    title = style.title
    lines = [
        GENERATED_HEADER.rstrip(),
        f"package {style.package_name}",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.path",
        "import androidx.compose.ui.unit.dp",
        f"import io.github.hlcaptain.symbols.material.{style.typed_root}",
        "",
    ]
    for code_point, path in zip(code_points, paths):
        object_name = f"{title}Vector{code_point:X}"
        names = names_by_code_point.get(code_point)
        if not names:
            raise GenerationError(
                f"{style.name}: U+{code_point:04X} has no typed symbol names"
            )
        for name in names:
            identifier = kotlin_identifier(name)
            lines.extend(
                (
                    f"public val {style.typed_root}.{title}.{identifier}: ImageVector",
                    f"    get() = {object_name}.value(autoMirror = false)",
                    "",
                )
            )

        mirror_suffix = (
            'if (autoMirror) ".AutoMirrored" else ""'
        )
        lines.extend(
            (
                f"private object {object_name} {{",
                "    private val default: ImageVector by lazy {",
                "        build(autoMirror = false)",
                "    }",
                "",
                "    private val autoMirrored: ImageVector by lazy {",
                "        build(autoMirror = true)",
                "    }",
                "",
                "    public fun value(autoMirror: Boolean): ImageVector =",
                "        if (autoMirror) autoMirrored else default",
                "",
                "    private fun build(autoMirror: Boolean): ImageVector {",
                f"        val mirrorSuffix = {mirror_suffix}",
                "        return ImageVector.Builder(",
                (
                    f'            name = "MaterialSymbols{title}.'
                    f'U+{code_point:X}$mirrorSuffix",'
                ),
                "            defaultWidth = 24.dp,",
                "            defaultHeight = 24.dp,",
                "            viewportWidth = 24f,",
                "            viewportHeight = 24f,",
                "            autoMirror = autoMirror,",
                "        ).apply {",
                "            path(fill = SolidColor(Color.Black)) {",
                *(
                    f"                {operation}"
                    for operation in render_path_operations(path)
                ),
                "            }",
                "        }.build()",
                "    }",
                "}",
                "",
            )
        )

    lines.extend(
        (
            '@Suppress("CyclomaticComplexMethod", "MagicNumber")',
            (
                f"internal fun {prefix}VectorChunk{chunk_index:03d}("
                "index: Int, autoMirror: Boolean): ImageVector = when (index) {"
            ),
        )
    )
    for offset, code_point in enumerate(code_points):
        object_name = f"{title}Vector{code_point:X}"
        lines.append(
            f"    {start + offset} -> {object_name}.value(autoMirror)"
        )
    lines.extend(
        (
            '    else -> error("index outside generated chunk: $index")',
            "}",
            "",
        )
    )
    return "\n".join(lines)


def render_themed_icon_file(
    entries: Sequence[tuple[str, int]],
) -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        f"package {THEMED_PACKAGE}",
        "",
        "import androidx.compose.runtime.Composable",
        "import androidx.compose.runtime.ReadOnlyComposable",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import io.github.hlcaptain.symbols.material.Icons",
        "import io.github.hlcaptain.symbols.material.MaterialSymbolStyle",
        "import io.github.hlcaptain.symbols.material.MaterialSymbolsTheme as SymbolsTheme",
    ]
    for name, _ in entries:
        identifier = kotlin_identifier(name)
        for style in STYLES:
            lines.append(
                f"import {style.package_name}.{identifier} as "
                f"{style.title}{identifier}"
            )
    lines.append("")

    for name, _ in entries:
        identifier = kotlin_identifier(name)
        lines.extend(
            (
                f"public val Icons.Themed.{identifier}: ImageVector",
                "    @Composable",
                "    @ReadOnlyComposable",
                "    get() = when (SymbolsTheme.style) {",
                (
                    "        MaterialSymbolStyle.Outlined -> "
                    f"Icons.Outlined.Outlined{identifier}"
                ),
                (
                    "        MaterialSymbolStyle.Rounded -> "
                    f"Icons.Rounded.Rounded{identifier}"
                ),
                (
                    "        MaterialSymbolStyle.Sharp -> "
                    f"Icons.Sharp.Sharp{identifier}"
                ),
                "    }",
                "",
            )
        )
    return "\n".join(lines)


def render_themed(entries: Sequence[tuple[str, int]]) -> dict[Path, str]:
    return {
        THEMED_SOURCE_DIRECTORY / f"ThemedIcons{chunk_index:03d}.generated.kt":
            render_themed_icon_file(
                entries[start : start + ICONS_PER_FILE]
            )
        for chunk_index, start in enumerate(range(0, len(entries), ICONS_PER_FILE))
    }


def render_style(
    style: Style,
    entries: Sequence[tuple[str, int]],
    code_points: Sequence[int],
    paths: Sequence[str],
) -> dict[Path, str]:
    if len(paths) != len(code_points):
        raise GenerationError(
            f"{style.name}: {len(paths)} paths for {len(code_points)} code points"
        )

    chunk_count = (
        len(code_points) + ICONS_PER_FILE - 1
    ) // ICONS_PER_FILE
    names_by_code_point = group_names_by_code_point(entries)
    rendered = {
        style.source_directory
        / f"MaterialSymbols{style.title}Vectors.generated.kt": render_public_api(style),
        style.source_directory
        / f"{style.title}VectorIndex.generated.kt": render_index(
            style,
            code_points,
            chunk_count,
        ),
    }
    for chunk_index, start in enumerate(
        range(0, len(code_points), ICONS_PER_FILE)
    ):
        chunk_code_points = code_points[start : start + ICONS_PER_FILE]
        chunk_paths = paths[start : start + ICONS_PER_FILE]
        rendered[
            style.source_directory
            / f"{style.title}Icons{chunk_index:03d}.generated.kt"
        ] = render_icon_file(
            style,
            chunk_index,
            start,
            chunk_code_points,
            chunk_paths,
            names_by_code_point,
        )
    return rendered


def synchronize_generated(
    rendered: dict[Path, str],
    styles: Sequence[Style],
    *,
    check: bool,
) -> tuple[int, int]:
    expected = set(rendered)
    existing = {
        path
        for style in styles
        if style.source_directory.is_dir()
        for path in style.source_directory.glob("*.generated.kt")
    }
    if THEMED_SOURCE_DIRECTORY.is_dir():
        existing.update(THEMED_SOURCE_DIRECTORY.glob("*.generated.kt"))
    stale = sorted(existing - expected)
    changed = [
        path
        for path, content in sorted(rendered.items())
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]

    if check and (changed or stale):
        details = [
            *(f"missing or stale: {path.relative_to(REPOSITORY_ROOT)}" for path in changed),
            *(f"unexpected generated file: {path.relative_to(REPOSITORY_ROOT)}" for path in stale),
        ]
        raise GenerationError(
            "Generated vector sources are stale:\n  "
            + "\n  ".join(details)
            + "\nRun tools/generate_material_vectors.py with the pinned FontTools environment."
        )

    if not check:
        for path in stale:
            if not path.read_text(encoding="utf-8").startswith(GENERATED_HEADER):
                raise GenerationError(f"Refusing to remove unrecognized file: {path}")
            path.unlink()
        for path in changed:
            path.parent.mkdir(parents=True, exist_ok=True)
            with path.open("w", encoding="utf-8", newline="\n") as output:
                output.write(rendered[path])

    total_bytes = sum(len(content.encode("utf-8")) for content in rendered.values())
    return len(changed) + len(stale), total_bytes


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--style",
        action="append",
        choices=[style.name for style in STYLES],
        help="Generate/check only this style; repeat for multiple styles (default: all).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when generated output is missing or stale.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    arguments = create_parser().parse_args(argv)
    selected_names = set(arguments.style or ())
    selected_styles = tuple(
        style for style in STYLES if not selected_names or style.name in selected_names
    )

    try:
        entries = parse_codepoints(CODEPOINTS_PATH)
        code_points = tuple(sorted({code_point for _, code_point in entries}))
        tt_font, svg_path_pen, transform_pen, fonttools_version = import_fonttools()
        rendered: dict[Path, str] = {}
        for style in selected_styles:
            paths = extract_paths(
                style,
                code_points,
                tt_font,
                svg_path_pen,
                transform_pen,
            )
            rendered.update(render_style(style, entries, code_points, paths))
        rendered.update(render_themed(entries))
        changed, total_bytes = synchronize_generated(
            rendered,
            selected_styles,
            check=arguments.check,
        )
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    state = "up to date" if changed == 0 else f"{changed} files updated"
    style_names = ", ".join(style.name for style in selected_styles)
    print(
        f"{state}; {style_names}; {len(entries):,} names / "
        f"{len(code_points):,} code points; {total_bytes:,} source bytes; "
        f"fonttools {fonttools_version}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
