#!/usr/bin/env python3
"""Generate allocation-free, style-typed font symbol namespaces.

The generated API keeps the semantic catalog in ``material-core`` as the
single source of truth while allowing style-aware catalog access such as:

    val check = Symbols.Rounded.Check.symbol

The output contains only inline wrapper getters. Font resources remain in the
independently selectable style artifacts.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
TOOLS_DIRECTORY = Path(__file__).resolve().parent
if str(TOOLS_DIRECTORY) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIRECTORY))

from generate_material_symbols import (  # noqa: E402
    CatalogError,
    Entry,
    kotlin_identifier,
    parse_codepoints,
)


DEFAULT_INPUT = REPOSITORY_ROOT / "fonts/material/MaterialSymbols.codepoints"
DEFAULT_OUTPUT_ROOT = (
    REPOSITORY_ROOT
    / "symbols/material-compose/src/commonMain/kotlin"
    / "io/github/hlcaptain/symbols/material"
    / "generated"
)
PACKAGE_NAME = "io.github.hlcaptain.symbols.material"
SYMBOLS_PER_FILE = 128
GENERATED_FILE_GLOB = "MaterialSymbols*FontNames*.generated.kt"


class GenerationError(RuntimeError):
    """Raised when the checked-in namespace output is missing or stale."""


@dataclass(frozen=True)
class Style:
    title: str

    @property
    def wrapper_type(self) -> str:
        return f"{self.title}MaterialSymbol"


STYLES = (
    Style("Outlined"),
    Style("Rounded"),
    Style("Sharp"),
)


def render_chunk(
    style: Style,
    entries: Sequence[Entry],
    chunk_index: int,
) -> str:
    lines = [
        "// Generated by tools/generate_material_font_namespaces.py. DO NOT EDIT.",
        '@file:Suppress("ObjectPropertyName")',
        "",
        f"package {PACKAGE_NAME}",
        "",
    ]
    for entry in entries:
        identifier = kotlin_identifier(entry.name)
        lines.extend(
            (
                (
                    f"/** `{entry.name}` (U+{entry.code_point:X}) as a "
                    f"{style.title} font glyph. */"
                ),
                (
                    f"val Symbols.{style.title}.{identifier}: "
                    f"{style.wrapper_type}"
                ),
                (
                    f"    get() = {style.wrapper_type}("
                    f"MaterialSymbols.{identifier})"
                ),
                "",
            )
        )
    return "\n".join(lines)


def generated_file_name(style: Style, chunk_index: int) -> str:
    return (
        f"MaterialSymbols{style.title}FontNames"
        f"{chunk_index:03d}.generated.kt"
    )


def generate_outputs(
    entries: Sequence[Entry],
    output_root: Path = DEFAULT_OUTPUT_ROOT,
) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for style in STYLES:
        for chunk_index, offset in enumerate(
            range(0, len(entries), SYMBOLS_PER_FILE)
        ):
            chunk = entries[offset : offset + SYMBOLS_PER_FILE]
            path = output_root / generated_file_name(style, chunk_index)
            outputs[path] = render_chunk(style, chunk, chunk_index)
    return outputs


def write_outputs(
    outputs: Mapping[Path, str],
    output_root: Path,
    *,
    check: bool,
) -> bool:
    expected_paths = set(outputs)
    existing_paths = (
        set(output_root.glob(GENERATED_FILE_GLOB))
        if output_root.is_dir()
        else set()
    )
    stale_paths = existing_paths - expected_paths
    mismatched_paths = {
        path
        for path, content in outputs.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    }

    if check and (stale_paths or mismatched_paths):
        details = [
            *(f"stale: {path}" for path in sorted(stale_paths)),
            *(f"missing or changed: {path}" for path in sorted(mismatched_paths)),
        ]
        raise GenerationError(
            "Generated font namespaces are stale.\n"
            "Run tools/generate_material_font_namespaces.py.\n"
            + "\n".join(details)
        )

    if not stale_paths and not mismatched_paths:
        return False

    output_root.mkdir(parents=True, exist_ok=True)
    for path in stale_paths:
        path.unlink()
    for path in mismatched_paths:
        with path.open("w", encoding="utf-8", newline="\n") as generated_file:
            generated_file.write(outputs[path])
    return True


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=f"Canonical codepoints file (default: {DEFAULT_INPUT})",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT,
        help=f"Generated Kotlin directory (default: {DEFAULT_OUTPUT_ROOT})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when checked-in output is stale.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    options = create_parser().parse_args(argv)
    try:
        entries = parse_codepoints(options.input)
        outputs = generate_outputs(entries, options.output_root)
        changed = write_outputs(
            outputs,
            options.output_root,
            check=options.check,
        )
    except (CatalogError, GenerationError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if options.check:
        print(f"Verified {len(outputs)} generated font namespace files.")
    elif changed:
        print(f"Generated {len(outputs)} font namespace files.")
    else:
        print(f"{len(outputs)} font namespace files are already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
