#!/usr/bin/env python3
"""Generate API-21-compatible static Material Symbols font instances.

This is a maintainer/CI tool. Consumer builds use the Gradle symbol-font
generator for vectors and never require Python or FontTools.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Sequence

try:
    import fontTools
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont

    FONTTOOLS_IMPORT_ERROR: ImportError | None = None
except ImportError as error:
    fontTools = None  # type: ignore[assignment]
    TTFont = None  # type: ignore[assignment,misc]
    instantiateVariableFont = None  # type: ignore[assignment]
    FONTTOOLS_IMPORT_ERROR = error


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
EXPECTED_FONTTOOLS_VERSION = "4.60.2"
DEFAULT_AXES = {
    "FILL": 0.0,
    "GRAD": 0.0,
    "opsz": 24.0,
    "wght": 400.0,
}
VARIABLE_TABLES = frozenset({"avar", "fvar", "gvar", "HVAR", "MVAR", "VVAR"})


@dataclass(frozen=True)
class StaticFontSpec:
    style: str
    input_path: Path
    output_path: Path


FONT_SPECS = tuple(
    StaticFontSpec(
        style=style,
        input_path=Path(
            f"fonts/material/{style}/composeResources/font/"
            f"material_symbols_{style}_variable.ttf"
        ),
        output_path=Path(
            f"fonts/material/{style}-static/composeResources/font/"
            f"material_symbols_{style}_regular.ttf"
        ),
    )
    for style in ("outlined", "rounded", "sharp")
)


def _require_fonttools() -> None:
    if FONTTOOLS_IMPORT_ERROR is not None:
        raise RuntimeError(
            "FontTools is required. Install "
            "tools/requirements-font-verification.txt in an isolated environment."
        ) from FONTTOOLS_IMPORT_ERROR
    if fontTools.version != EXPECTED_FONTTOOLS_VERSION:
        raise RuntimeError(
            f"Expected FontTools {EXPECTED_FONTTOOLS_VERSION}, "
            f"found {fontTools.version}."
        )


def instantiate_static_font(input_path: Path) -> bytes:
    """Return a deterministic static instance at the documented default axes."""

    _require_fonttools()
    source = TTFont(input_path, recalcTimestamp=False)
    try:
        if "fvar" not in source:
            raise ValueError(f"Input is not a variable font: {input_path}")
        available_axes = {
            axis.axisTag: (axis.minValue, axis.defaultValue, axis.maxValue)
            for axis in source["fvar"].axes
        }
        missing_axes = sorted(DEFAULT_AXES.keys() - available_axes.keys())
        if missing_axes:
            raise ValueError(
                f"{input_path} is missing required axes: {', '.join(missing_axes)}"
            )
        for tag, value in DEFAULT_AXES.items():
            minimum, _, maximum = available_axes[tag]
            if not minimum <= value <= maximum:
                raise ValueError(
                    f"{input_path} axis {tag} cannot represent {value}; "
                    f"range is {minimum}..{maximum}"
                )

        static_font = instantiateVariableFont(
            source,
            DEFAULT_AXES,
            inplace=False,
            optimize=True,
        )
        remaining_tables = VARIABLE_TABLES.intersection(static_font.keys())
        if remaining_tables:
            raise AssertionError(
                "Static instancing retained variable tables: "
                + ", ".join(sorted(remaining_tables))
            )

        output = BytesIO()
        static_font.recalcTimestamp = False
        static_font.save(output, reorderTables=True)
        return output.getvalue()
    finally:
        source.close()


def sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def process_spec(spec: StaticFontSpec, *, check: bool) -> tuple[int, str]:
    input_path = REPOSITORY_ROOT / spec.input_path
    output_path = REPOSITORY_ROOT / spec.output_path
    generated = instantiate_static_font(input_path)

    if check:
        if not output_path.is_file():
            raise RuntimeError(f"Missing generated static font: {spec.output_path}")
        actual = output_path.read_bytes()
        if actual != generated:
            raise RuntimeError(
                f"Generated static font is stale: {spec.output_path}\n"
                f"expected SHA-256 {sha256(generated)}\n"
                f"actual SHA-256   {sha256(actual)}"
            )
    else:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_bytes(generated)

    return len(generated), sha256(generated)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when a checked-in static font differs from regenerated bytes.",
    )
    parser.add_argument(
        "--style",
        choices=tuple(spec.style for spec in FONT_SPECS),
        action="append",
        help="Generate only this style. Repeat for multiple styles.",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    selected_styles = set(args.style or ())
    specs = tuple(
        spec
        for spec in FONT_SPECS
        if not selected_styles or spec.style in selected_styles
    )

    try:
        for spec in specs:
            byte_length, digest = process_spec(spec, check=args.check)
            verb = "Verified" if args.check else "Generated"
            print(
                f"{verb} {spec.style} static font: "
                f"{byte_length:,} bytes, SHA-256 {digest}"
            )
    except (AssertionError, OSError, RuntimeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
